// Generated by truewire — do not edit by hand.
import type { MessageInitShape } from '@bufbuild/protobuf'
import type { GrpcCallOptions, GrpcEndpoint } from '@truewire/core/grpc'
import type { GrpcMeta } from '../meta.js'
import { Query, type QueryBalanceRequestSchema, type QueryBalanceResponse } from '../protos/demo/bank/v1/query_pb.js'

/** The `demo.bank.v1.QueryBalanceRequest` message the call sends: a partial object or a full message. */
export type Request = MessageInitShape<typeof QueryBalanceRequestSchema>

/** The `demo.bank.v1.QueryBalanceResponse` message the call returns. */
export type Response = QueryBalanceResponse

/** The stub's descriptor of `demo.bank.v1.Query.Balance`. */
export const method = Query.method.balance

/** Query one denomination's balance of an address. */
export class Balance {
  constructor(readonly core: GrpcEndpoint<GrpcMeta>) {}

  /**
   * Query one denomination's balance of an address.
   *
   * @see https://docs.cosmos.network/main/build/modules/bank
   */
  async balance(request: Request = {}, options?: GrpcCallOptions): Promise<Response> {
    return this.core.unary({ method, request, meta: { public: true }, ...options })
  }
}
