// Code generated by truewire. DO NOT EDIT.

// Package batchcancel is the `trading_ws.batch_cancel` endpoint.
package batchcancel

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
)

type BatchCancelReplyMethod string

const BatchCancelReplyMethodBatchCancel BatchCancelReplyMethod = "batch_cancel"

// UnmarshalJSON accepts only the literal's values.
func (v *BatchCancelReplyMethod) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, BatchCancelReplyMethodBatchCancel)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v BatchCancelReplyMethod) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, BatchCancelReplyMethodBatchCancel)
}

// Reply to a `batch_cancel` request -- the count lives directly on the frame, not under a `result` key.
type BatchCancelReply struct {
	// Echoes the request method, `batch_cancel`.
	Method BatchCancelReplyMethod
	// Echoes the request's correlation id.
	ReqID int64
	// `true` on a successful cancellation.
	Success bool
	// Number of orders cancelled. Confirmed live -- upstream's docs page instead describes a nested `result: {count, warnings}` shape, which the real reply does not send; see `notes`.
	OrdersCancelled *int64
	// Non-fatal warnings about the cancellation, if any. Documented by upstream nested under `result`; kept top-level here to match the real reply's flat shape, unconfirmed live (none appeared in this run's capture).
	Warnings []string
	// Server receive timestamp.
	TimeIn *truewire.TimestampIso
	// Server response timestamp.
	TimeOut *truewire.TimestampIso
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *BatchCancelReply) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("method", &r.Method),
		truewire.Required("req_id", &r.ReqID),
		truewire.Required("success", &r.Success),
		truewire.OptionalField("orders_cancelled", &r.OrdersCancelled),
		truewire.OptionalField("warnings", &r.Warnings),
		truewire.OptionalField("time_in", &r.TimeIn),
		truewire.OptionalField("time_out", &r.TimeOut),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r BatchCancelReply) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("method", &r.Method),
		truewire.Required("req_id", &r.ReqID),
		truewire.Required("success", &r.Success),
		truewire.OptionalField("orders_cancelled", &r.OrdersCancelled),
		truewire.OptionalField("warnings", &r.Warnings),
		truewire.OptionalField("time_in", &r.TimeIn),
		truewire.OptionalField("time_out", &r.TimeOut),
	)
}

// Parameters for cancelling multiple orders (minimum 2, maximum 50) in a single request, identified by a mix of client or Kraken identifiers.
type Request struct {
	// List containing either client `order_userref` or Kraken `order_id` identifiers, 2 to 50 of them.
	Orders []string
	// List of client `cl_ord_id` identifiers.
	ClOrdID []string
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Request) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("orders", &r.Orders),
		truewire.OptionalField("cl_ord_id", &r.ClOrdID),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Request) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("orders", &r.Orders),
		truewire.OptionalField("cl_ord_id", &r.ClOrdID),
	)
}

// Endpoint is the `trading_ws.batch_cancel` endpoint.
//
// Cancels multiple orders (minimum 2, maximum 50) in a single request, identified by a mix of client or Kraken identifiers.
type Endpoint struct {
	core truewire.CommandEndpoint
}

// New returns the endpoint over core.
func New(core truewire.CommandEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// Cancels multiple orders (minimum 2, maximum 50) in a single request, identified by a mix of client or Kraken identifiers.
//
// See https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/batch_cancel.
func (e *Endpoint) BatchCancel(ctx context.Context, request Request, opts ...truewire.CallOption) (BatchCancelReply, error) {
	return truewire.DecodeResult[BatchCancelReply](e.BatchCancelRaw(ctx, request, opts...))
}

// BatchCancelRaw is BatchCancel without validation: the wire body as it came.
func (e *Endpoint) BatchCancelRaw(ctx context.Context, request Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	body, err := truewire.Dump(request)
	if err != nil {
		return nil, err
	}
	return e.core.Command(ctx, truewire.CommandCall{Path: "batch_cancel", Request: body, Options: truewire.Options(opts...)})
}
