// Code generated by truewire. DO NOT EDIT.

// Package balance is the `spot.account.balance` endpoint.
package balance

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/kraken/src/kraken/meta"
)

type AccountBalance = map[string]truewire.Decimal

type RequestRebaseMultiplier string

const RequestRebaseMultiplierRebased RequestRebaseMultiplier = "rebased"
const RequestRebaseMultiplierBase RequestRebaseMultiplier = "base"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestRebaseMultiplier) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestRebaseMultiplierRebased, RequestRebaseMultiplierBase)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestRebaseMultiplier) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestRebaseMultiplierRebased, RequestRebaseMultiplierBase)
}

type Request struct {
	// Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity, `base` displays in terms of SPV tokens.
	RebaseMultiplier truewire.Optional[*RequestRebaseMultiplier]
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Request) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalNullable("rebase_multiplier", &r.RebaseMultiplier),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Request) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalNullable("rebase_multiplier", &r.RebaseMultiplier),
	)
}

// Endpoint is the `spot.account.balance` endpoint.
//
// Retrieve all cash balances, net of pending withdrawals.
//
// **Note on Staking/Earn assets:** assets migrated from the legacy Staking system to the new Earn system may appear in balances and ledgers with symbol extensions -- `.B` (new yield-bearing products), `.F` (auto-earning Kraken Rewards), `.S`/`.M` (legacy staked/opt-in-reward balances), `.T` (tokenized assets). These are read-only for transacting; use the base asset (e.g. `USDT`) instead.
//
// **API Key Permissions Required:** `Funds permissions - Query`
type Endpoint struct {
	core truewire.HttpEndpoint
}

// New returns the endpoint over core.
func New(core truewire.HttpEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// Retrieve all cash balances, net of pending withdrawals.
//
// **Note on Staking/Earn assets:** assets migrated from the legacy Staking system to the new Earn system may appear in balances and ledgers with symbol extensions -- `.B` (new yield-bearing products), `.F` (auto-earning Kraken Rewards), `.S`/`.M` (legacy staked/opt-in-reward balances), `.T` (tokenized assets). These are read-only for transacting; use the base asset (e.g. `USDT`) instead.
//
// **API Key Permissions Required:** `Funds permissions - Query`
//
// See https://docs.kraken.com/api-reference/account-data/get-account-balance.
func (e *Endpoint) Balance(ctx context.Context, request Request, opts ...truewire.CallOption) (AccountBalance, error) {
	return truewire.DecodeResult[AccountBalance](e.BalanceRaw(ctx, request, opts...))
}

// BalanceRaw is Balance without validation: the wire body as it came.
func (e *Endpoint) BalanceRaw(ctx context.Context, request Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	body, err := truewire.Dump(request)
	if err != nil {
		return nil, err
	}
	return e.core.Request(ctx, truewire.HttpCall{Method: "POST", Path: "/0/private/Balance", Request: body, Meta: meta.SpotMeta{Signed: truewire.Ptr(true)}, Options: truewire.Options(opts...)})
}
