// Code generated by truewire. DO NOT EDIT.

// Package pretrade is the `spot.market_data.pre_trade` endpoint.
package pretrade

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/kraken/src/kraken/meta"
)

type PreTradeAskLevelSide string

const PreTradeAskLevelSideSell PreTradeAskLevelSide = "SELL"

// UnmarshalJSON accepts only the literal's values.
func (v *PreTradeAskLevelSide) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, PreTradeAskLevelSideSell)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v PreTradeAskLevelSide) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, PreTradeAskLevelSideSell)
}

// One aggregated ask price level.
type PreTradeAskLevel struct {
	// Indicates this level is an offer.
	Side *PreTradeAskLevelSide
	// Price level in the Central Limit Order Book (CLOB).
	Price *string
	// The aggregated quantity at the price level.
	Qty *string
	// The number of orders in the price level.
	Count *int64
	// Timestamp the order at this price level was submitted.
	SubmissionTs *truewire.TimestampIso
	// Timestamp the price level was last updated and published.
	PublicationTs *truewire.TimestampIso
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *PreTradeAskLevel) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalField("side", &r.Side),
		truewire.OptionalField("price", &r.Price),
		truewire.OptionalField("qty", &r.Qty),
		truewire.OptionalField("count", &r.Count),
		truewire.OptionalField("submission_ts", &r.SubmissionTs),
		truewire.OptionalField("publication_ts", &r.PublicationTs),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r PreTradeAskLevel) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalField("side", &r.Side),
		truewire.OptionalField("price", &r.Price),
		truewire.OptionalField("qty", &r.Qty),
		truewire.OptionalField("count", &r.Count),
		truewire.OptionalField("submission_ts", &r.SubmissionTs),
		truewire.OptionalField("publication_ts", &r.PublicationTs),
	)
}

type PreTradeBidLevelSide string

const PreTradeBidLevelSideBuy PreTradeBidLevelSide = "BUY"

// UnmarshalJSON accepts only the literal's values.
func (v *PreTradeBidLevelSide) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, PreTradeBidLevelSideBuy)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v PreTradeBidLevelSide) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, PreTradeBidLevelSideBuy)
}

// One aggregated bid price level.
type PreTradeBidLevel struct {
	// Indicates this level is a bid.
	Side *PreTradeBidLevelSide
	// Price level in the Central Limit Order Book (CLOB).
	Price *string
	// The aggregated quantity at the price level.
	Qty *string
	// The number of orders in the price level.
	Count *int64
	// Timestamp the order at this price level was submitted.
	SubmissionTs *truewire.TimestampIso
	// Timestamp the price level was last updated and published.
	PublicationTs *truewire.TimestampIso
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *PreTradeBidLevel) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalField("side", &r.Side),
		truewire.OptionalField("price", &r.Price),
		truewire.OptionalField("qty", &r.Qty),
		truewire.OptionalField("count", &r.Count),
		truewire.OptionalField("submission_ts", &r.SubmissionTs),
		truewire.OptionalField("publication_ts", &r.PublicationTs),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r PreTradeBidLevel) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalField("side", &r.Side),
		truewire.OptionalField("price", &r.Price),
		truewire.OptionalField("qty", &r.Qty),
		truewire.OptionalField("count", &r.Count),
		truewire.OptionalField("submission_ts", &r.SubmissionTs),
		truewire.OptionalField("publication_ts", &r.PublicationTs),
	)
}

type Request struct {
	// A list of symbols for the currency pairs.
	Symbol string
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Request) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("symbol", &r.Symbol),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Request) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("symbol", &r.Symbol),
	)
}

type PreTradeBookBaseNotation string

const PreTradeBookBaseNotationUnit PreTradeBookBaseNotation = "UNIT"
const PreTradeBookBaseNotationNoml PreTradeBookBaseNotation = "NOML"

// UnmarshalJSON accepts only the literal's values.
func (v *PreTradeBookBaseNotation) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, PreTradeBookBaseNotationUnit, PreTradeBookBaseNotationNoml)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v PreTradeBookBaseNotation) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, PreTradeBookBaseNotationUnit, PreTradeBookBaseNotationNoml)
}

type PreTradeBookQuoteNotation string

const PreTradeBookQuoteNotationMone PreTradeBookQuoteNotation = "MONE"

// UnmarshalJSON accepts only the literal's values.
func (v *PreTradeBookQuoteNotation) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, PreTradeBookQuoteNotationMone)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v PreTradeBookQuoteNotation) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, PreTradeBookQuoteNotationMone)
}

type PreTradeBookVenue string

const PreTradeBookVenuePgsl PreTradeBookVenue = "PGSL"

// UnmarshalJSON accepts only the literal's values.
func (v *PreTradeBookVenue) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, PreTradeBookVenuePgsl)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v PreTradeBookVenue) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, PreTradeBookVenuePgsl)
}

type PreTradeBookSystem string

const PreTradeBookSystemClob PreTradeBookSystem = "CLOB"

// UnmarshalJSON accepts only the literal's values.
func (v *PreTradeBookSystem) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, PreTradeBookSystemClob)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v PreTradeBookSystem) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, PreTradeBookSystemClob)
}

// The top-10-level aggregated order book for a pair, plus reference/venue metadata.
type PreTradeBook struct {
	// The symbol of the currency pair.
	Symbol *string
	// The full description of the currency pair.
	Description *string
	// ISO 4217 currency code for the base asset.
	BaseAsset *string
	// Digital Token Identifier (DTI) code for the base asset.
	BaseDtiCode *string
	// DTI short name for the base asset.
	BaseDtiShortName *string
	// Digital Token Identifier (DTI) code for the quote asset.
	QuoteDtiCode *string
	// DTI short name for the quote asset.
	QuoteDtiShortName *string
	// Indicates how the base quantity is expressed: `UNIT` (nominal units) or `NOML` (notional value).
	BaseNotation *PreTradeBookBaseNotation
	// ISO 4217 currency in which the trading price is expressed.
	QuoteAsset *string
	// Indicates that the price is expressed in monetary value.
	QuoteNotation *PreTradeBookQuoteNotation
	// ISO 10383 Market Identifier Code (MIC) of the trading platform where the order was submitted.
	Venue *PreTradeBookVenue
	// Indicates the order system is a Central Limit Order Book.
	System *PreTradeBookSystem
	// Top-10 aggregated bid levels.
	Bids []PreTradeBidLevel
	// Top-10 aggregated ask levels.
	Asks []PreTradeAskLevel
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *PreTradeBook) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalField("symbol", &r.Symbol),
		truewire.OptionalField("description", &r.Description),
		truewire.OptionalField("base_asset", &r.BaseAsset),
		truewire.OptionalField("base_dti_code", &r.BaseDtiCode),
		truewire.OptionalField("base_dti_short_name", &r.BaseDtiShortName),
		truewire.OptionalField("quote_dti_code", &r.QuoteDtiCode),
		truewire.OptionalField("quote_dti_short_name", &r.QuoteDtiShortName),
		truewire.OptionalField("base_notation", &r.BaseNotation),
		truewire.OptionalField("quote_asset", &r.QuoteAsset),
		truewire.OptionalField("quote_notation", &r.QuoteNotation),
		truewire.OptionalField("venue", &r.Venue),
		truewire.OptionalField("system", &r.System),
		truewire.OptionalField("bids", &r.Bids),
		truewire.OptionalField("asks", &r.Asks),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r PreTradeBook) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalField("symbol", &r.Symbol),
		truewire.OptionalField("description", &r.Description),
		truewire.OptionalField("base_asset", &r.BaseAsset),
		truewire.OptionalField("base_dti_code", &r.BaseDtiCode),
		truewire.OptionalField("base_dti_short_name", &r.BaseDtiShortName),
		truewire.OptionalField("quote_dti_code", &r.QuoteDtiCode),
		truewire.OptionalField("quote_dti_short_name", &r.QuoteDtiShortName),
		truewire.OptionalField("base_notation", &r.BaseNotation),
		truewire.OptionalField("quote_asset", &r.QuoteAsset),
		truewire.OptionalField("quote_notation", &r.QuoteNotation),
		truewire.OptionalField("venue", &r.Venue),
		truewire.OptionalField("system", &r.System),
		truewire.OptionalField("bids", &r.Bids),
		truewire.OptionalField("asks", &r.Asks),
	)
}

// Endpoint is the `spot.market_data.pre_trade` endpoint.
//
// Returns the price levels in the order book with aggregated order quantities at each price level. The top 10 levels are returned for each trading pair.
type Endpoint struct {
	core truewire.HttpEndpoint
}

// New returns the endpoint over core.
func New(core truewire.HttpEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// Returns the price levels in the order book with aggregated order quantities at each price level. The top 10 levels are returned for each trading pair.
//
// See https://docs.kraken.com/api-reference/transparency/pre-trade-data.
func (e *Endpoint) PreTrade(ctx context.Context, request Request, opts ...truewire.CallOption) (PreTradeBook, error) {
	return truewire.DecodeResult[PreTradeBook](e.PreTradeRaw(ctx, request, opts...))
}

// PreTradeRaw is PreTrade without validation: the wire body as it came.
func (e *Endpoint) PreTradeRaw(ctx context.Context, request Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	body, err := truewire.Dump(request)
	if err != nil {
		return nil, err
	}
	return e.core.Request(ctx, truewire.HttpCall{Method: "GET", Path: "/0/public/PreTrade", Request: body, Meta: meta.SpotMeta{}, Options: truewire.Options(opts...)})
}
