// Code generated by truewire. DO NOT EDIT.

// Package cancelall is the `spot.trading.cancel_all` endpoint.
package cancelall

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/kraken/src/kraken/meta"
)

// Result of a cancel request.
type OrderCancelled struct {
	// Number of orders cancelled.
	Count *int64
	// If true, orders are pending cancellation.
	Pending *bool
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *OrderCancelled) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalField("count", &r.Count),
		truewire.OptionalField("pending", &r.Pending),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r OrderCancelled) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalField("count", &r.Count),
		truewire.OptionalField("pending", &r.Pending),
	)
}

// Endpoint is the `spot.trading.cancel_all` endpoint.
//
// Cancel every open order for the account.
//
// **API Key Permissions Required:** `Orders and trades - Create & modify orders` or `Orders and trades - Cancel & close orders`
type Endpoint struct {
	core truewire.HttpEndpoint
}

// New returns the endpoint over core.
func New(core truewire.HttpEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// Cancel every open order for the account.
//
// **API Key Permissions Required:** `Orders and trades - Create & modify orders` or `Orders and trades - Cancel & close orders`
//
// See https://docs.kraken.com/api-reference/trading/cancel-all-orders.
func (e *Endpoint) CancelAll(ctx context.Context, opts ...truewire.CallOption) (OrderCancelled, error) {
	return truewire.DecodeResult[OrderCancelled](e.CancelAllRaw(ctx, opts...))
}

// CancelAllRaw is CancelAll without validation: the wire body as it came.
func (e *Endpoint) CancelAllRaw(ctx context.Context, opts ...truewire.CallOption) (json.RawMessage, error) {
	return e.core.Request(ctx, truewire.HttpCall{Method: "POST", Path: "/0/private/CancelAll", Meta: meta.SpotMeta{Signed: truewire.Ptr(true)}, Options: truewire.Options(opts...)})
}
