// Code generated by truewire. DO NOT EDIT.

// Package list is the `issues.list` endpoint.
package list

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/github/src/github/meta"
	"truewire.dev/examples/github/src/github/types"
)

// Present when the row is a pull request.
type IssuePullRequest struct {
	// API URL of the pull request.
	URL string
	// Web page of the pull request.
	HTMLURL string
	// When the pull request was merged; null if not merged.
	MergedAt truewire.Optional[*truewire.TimestampIso]
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *IssuePullRequest) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("url", &r.URL),
		truewire.Required("html_url", &r.HTMLURL),
		truewire.OptionalNullable("merged_at", &r.MergedAt),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r IssuePullRequest) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("url", &r.URL),
		truewire.Required("html_url", &r.HTMLURL),
		truewire.OptionalNullable("merged_at", &r.MergedAt),
	)
}

type RequestState string

const RequestStateOpen RequestState = "open"
const RequestStateClosed RequestState = "closed"
const RequestStateAll RequestState = "all"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestState) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestStateOpen, RequestStateClosed, RequestStateAll)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestState) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestStateOpen, RequestStateClosed, RequestStateAll)
}

type RequestSort string

const RequestSortCreated RequestSort = "created"
const RequestSortUpdated RequestSort = "updated"
const RequestSortComments RequestSort = "comments"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestSort) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestSortCreated, RequestSortUpdated, RequestSortComments)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestSort) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestSortCreated, RequestSortUpdated, RequestSortComments)
}

type RequestDirection string

const RequestDirectionAsc RequestDirection = "asc"
const RequestDirectionDesc RequestDirection = "desc"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestDirection) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestDirectionAsc, RequestDirectionDesc)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestDirection) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestDirectionAsc, RequestDirectionDesc)
}

// Which repository, which issues, and which page.
type Request struct {
	// Account owner of the repository, case-insensitive.
	Owner string
	// Repository name without the `.git` extension, case-insensitive.
	Repo string
	// Issue state to include.
	State *RequestState
	// Comma-separated label names; every one must match.
	Labels *string
	// Sort key.
	Sort *RequestSort
	// Sort direction.
	Direction *RequestDirection
	// Only issues updated at or after this instant.
	Since *truewire.TimestampIso
	// Results per page, at most 100.
	PerPage *int64
	// Page number of the results to fetch, starting at 1.
	Page *int64
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Request) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("owner", &r.Owner),
		truewire.Required("repo", &r.Repo),
		truewire.OptionalField("state", &r.State),
		truewire.OptionalField("labels", &r.Labels),
		truewire.OptionalField("sort", &r.Sort),
		truewire.OptionalField("direction", &r.Direction),
		truewire.OptionalField("since", &r.Since),
		truewire.OptionalField("per_page", &r.PerPage),
		truewire.OptionalField("page", &r.Page),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Request) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("owner", &r.Owner),
		truewire.Required("repo", &r.Repo),
		truewire.OptionalField("state", &r.State),
		truewire.OptionalField("labels", &r.Labels),
		truewire.OptionalField("sort", &r.Sort),
		truewire.OptionalField("direction", &r.Direction),
		truewire.OptionalField("since", &r.Since),
		truewire.OptionalField("per_page", &r.PerPage),
		truewire.OptionalField("page", &r.Page),
	)
}

type IssueState string

const IssueStateOpen IssueState = "open"
const IssueStateClosed IssueState = "closed"

// UnmarshalJSON accepts only the literal's values.
func (v *IssueState) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, IssueStateOpen, IssueStateClosed)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v IssueState) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, IssueStateOpen, IssueStateClosed)
}

type IssueStateReason string

const IssueStateReasonCompleted IssueStateReason = "completed"
const IssueStateReasonNotPlanned IssueStateReason = "not_planned"
const IssueStateReasonReopened IssueStateReason = "reopened"
const IssueStateReasonDuplicate IssueStateReason = "duplicate"

// UnmarshalJSON accepts only the literal's values.
func (v *IssueStateReason) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, IssueStateReasonCompleted, IssueStateReasonNotPlanned, IssueStateReasonReopened, IssueStateReasonDuplicate)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v IssueStateReason) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, IssueStateReasonCompleted, IssueStateReasonNotPlanned, IssueStateReasonReopened, IssueStateReasonDuplicate)
}

type IssueAuthorAssociation string

const IssueAuthorAssociationCollaborator IssueAuthorAssociation = "COLLABORATOR"
const IssueAuthorAssociationContributor IssueAuthorAssociation = "CONTRIBUTOR"
const IssueAuthorAssociationFirstTimer IssueAuthorAssociation = "FIRST_TIMER"
const IssueAuthorAssociationFirstTimeContributor IssueAuthorAssociation = "FIRST_TIME_CONTRIBUTOR"
const IssueAuthorAssociationMannequin IssueAuthorAssociation = "MANNEQUIN"
const IssueAuthorAssociationMember IssueAuthorAssociation = "MEMBER"
const IssueAuthorAssociationNone IssueAuthorAssociation = "NONE"
const IssueAuthorAssociationOwner IssueAuthorAssociation = "OWNER"

// UnmarshalJSON accepts only the literal's values.
func (v *IssueAuthorAssociation) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, IssueAuthorAssociationCollaborator, IssueAuthorAssociationContributor, IssueAuthorAssociationFirstTimer, IssueAuthorAssociationFirstTimeContributor, IssueAuthorAssociationMannequin, IssueAuthorAssociationMember, IssueAuthorAssociationNone, IssueAuthorAssociationOwner)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v IssueAuthorAssociation) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, IssueAuthorAssociationCollaborator, IssueAuthorAssociationContributor, IssueAuthorAssociationFirstTimer, IssueAuthorAssociationFirstTimeContributor, IssueAuthorAssociationMannequin, IssueAuthorAssociationMember, IssueAuthorAssociationNone, IssueAuthorAssociationOwner)
}

// An issue, or a pull request seen as one.
type Issue struct {
	// Issue id.
	ID int64
	// GraphQL node id.
	NodeID *string
	// Issue number within the repository.
	Number int64
	// Title.
	Title string
	// Open or closed.
	State IssueState
	// Why the issue is in its state, when GitHub recorded one.
	StateReason truewire.Optional[*IssueStateReason]
	// Whether the conversation is locked.
	Locked bool
	// Author, when the account still exists.
	User truewire.Optional[*types.SimpleUser]
	// Labels on the issue.
	Labels []types.Label
	// Number of comments.
	Comments int64
	// When the issue was opened.
	CreatedAt truewire.TimestampIso
	// When the issue last changed.
	UpdatedAt truewire.TimestampIso
	// When the issue was closed; null while open.
	ClosedAt truewire.Optional[*truewire.TimestampIso]
	// Body in Markdown, when set.
	Body truewire.Optional[*string]
	// Web page of the issue.
	HTMLURL string
	// How the author relates to the repository.
	AuthorAssociation *IssueAuthorAssociation
	PullRequest       *IssuePullRequest
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Issue) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("id", &r.ID),
		truewire.OptionalField("node_id", &r.NodeID),
		truewire.Required("number", &r.Number),
		truewire.Required("title", &r.Title),
		truewire.Required("state", &r.State),
		truewire.OptionalNullable("state_reason", &r.StateReason),
		truewire.Required("locked", &r.Locked),
		truewire.OptionalNullable("user", &r.User),
		truewire.Required("labels", &r.Labels),
		truewire.Required("comments", &r.Comments),
		truewire.Required("created_at", &r.CreatedAt),
		truewire.Required("updated_at", &r.UpdatedAt),
		truewire.OptionalNullable("closed_at", &r.ClosedAt),
		truewire.OptionalNullable("body", &r.Body),
		truewire.Required("html_url", &r.HTMLURL),
		truewire.OptionalField("author_association", &r.AuthorAssociation),
		truewire.OptionalField("pull_request", &r.PullRequest),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Issue) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("id", &r.ID),
		truewire.OptionalField("node_id", &r.NodeID),
		truewire.Required("number", &r.Number),
		truewire.Required("title", &r.Title),
		truewire.Required("state", &r.State),
		truewire.OptionalNullable("state_reason", &r.StateReason),
		truewire.Required("locked", &r.Locked),
		truewire.OptionalNullable("user", &r.User),
		truewire.Required("labels", &r.Labels),
		truewire.Required("comments", &r.Comments),
		truewire.Required("created_at", &r.CreatedAt),
		truewire.Required("updated_at", &r.UpdatedAt),
		truewire.OptionalNullable("closed_at", &r.ClosedAt),
		truewire.OptionalNullable("body", &r.Body),
		truewire.Required("html_url", &r.HTMLURL),
		truewire.OptionalField("author_association", &r.AuthorAssociation),
		truewire.OptionalField("pull_request", &r.PullRequest),
	)
}

type Issues = []Issue

// PagedRequest is Request without `page`, which ListPaged advances.
type PagedRequest struct {
	// Account owner of the repository, case-insensitive.
	Owner string
	// Repository name without the `.git` extension, case-insensitive.
	Repo string
	// Issue state to include.
	State *RequestState
	// Comma-separated label names; every one must match.
	Labels *string
	// Sort key.
	Sort *RequestSort
	// Sort direction.
	Direction *RequestDirection
	// Only issues updated at or after this instant.
	Since *truewire.TimestampIso
	// Results per page, at most 100.
	PerPage *int64
	// Extra holds keys the spec does not document, sent as they are.
	Extra map[string]json.RawMessage
}

// at is the Request for one page of the walk.
func (p PagedRequest) at(pageValue *int64) Request {
	return Request{Owner: p.Owner, Repo: p.Repo, State: p.State, Labels: p.Labels, Sort: p.Sort, Direction: p.Direction, Since: p.Since, PerPage: p.PerPage, Page: pageValue, Extra: p.Extra}
}

// Endpoint is the `issues.list` endpoint.
//
// List issues in a repository. GitHub returns pull requests here too; a row with `pull_request` set is one.
type Endpoint struct {
	core truewire.HttpEndpoint
}

// New returns the endpoint over core.
func New(core truewire.HttpEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// List issues in a repository. GitHub returns pull requests here too; a row with `pull_request` set is one.
//
// ListPaged is the paged variant of List: All for every row, or range over Rows/Pages one page at a time.
//
// See https://docs.github.com/en/rest/issues/issues#list-repository-issues.
func (e *Endpoint) ListPaged(request PagedRequest, opts ...truewire.CallOption) *truewire.PaginatedResponse[Issue, int64] {
	size := 30
	if request.PerPage != nil {
		size = min(int(*request.PerPage), 100)
	}
	next := func(ctx context.Context, state int64) ([]Issue, *int64, error) {
		response, err := e.List(ctx, request.at(&state), opts...)
		if err != nil {
			return nil, nil, err
		}
		rows := response
		if truewire.Exhausted(len(rows), size) {
			return rows, nil, nil
		}
		following := state + 1
		return rows, &following, nil
	}
	return truewire.NewPaginatedResponse(int64(1), next)
}

// List issues in a repository. GitHub returns pull requests here too; a row with `pull_request` set is one.
//
// See https://docs.github.com/en/rest/issues/issues#list-repository-issues.
func (e *Endpoint) List(ctx context.Context, request Request, opts ...truewire.CallOption) (Issues, error) {
	return truewire.DecodeResult[Issues](e.ListRaw(ctx, request, opts...))
}

// ListRaw is List without validation: the wire body as it came.
func (e *Endpoint) ListRaw(ctx context.Context, request Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	body, err := truewire.Dump(request)
	if err != nil {
		return nil, err
	}
	return e.core.Request(ctx, truewire.HttpCall{Method: "GET", Path: "/repos/{owner}/{repo}/issues", Request: body, Meta: meta.DefaultMeta{Public: truewire.Ptr(true)}, Options: truewire.Options(opts...)})
}
