// Code generated by truewire. DO NOT EDIT.

// Package removeexport is the `spot.account.remove_export` endpoint.
package removeexport

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/kraken/src/kraken/meta"
)

// Outcome of the delete/cancel operation. Exactly one of `delete`/`cancel` is present, matching the requested `type`.
type RemoveExportResult struct {
	// Whether deletion succeeded. Present when `type: "delete"` was requested.
	Delete *bool
	// Whether cancellation succeeded. Present when `type: "cancel"` was requested.
	Cancel *bool
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *RemoveExportResult) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalField("delete", &r.Delete),
		truewire.OptionalField("cancel", &r.Cancel),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r RemoveExportResult) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalField("delete", &r.Delete),
		truewire.OptionalField("cancel", &r.Cancel),
	)
}

type RequestType string

const RequestTypeCancel RequestType = "cancel"
const RequestTypeDelete RequestType = "delete"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestType) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestTypeCancel, RequestTypeDelete)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestType) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestTypeCancel, RequestTypeDelete)
}

type Request struct {
	// ID of the report to delete or cancel.
	ID string
	// `delete` can only be used for reports that have already been processed. Use `cancel` for queued or processing reports.
	Type RequestType
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Request) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("id", &r.ID),
		truewire.Required("type", &r.Type),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Request) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("id", &r.ID),
		truewire.Required("type", &r.Type),
	)
}

// Endpoint is the `spot.account.remove_export` endpoint.
//
// Delete an exported trades/ledgers report. `delete` can only be used for reports that have already been processed; use `cancel` for reports that are still queued or processing.
//
// **API Key Permissions Required:** `Data - Export data`
type Endpoint struct {
	core truewire.HttpEndpoint
}

// New returns the endpoint over core.
func New(core truewire.HttpEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// Delete an exported trades/ledgers report. `delete` can only be used for reports that have already been processed; use `cancel` for reports that are still queued or processing.
//
// **API Key Permissions Required:** `Data - Export data`
//
// See https://docs.kraken.com/api-reference/account-data/delete-export-report.
func (e *Endpoint) RemoveExport(ctx context.Context, request Request, opts ...truewire.CallOption) (RemoveExportResult, error) {
	return truewire.DecodeResult[RemoveExportResult](e.RemoveExportRaw(ctx, request, opts...))
}

// RemoveExportRaw is RemoveExport without validation: the wire body as it came.
func (e *Endpoint) RemoveExportRaw(ctx context.Context, request Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	body, err := truewire.Dump(request)
	if err != nil {
		return nil, err
	}
	return e.core.Request(ctx, truewire.HttpCall{Method: "POST", Path: "/0/private/RemoveExport", Request: body, Meta: meta.SpotMeta{Signed: truewire.Ptr(true)}, Options: truewire.Options(opts...)})
}
