// Generated by truewire — do not edit by hand.
import type { HttpEndpoint } from '@truewire/core'
import { Issues } from './issues/index.js'
import type { DefaultMeta } from './meta.js'
import { Repos } from './repos/index.js'

/**
 * GitHub REST API, repository-scoped endpoints: repositories, commits, tags, releases and issues. Every recorded example is a live capture from api.github.com against truewire-dev/truewire.
 *
 * @see https://docs.github.com/en/rest
 */
export class GitHub {
  /** Issues and, through the same list, pull requests. */
  readonly issues: Issues
  /** Repositories: metadata, commits, tags and releases. */
  readonly repos: Repos

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.issues = new Issues(core)
    this.repos = new Repos(core)
  }
}
