// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'
import { ConditionalCloseOrder } from '../../types/index.js'

/** Human-readable description of the order (and its conditional close, if one was attached). */
export interface OrderDescription {
  /** Human-readable order description. */
  order?: string
  /** Human-readable conditional close order description, if one was attached. */
  close?: string
}

export const OrderDescription: Codec<OrderDescription> = t.object({
  order: t.optional(t.string),
  close: t.optional(t.string),
})

/** An iceberg order: a limit order that shows only `displayvol` of its quantity in the book while the rest remains hidden. */
export interface AddOrderIceberg {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'iceberg'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
  /** Limit price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference. */
  price: string
  /** Quantity to show in the book while the rest of the order quantity (`volume`) remains hidden. Minimum value is 1/15 of `volume`. */
  displayvol: string
}

export const AddOrderIceberg: Codec<AddOrderIceberg> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('iceberg'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
  price: t.string,
  displayvol: t.string,
})

/** A limit order: rests in the book at `price` or better. */
export interface AddOrderLimit {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'limit'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
  /** Limit price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference. */
  price: string
}

export const AddOrderLimit: Codec<AddOrderLimit> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('limit'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
  price: t.string,
})

/** A market order: executes immediately at the best available price. */
export interface AddOrderMarket {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'market'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
}

export const AddOrderMarket: Codec<AddOrderMarket> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('market'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
})

/** Settles an open leveraged position at the current market price. */
export interface AddOrderSettlePosition {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'settle-position'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
}

export const AddOrderSettlePosition: Codec<AddOrderSettlePosition> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('settle-position'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
})

/** A stop-loss order: becomes a market order once `price` (the trigger) is reached in an unfavourable direction. */
export interface AddOrderStopLoss {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'stop-loss'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
  /** Trigger price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference. */
  price: string
  /** Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference. */
  trigger?: 'index' | 'last'
}

export const AddOrderStopLoss: Codec<AddOrderStopLoss> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('stop-loss'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
  price: t.string,
  trigger: t.optional(t.literal('index', 'last')),
})

/** A stop-loss-limit order: becomes a limit order at `price2` once `price` (the trigger) is reached in an unfavourable direction. */
export interface AddOrderStopLossLimit {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'stop-loss-limit'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
  /** Trigger price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference. */
  price: string
  /** Limit price for the order once triggered. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference. */
  price2: string
  /** Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference. */
  trigger?: 'index' | 'last'
}

export const AddOrderStopLossLimit: Codec<AddOrderStopLossLimit> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('stop-loss-limit'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
  price: t.string,
  price2: t.string,
  trigger: t.optional(t.literal('index', 'last')),
})

/** A take-profit order: becomes a market order once `price` (the trigger) is reached in a favourable direction. */
export interface AddOrderTakeProfit {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'take-profit'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
  /** Trigger price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference. */
  price: string
  /** Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference. */
  trigger?: 'index' | 'last'
}

export const AddOrderTakeProfit: Codec<AddOrderTakeProfit> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('take-profit'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
  price: t.string,
  trigger: t.optional(t.literal('index', 'last')),
})

/** A take-profit-limit order: becomes a limit order at `price2` once `price` (the trigger) is reached in a favourable direction. */
export interface AddOrderTakeProfitLimit {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'take-profit-limit'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
  /** Trigger price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference. */
  price: string
  /** Limit price for the order once triggered. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference. */
  price2: string
  /** Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference. */
  trigger?: 'index' | 'last'
}

export const AddOrderTakeProfitLimit: Codec<AddOrderTakeProfitLimit> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('take-profit-limit'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
  price: t.string,
  price2: t.string,
  trigger: t.optional(t.literal('index', 'last')),
})

/** A trailing-stop order: triggers as a market order once the price reverts by `price` from its peak/trough since order entry. */
export interface AddOrderTrailingStop {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'trailing-stop'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
  /** Relative trailing offset from the last traded price. Must use the `+` prefix (direction is inferred from the order's buy/sell side), and also accepts the `%` suffix. */
  price: string
  /** Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference. */
  trigger?: 'index' | 'last'
}

export const AddOrderTrailingStop: Codec<AddOrderTrailingStop> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('trailing-stop'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
  price: t.string,
  trigger: t.optional(t.literal('index', 'last')),
})

/** A trailing-stop-limit order: triggers a limit order at an offset (`price2`) from the trigger price once the price reverts by `price` from its peak/trough since order entry. */
export interface AddOrderTrailingStopLimit {
  /** Asset pair `id` or `altname`, e.g. `XBTUSD`. */
  pair: string
  /** Order direction. */
  type: 'buy' | 'sell'
  /** The execution model of the order. */
  ordertype: 'trailing-stop-limit'
  /** Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity. */
  volume: string
  /** An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`. */
  userref?: number
  /** An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`. */
  cl_ord_id?: string
  /** Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
  /** Amount of leverage desired. Defaults to none. */
  leverage?: string
  /** If true, the order will only reduce a currently open position rather than increase it or open a new one. */
  reduce_only?: boolean
  /** Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both. */
  stptype?: 'cancel-newest' | 'cancel-oldest' | 'cancel-both'
  /** Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders). */
  oflags?: string
  /** How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely. */
  timeinforce?: 'GTC' | 'IOC' | 'GTD' | 'FOK'
  /** Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`). */
  starttm?: string
  /** Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`). */
  expiretm?: string
  /** Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it. */
  close?: ConditionalCloseOrder | null
  /** RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s. */
  deadline?: TimestampIso
  /** If true, the order is validated only and never reaches the matching engine (no `txid` is returned). */
  validate?: boolean
  /** Broker IIBAN (partner's Kraken IIBAN). */
  broker?: string | null
  /** Relative trailing offset from the last traded price. Must use the `+` prefix (direction is inferred from the order's buy/sell side), and also accepts the `%` suffix. */
  price: string
  /** Relative offset (`+`/`-` prefix, optionally `%` suffix) from the trigger price to the limit price -- `+0` sets the limit price equal to the trigger price. */
  price2: string
  /** Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference. */
  trigger?: 'index' | 'last'
}

export const AddOrderTrailingStopLimit: Codec<AddOrderTrailingStopLimit> = t.object({
  pair: t.string,
  type: t.literal('buy', 'sell'),
  ordertype: t.literal('trailing-stop-limit'),
  volume: t.string,
  userref: t.optional(t.integer),
  cl_ord_id: t.optional(t.string),
  asset_class: t.optional(t.literal('tokenized_asset')),
  leverage: t.optional(t.string),
  reduce_only: t.optional(t.boolean),
  stptype: t.optional(t.literal('cancel-newest', 'cancel-oldest', 'cancel-both')),
  oflags: t.optional(t.string),
  timeinforce: t.optional(t.literal('GTC', 'IOC', 'GTD', 'FOK')),
  starttm: t.optional(t.string),
  expiretm: t.optional(t.string),
  close: t.optional(t.nullable(ConditionalCloseOrder)),
  deadline: t.optional(t.dateTime),
  validate: t.optional(t.boolean),
  broker: t.optional(t.nullable(t.string)),
  price: t.string,
  price2: t.string,
  trigger: t.optional(t.literal('index', 'last')),
})

/** Result of placing a new order. */
export interface OrderAdded {
  descr?: OrderDescription
  /** Transaction ID(s) for the order -- present only once the order actually reaches the matching engine, i.e. absent when `validate` was set. */
  txid?: string[]
}

export const OrderAdded: Codec<OrderAdded> = t.object({
  descr: t.optional(OrderDescription),
  txid: t.optional(t.array(t.string)),
})

export type Request = AddOrderMarket | AddOrderLimit | AddOrderIceberg | AddOrderStopLoss | AddOrderTakeProfit | AddOrderStopLossLimit | AddOrderTakeProfitLimit | AddOrderTrailingStop | AddOrderTrailingStopLimit | AddOrderSettlePosition

export const Request: Codec<Request> = t.union(AddOrderMarket, AddOrderLimit, AddOrderIceberg, AddOrderStopLoss, AddOrderTakeProfit, AddOrderStopLossLimit, AddOrderTakeProfitLimit, AddOrderTrailingStop, AddOrderTrailingStopLimit, AddOrderSettlePosition)

/**
 * Place a new order. See `AssetPairs` for tradable pairs, their price/quantity precisions, order minimums, and available leverage.
 *
 * **API Key Permissions Required:** `Orders and trades - Create & modify orders`
 */
export class AddOrder {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  addOrder(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Place a new order. See `AssetPairs` for tradable pairs, their price/quantity precisions, order minimums, and available leverage.
   *
   * **API Key Permissions Required:** `Orders and trades - Create & modify orders`
   *
   * @see https://docs.kraken.com/api-reference/trading/add-order
   */
  addOrder(request: Request, options?: CallOptions): Promise<OrderAdded>
  async addOrder(request: Request, options?: CallOptions): Promise<OrderAdded> {
    return this.core.request({
      method: 'POST',
      path: '/0/private/AddOrder',
      request,
      requestCodec: Request,
      responseCodec: OrderAdded,
      meta: { signed: true },
      ...options,
    })
  }
}
