//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso,
};

use crate::meta::SpotMeta;
use crate::types::ConditionalCloseOrder;

/// Human-readable description of the order (and its conditional close, if one was attached).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderDescription {
    /// Human-readable order description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order: Option<String>,
    /// Human-readable conditional close order description, if one was attached.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub close: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderIcebergType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderIcebergOrdertype {
    #[serde(rename = "iceberg")]
    Iceberg,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderIcebergAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderIcebergStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderIcebergTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

/// An iceberg order: a limit order that shows only `displayvol` of its quantity in the book while the rest remains hidden.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderIceberg {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderIcebergType,
    /// The execution model of the order.
    pub ordertype: AddOrderIcebergOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderIcebergAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderIcebergStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderIcebergTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Limit price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference.
    pub price: String,
    /// Quantity to show in the book while the rest of the order quantity (`volume`) remains hidden. Minimum value is 1/15 of `volume`.
    pub displayvol: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderLimitType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderLimitOrdertype {
    #[serde(rename = "limit")]
    Limit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderLimitAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderLimitStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderLimitTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

/// A limit order: rests in the book at `price` or better.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderLimit {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderLimitType,
    /// The execution model of the order.
    pub ordertype: AddOrderLimitOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderLimitAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderLimitStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderLimitTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Limit price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference.
    pub price: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderMarketType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderMarketOrdertype {
    #[serde(rename = "market")]
    Market,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderMarketAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderMarketStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderMarketTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

/// A market order: executes immediately at the best available price.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderMarket {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderMarketType,
    /// The execution model of the order.
    pub ordertype: AddOrderMarketOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderMarketAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderMarketStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderMarketTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderSettlePositionType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderSettlePositionOrdertype {
    #[serde(rename = "settle-position")]
    SettlePosition,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderSettlePositionAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderSettlePositionStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderSettlePositionTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

/// Settles an open leveraged position at the current market price.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderSettlePosition {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderSettlePositionType,
    /// The execution model of the order.
    pub ordertype: AddOrderSettlePositionOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderSettlePositionAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderSettlePositionStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderSettlePositionTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossOrdertype {
    #[serde(rename = "stop-loss")]
    StopLoss,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossTrigger {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "last")]
    Last,
}

/// A stop-loss order: becomes a market order once `price` (the trigger) is reached in an unfavourable direction.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderStopLoss {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderStopLossType,
    /// The execution model of the order.
    pub ordertype: AddOrderStopLossOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderStopLossAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderStopLossStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderStopLossTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Trigger price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference.
    pub price: String,
    /// Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<AddOrderStopLossTrigger>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossLimitType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossLimitOrdertype {
    #[serde(rename = "stop-loss-limit")]
    StopLossLimit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossLimitAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossLimitStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossLimitTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderStopLossLimitTrigger {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "last")]
    Last,
}

/// A stop-loss-limit order: becomes a limit order at `price2` once `price` (the trigger) is reached in an unfavourable direction.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderStopLossLimit {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderStopLossLimitType,
    /// The execution model of the order.
    pub ordertype: AddOrderStopLossLimitOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderStopLossLimitAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderStopLossLimitStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderStopLossLimitTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Trigger price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference.
    pub price: String,
    /// Limit price for the order once triggered. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference.
    pub price2: String,
    /// Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<AddOrderStopLossLimitTrigger>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitOrdertype {
    #[serde(rename = "take-profit")]
    TakeProfit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitTrigger {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "last")]
    Last,
}

/// A take-profit order: becomes a market order once `price` (the trigger) is reached in a favourable direction.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderTakeProfit {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderTakeProfitType,
    /// The execution model of the order.
    pub ordertype: AddOrderTakeProfitOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderTakeProfitAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderTakeProfitStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderTakeProfitTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Trigger price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference.
    pub price: String,
    /// Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<AddOrderTakeProfitTrigger>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitLimitType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitLimitOrdertype {
    #[serde(rename = "take-profit-limit")]
    TakeProfitLimit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitLimitAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitLimitStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitLimitTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTakeProfitLimitTrigger {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "last")]
    Last,
}

/// A take-profit-limit order: becomes a limit order at `price2` once `price` (the trigger) is reached in a favourable direction.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderTakeProfitLimit {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderTakeProfitLimitType,
    /// The execution model of the order.
    pub ordertype: AddOrderTakeProfitLimitOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderTakeProfitLimitAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderTakeProfitLimitStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderTakeProfitLimitTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Trigger price for the order. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference.
    pub price: String,
    /// Limit price for the order once triggered. May be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction), and suffixed with `%` for a relative percentage instead of an absolute difference.
    pub price2: String,
    /// Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<AddOrderTakeProfitLimitTrigger>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopOrdertype {
    #[serde(rename = "trailing-stop")]
    TrailingStop,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopTrigger {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "last")]
    Last,
}

/// A trailing-stop order: triggers as a market order once the price reverts by `price` from its peak/trough since order entry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderTrailingStop {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderTrailingStopType,
    /// The execution model of the order.
    pub ordertype: AddOrderTrailingStopOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderTrailingStopAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderTrailingStopStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderTrailingStopTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Relative trailing offset from the last traded price. Must use the `+` prefix (direction is inferred from the order's buy/sell side), and also accepts the `%` suffix.
    pub price: String,
    /// Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<AddOrderTrailingStopTrigger>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopLimitType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopLimitOrdertype {
    #[serde(rename = "trailing-stop-limit")]
    TrailingStopLimit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopLimitAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopLimitStptype {
    #[serde(rename = "cancel-newest")]
    CancelNewest,
    #[serde(rename = "cancel-oldest")]
    CancelOldest,
    #[serde(rename = "cancel-both")]
    CancelBoth,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopLimitTimeinforce {
    #[serde(rename = "GTC")]
    Gtc,
    #[serde(rename = "IOC")]
    Ioc,
    #[serde(rename = "GTD")]
    Gtd,
    #[serde(rename = "FOK")]
    Fok,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AddOrderTrailingStopLimitTrigger {
    #[serde(rename = "index")]
    Index,
    #[serde(rename = "last")]
    Last,
}

/// A trailing-stop-limit order: triggers a limit order at an offset (`price2`) from the trigger price once the price reverts by `price` from its peak/trough since order entry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddOrderTrailingStopLimit {
    /// Asset pair `id` or `altname`, e.g. `XBTUSD`.
    pub pair: String,
    /// Order direction.
    #[serde(rename = "type")]
    pub type_: AddOrderTrailingStopLimitType,
    /// The execution model of the order.
    pub ordertype: AddOrderTrailingStopLimitOrdertype,
    /// Order quantity in terms of the base asset. May be `0` for closing margin orders to automatically fill the requisite quantity.
    pub volume: String,
    /// An optional non-unique numeric identifier the client can associate with any number of orders (e.g. for grouping by pair/side/strategy), letting cancel/query calls target the group by `userref` instead of individual `txid`s. Uniqueness is not enforced. Mutually exclusive with `cl_ord_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// An alphanumeric client order identifier which uniquely identifies this order for the client. One of: a long UUID (`6d1b345e-2821-40e2-ad83-4ecb18a06876`), a short UUID with no dashes, or free-form ASCII text up to 18 characters. Mutually exclusive with `userref`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<AddOrderTrailingStopLimitAssetClass>,
    /// Amount of leverage desired. Defaults to none.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub leverage: Option<String>,
    /// If true, the order will only reduce a currently open position rather than increase it or open a new one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
    /// Self Trade Prevention (STP) mode, defining which order(s) are expired to prevent a self-match: `cancel-newest` cancels the arriving order, `cancel-oldest` cancels the resting order, `cancel-both` cancels both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stptype: Option<AddOrderTrailingStopLimitStptype>,
    /// Comma-delimited list of order flags: `post` (post-only, available when `ordertype = limit`), `fcib` (prefer fee in base currency, default when selling), `fciq` (prefer fee in quote currency, default when buying, mutually exclusive with `fcib`), `nompp` (deprecated -- disabling Market Price Protection is no longer supported; accepted but ignored if supplied), `viqc` (order volume expressed in quote currency; buy market orders only, unavailable on margin orders).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// How long the order should remain in the book before being cancelled. `GTC` (good-'til-cancelled, default): rests until filled or cancelled. `IOC` (immediate-or-cancel): fills what it can immediately, cancels the remainder rather than resting. `GTD` (good-'til-date): must be paired with `expiretm`. `FOK` (fill-or-kill): fills the entire order immediately or cancels it entirely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeinforce: Option<AddOrderTrailingStopLimitTimeinforce>,
    /// Scheduled start time: `0` for now (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starttm: Option<String>,
    /// Expiry time for `GTD` orders, up to one month in the future: `0` for no expiration (default), an absolute unix timestamp, or `+<n>` for `<n>` seconds from now, minimum 5 (URL-encode the `+` as `%2b`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiretm: Option<String>,
    /// Conditional close order, attached to this order. Triggered by execution of the primary order in the same quantity and opposite direction, but once triggered becomes an independent order that may reduce or increase net position, not just close it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub close: Option<Option<ConditionalCloseOrder>>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this order if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the order is validated only and never reaches the matching engine (no `txid` is returned).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Broker IIBAN (partner's Kraken IIBAN).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub broker: Option<Option<String>>,
    /// Relative trailing offset from the last traded price. Must use the `+` prefix (direction is inferred from the order's buy/sell side), and also accepts the `%` suffix.
    pub price: String,
    /// Relative offset (`+`/`-` prefix, optionally `%` suffix) from the trigger price to the limit price -- `+0` sets the limit price equal to the trigger price.
    pub price2: String,
    /// Price signal used to trigger this order (and any attached conditional close order). During connectivity issues with external index feeds, the last trade price is used as a fallback reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<AddOrderTrailingStopLimitTrigger>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Result of placing a new order.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderAdded {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descr: Option<OrderDescription>,
    /// Transaction ID(s) for the order -- present only once the order actually reaches the matching engine, i.e. absent when `validate` was set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub txid: Option<Vec<String>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Request {
    AddOrderMarket(AddOrderMarket),
    AddOrderLimit(AddOrderLimit),
    AddOrderIceberg(AddOrderIceberg),
    AddOrderStopLoss(AddOrderStopLoss),
    AddOrderTakeProfit(AddOrderTakeProfit),
    AddOrderStopLossLimit(AddOrderStopLossLimit),
    AddOrderTakeProfitLimit(AddOrderTakeProfitLimit),
    AddOrderTrailingStop(AddOrderTrailingStop),
    AddOrderTrailingStopLimit(AddOrderTrailingStopLimit),
    AddOrderSettlePosition(AddOrderSettlePosition),
}

/// Place a new order. See `AssetPairs` for tradable pairs, their price/quantity precisions, order minimums, and available leverage.
///
/// **API Key Permissions Required:** `Orders and trades - Create & modify orders`
#[derive(Clone)]
pub struct AddOrder {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl AddOrder {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Place a new order. See `AssetPairs` for tradable pairs, their price/quantity precisions, order minimums, and available leverage.
    ///
    /// **API Key Permissions Required:** `Orders and trades - Create & modify orders`
    ///
    /// See <https://docs.kraken.com/api-reference/trading/add-order>.
    pub async fn add_order(&self, request: Request, options: CallOptions) -> Result<OrderAdded> {
        let raw = self.add_order_raw(request, options).await?;
        decode(raw)
    }

    /// `add_order` without validation: the wire body as it came.
    pub async fn add_order_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/AddOrder",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
