//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::SpotMeta;

/// Result of a cancel request.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderCancelled {
    /// Number of orders cancelled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// If true, orders are pending cancellation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pending: Option<bool>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RequestTxid {
    String(String),
    Integer(i64),
}

/// Parameters identifying the order(s) to cancel.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Kraken order identifier (txid), or a user reference (userref) to cancel every order sharing it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub txid: Option<RequestTxid>,
    /// An alphanumeric client order identifier which uniquely identifies an open order for this client.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cl_ord_id: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Cancel a particular open order (or set of open orders sharing a `userref`) by `txid`, `userref` or `cl_ord_id`.
///
/// **API Key Permissions Required:** `Orders and trades - Create & modify orders` or `Orders and trades - Cancel & close orders`
#[derive(Clone)]
pub struct CancelOrder {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl CancelOrder {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Cancel a particular open order (or set of open orders sharing a `userref`) by `txid`, `userref` or `cl_ord_id`.
    ///
    /// **API Key Permissions Required:** `Orders and trades - Create & modify orders` or `Orders and trades - Cancel & close orders`
    ///
    /// See <https://docs.kraken.com/api-reference/trading/cancel-order>.
    pub async fn cancel_order(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<OrderCancelled> {
        let raw = self.cancel_order_raw(request, options).await?;
        decode(raw)
    }

    /// `cancel_order` without validation: the wire body as it came.
    pub async fn cancel_order_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/CancelOrder",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
