//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso,
};

use crate::meta::SpotMeta;

/// Human-readable description of the replacement order.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderDescription {
    /// Human-readable order description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RequestTxid {
    String(String),
    Integer(i64),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestAssetClass {
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

/// Parameters for cancel-replacing a live order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// An optional user-specified integer id associated with this edit request. Note: the parent order's `userref` is not retained on the new order after the edit.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub userref: Option<i64>,
    /// The original order's transaction ID (txid), or its user reference (userref) if unique to a single order -- if the userref matches multiple orders, the edit is denied with an error.
    pub txid: RequestTxid,
    /// Order quantity in terms of the base asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub volume: Option<String>,
    /// For `iceberg` orders only, the quantity to show in the book while the rest of the order quantity remains hidden. Minimum value is 1/15 of `volume`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub displayvol: Option<String>,
    /// Asset pair `id` or `altname`.
    pub pair: String,
    /// Required on requests for non-crypto pairs, e.g. `tokenized_asset` for xstocks.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<RequestAssetClass>,
    /// Limit price for `limit`/`iceberg` orders, or trigger price for `stop-loss`, `stop-loss-limit`, `take-profit`, `take-profit-limit`, `trailing-stop` and `trailing-stop-limit` orders. Either `price` or `price2` may be prefixed with `+`/`-` (offset from last traded price) or `#` (add or subtract depending on order direction/type), and suffixed with `%` for a relative percentage instead of an absolute difference. Trailing stops must use the `+` prefix, and also accept the `%` suffix.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    /// Secondary price for `stop-loss-limit`, `take-profit-limit` and `trailing-stop-limit` orders. For trailing stops this is a relative offset (`+`/`-` prefix, optionally `%` suffix) from the trigger price to the limit price -- `+0` sets the limit price equal to the trigger price.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price2: Option<String>,
    /// Comma-delimited list of order flags. Only `post` (post-only, available when `ordertype = limit`) can be changed on edit -- every other flag from the parent order is retained, and `post` itself must be explicitly re-supplied on the edit request or it is dropped.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// RFC3339 timestamp (e.g. `2021-04-01T00:18:45Z`) after which the matching engine should reject this edit if it is still queued due to latency, minimum now()+2s, maximum now()+60s.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<TimestampIso>,
    /// If true, the client receives a pending-replace acknowledgement before the order is fully replaced.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancel_response: Option<bool>,
    /// If true, the edit is validated only and never reaches the matching engine.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validate: Option<bool>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Result of a cancel-replace edit.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderEdited {
    /// Outcome of the edit request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// New transaction ID, present if the order was successfully replaced.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    /// The original order's transaction ID.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub originaltxid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub descr: Option<OrderDescription>,
    /// Updated order volume.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub volume: Option<String>,
    /// Updated order price.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    /// Updated order secondary price.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price2: Option<String>,
    /// Number of orders cancelled by this edit -- either 0 or 1.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub orders_cancelled: Option<i64>,
    /// The `userref` passed with this edit request, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub newuserref: Option<String>,
    /// The original order's `userref`, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub olduserref: Option<String>,
    /// Error message, present if the edit was unsuccessful.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Legacy cancel-replace: edits the parameters of a live order by cancelling it and creating a new order with the adjusted parameters, returning a new `txid`. Superseded by `AmendOrder`, which edits in place and resolves this endpoint's caveats with better performance. Caveats: triggered stop-loss/take-profit orders are not supported; orders with a conditional close attached are not supported; an edit reducing volume below the already-executed volume is rejected; `cl_ord_id` is not supported; executions stay associated with the original order rather than the replacement; queue position is not maintained.
///
/// **API Key Permissions Required:** `Orders and trades - Create & modify orders` and `Orders and trades - Cancel & close orders`
#[derive(Clone)]
pub struct EditOrder {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl EditOrder {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Legacy cancel-replace: edits the parameters of a live order by cancelling it and creating a new order with the adjusted parameters, returning a new `txid`. Superseded by `AmendOrder`, which edits in place and resolves this endpoint's caveats with better performance. Caveats: triggered stop-loss/take-profit orders are not supported; orders with a conditional close attached are not supported; an edit reducing volume below the already-executed volume is rejected; `cl_ord_id` is not supported; executions stay associated with the original order rather than the replacement; queue position is not maintained.
    ///
    /// **API Key Permissions Required:** `Orders and trades - Create & modify orders` and `Orders and trades - Cancel & close orders`
    ///
    /// See <https://docs.kraken.com/api-reference/trading/edit-order>.
    pub async fn edit_order(&self, request: Request, options: CallOptions) -> Result<OrderEdited> {
        let raw = self.edit_order_raw(request, options).await?;
        decode(raw)
    }

    /// `edit_order` without validation: the wire body as it came.
    pub async fn edit_order_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/EditOrder",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
