//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::SpotMeta;

/// A short-lived token authenticating a private WebSocket connection.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct WebSocketsToken {
    /// WebSocket authentication token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// Seconds after which the token expires (~900), unless already consumed by a private WebSocket subscription.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires: Option<i64>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Request an authentication token for connecting to and authenticating with Kraken's private WebSocket API. The token should be used within 15 minutes of issuance; once a successful connection and private subscription has been made, it does not expire for the life of that connection.
///
/// **API Key Permissions Required:** `WebSocket interface - On`
#[derive(Clone)]
pub struct GetWebsocketsToken {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl GetWebsocketsToken {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Request an authentication token for connecting to and authenticating with Kraken's private WebSocket API. The token should be used within 15 minutes of issuance; once a successful connection and private subscription has been made, it does not expire for the life of that connection.
    ///
    /// **API Key Permissions Required:** `WebSocket interface - On`
    ///
    /// See <https://docs.kraken.com/api-reference/trading/get-websockets-token>.
    pub async fn get_websockets_token(&self, options: CallOptions) -> Result<WebSocketsToken> {
        let raw = self.get_websockets_token_raw(options).await?;
        decode(raw)
    }

    /// `get_websockets_token` without validation: the wire body as it came.
    pub async fn get_websockets_token_raw(
        &self,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/GetWebSocketsToken",
            request: None,
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
