// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type Decimal, type HttpEndpoint, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'

/** One method available for depositing a particular asset. */
export interface DepositMethod {
  /** Name of the deposit method, e.g. `Bitcoin`. */
  method: string
  /** Maximum net amount that can be deposited right now, or `false` if there is no limit. */
  limit: string | false
  /** Amount of fees that will be paid (flat fee). */
  fee: Decimal
  /** Percentage fee that will be paid (used instead of `fee` for some methods, e.g. Lightning). */
  'fee-percentage'?: Decimal
  /** Whether or not the method has an address setup fee. */
  'address-setup-fee'?: string
  /** Whether new addresses can be generated for this method. */
  'gen-address'?: boolean
  /** Minimum net amount that can be deposited right now. */
  minimum?: Decimal
}

export const DepositMethod: Codec<DepositMethod> = t.object({
  method: t.string,
  limit: t.union(t.string, t.literal(false)),
  fee: t.decimal,
  'fee-percentage': t.optional(t.decimal),
  'address-setup-fee': t.optional(t.string),
  'gen-address': t.optional(t.boolean),
  minimum: t.optional(t.decimal),
})

export interface Request {
  /** Asset being deposited, e.g. `XBT`. */
  asset: string
  /** Asset class (optional). Only `currency` is broadly used today; `tokenized_asset` covers xstocks-style tokenized equities. */
  aclass?: 'currency' | 'tokenized_asset'
  /** Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity; `base` displays in terms of SPV tokens. */
  rebase_multiplier?: 'rebased' | 'base' | null
}

export const Request: Codec<Request> = t.object({
  asset: t.string,
  aclass: t.optional(t.literal('currency', 'tokenized_asset')),
  rebase_multiplier: t.optional(t.nullable(t.literal('rebased', 'base'))),
})

export type Response = DepositMethod[]

export const Response: Codec<Response> = t.array(DepositMethod)

/** Retrieve methods available for depositing a particular asset. Requires the `Funds permissions - Query` and `Funds permissions - Deposit` API key permissions. */
export class DepositMethods {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  depositMethods(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Retrieve methods available for depositing a particular asset. Requires the `Funds permissions - Query` and `Funds permissions - Deposit` API key permissions.
   *
   * @see https://docs.kraken.com/api-reference/funding/get-deposit-methods
   */
  depositMethods(request: Request, options?: CallOptions): Promise<Response>
  async depositMethods(request: Request, options?: CallOptions): Promise<Response> {
    return this.core.request({
      method: 'POST',
      path: '/0/private/DepositMethods',
      request,
      requestCodec: Request,
      responseCodec: Response,
      meta: { signed: true },
      ...options,
    })
  }
}
