// Code generated by truewire. DO NOT EDIT.

// Package funding is the `spot.funding` router.
package funding

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/depositaddresses"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/depositmethods"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/depositstatus"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/wallettransfer"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/withdraw"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/withdrawaddresses"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/withdrawcancel"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/withdrawinfo"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/withdrawmethods"
	"truewire.dev/examples/kraken/src/kraken/spot/funding/withdrawstatus"
)

// Funding groups: Funding: deposit addresses/methods/status, withdrawal addresses/methods/status, withdrawal requests and cancellation, and internal wallet transfers.
//
// See https://docs.kraken.com/api-reference/funding.
type Funding struct {
	// The core this router was built from, for hand-written methods beside the generated ones.
	core              truewire.HttpEndpoint
	depositAddresses  *depositaddresses.Endpoint
	depositMethods    *depositmethods.Endpoint
	depositStatus     *depositstatus.Endpoint
	walletTransfer    *wallettransfer.Endpoint
	withdraw          *withdraw.Endpoint
	withdrawAddresses *withdrawaddresses.Endpoint
	withdrawCancel    *withdrawcancel.Endpoint
	withdrawInfo      *withdrawinfo.Endpoint
	withdrawMethods   *withdrawmethods.Endpoint
	withdrawStatus    *withdrawstatus.Endpoint
}

// New returns the router over core.
func New(core truewire.HttpEndpoint) *Funding {
	return &Funding{core: core, depositAddresses: depositaddresses.New(core), depositMethods: depositmethods.New(core), depositStatus: depositstatus.New(core), walletTransfer: wallettransfer.New(core), withdraw: withdraw.New(core), withdrawAddresses: withdrawaddresses.New(core), withdrawCancel: withdrawcancel.New(core), withdrawInfo: withdrawinfo.New(core), withdrawMethods: withdrawmethods.New(core), withdrawStatus: withdrawstatus.New(core)}
}

// Retrieve (or generate a new) deposit address for a particular asset and method. Requires the `Funds permissions - Query` API key permission.
//
// See https://docs.kraken.com/api-reference/funding/get-deposit-addresses.
func (r *Funding) DepositAddresses(ctx context.Context, request depositaddresses.Request, opts ...truewire.CallOption) (depositaddresses.Response, error) {
	return r.depositAddresses.DepositAddresses(ctx, request, opts...)
}

// DepositAddressesRaw is DepositAddresses without validation: the wire body as it came.
func (r *Funding) DepositAddressesRaw(ctx context.Context, request depositaddresses.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.depositAddresses.DepositAddressesRaw(ctx, request, opts...)
}

// Retrieve methods available for depositing a particular asset. Requires the `Funds permissions - Query` and `Funds permissions - Deposit` API key permissions.
//
// See https://docs.kraken.com/api-reference/funding/get-deposit-methods.
func (r *Funding) DepositMethods(ctx context.Context, request depositmethods.Request, opts ...truewire.CallOption) (depositmethods.Response, error) {
	return r.depositMethods.DepositMethods(ctx, request, opts...)
}

// DepositMethodsRaw is DepositMethods without validation: the wire body as it came.
func (r *Funding) DepositMethodsRaw(ctx context.Context, request depositmethods.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.depositMethods.DepositMethodsRaw(ctx, request, opts...)
}

// Retrieve information about recent deposits. Results are sorted by recency; use the `cursor` parameter to iterate through the list of deposits (page size equal to the value of `limit`) from newest to oldest. Requires the `Funds permissions - Query` API key permission.
//
// See https://docs.kraken.com/api-reference/funding/get-status-of-recent-deposits.
func (r *Funding) DepositStatus(ctx context.Context, request depositstatus.Request, opts ...truewire.CallOption) (depositstatus.Response, error) {
	return r.depositStatus.DepositStatus(ctx, request, opts...)
}

// DepositStatusRaw is DepositStatus without validation: the wire body as it came.
func (r *Funding) DepositStatusRaw(ctx context.Context, request depositstatus.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.depositStatus.DepositStatusRaw(ctx, request, opts...)
}

// Transfer from a Kraken Spot wallet to a Kraken Futures wallet. A transfer in the other direction must be requested via the Kraken Futures API withdrawal-to-Spot-wallet endpoint instead. Requires the `Funds permissions - Query` API key permission.
//
// See https://docs.kraken.com/api-reference/funding/request-wallet-transfer.
func (r *Funding) WalletTransfer(ctx context.Context, request wallettransfer.Request, opts ...truewire.CallOption) (wallettransfer.WalletTransferReceipt, error) {
	return r.walletTransfer.WalletTransfer(ctx, request, opts...)
}

// WalletTransferRaw is WalletTransfer without validation: the wire body as it came.
func (r *Funding) WalletTransferRaw(ctx context.Context, request wallettransfer.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.walletTransfer.WalletTransferRaw(ctx, request, opts...)
}

// Make a withdrawal request. Requires the `Funds permissions - Withdraw` API key permission.
//
// See https://docs.kraken.com/api-reference/funding/withdraw-funds.
func (r *Funding) Withdraw(ctx context.Context, request withdraw.Request, opts ...truewire.CallOption) (withdraw.WithdrawReceipt, error) {
	return r.withdraw.Withdraw(ctx, request, opts...)
}

// WithdrawRaw is Withdraw without validation: the wire body as it came.
func (r *Funding) WithdrawRaw(ctx context.Context, request withdraw.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.withdraw.WithdrawRaw(ctx, request, opts...)
}

// Retrieve a list of withdrawal addresses available for the user. Requires the `Funds permissions - Query` and `Funds permissions - Withdraw` API key permissions.
//
// See https://docs.kraken.com/api-reference/funding/get-withdrawal-addresses.
func (r *Funding) WithdrawAddresses(ctx context.Context, request withdrawaddresses.Request, opts ...truewire.CallOption) (withdrawaddresses.Response, error) {
	return r.withdrawAddresses.WithdrawAddresses(ctx, request, opts...)
}

// WithdrawAddressesRaw is WithdrawAddresses without validation: the wire body as it came.
func (r *Funding) WithdrawAddressesRaw(ctx context.Context, request withdrawaddresses.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.withdrawAddresses.WithdrawAddressesRaw(ctx, request, opts...)
}

// Cancel a recently requested withdrawal, if it has not already been successfully processed. Requires the `Funds permissions - Withdraw` API key permission, unless the withdrawal is a `WalletTransfer`, in which case no permissions are required.
//
// See https://docs.kraken.com/api-reference/funding/request-withdrawal-cancellation.
func (r *Funding) WithdrawCancel(ctx context.Context, request withdrawcancel.Request, opts ...truewire.CallOption) (withdrawcancel.Response, error) {
	return r.withdrawCancel.WithdrawCancel(ctx, request, opts...)
}

// WithdrawCancelRaw is WithdrawCancel without validation: the wire body as it came.
func (r *Funding) WithdrawCancelRaw(ctx context.Context, request withdrawcancel.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.withdrawCancel.WithdrawCancelRaw(ctx, request, opts...)
}

// Retrieve fee information about a potential withdrawal for a particular asset, key, and amount. Requires the `Funds permissions - Query` and `Funds permissions - Withdraw` API key permissions.
//
// See https://docs.kraken.com/api-reference/funding/get-withdrawal-information.
func (r *Funding) WithdrawInfo(ctx context.Context, request withdrawinfo.Request, opts ...truewire.CallOption) (withdrawinfo.WithdrawalInfo, error) {
	return r.withdrawInfo.WithdrawInfo(ctx, request, opts...)
}

// WithdrawInfoRaw is WithdrawInfo without validation: the wire body as it came.
func (r *Funding) WithdrawInfoRaw(ctx context.Context, request withdrawinfo.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.withdrawInfo.WithdrawInfoRaw(ctx, request, opts...)
}

// Retrieve a list of withdrawal methods available for the user. Requires the `Funds permissions - Query` and `Funds permissions - Withdraw` API key permissions.
//
// See https://docs.kraken.com/api-reference/funding/get-withdrawal-methods.
func (r *Funding) WithdrawMethods(ctx context.Context, request withdrawmethods.Request, opts ...truewire.CallOption) (withdrawmethods.Response, error) {
	return r.withdrawMethods.WithdrawMethods(ctx, request, opts...)
}

// WithdrawMethodsRaw is WithdrawMethods without validation: the wire body as it came.
func (r *Funding) WithdrawMethodsRaw(ctx context.Context, request withdrawmethods.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.withdrawMethods.WithdrawMethodsRaw(ctx, request, opts...)
}

// Retrieve information about recent withdrawals. Results are sorted by recency; use the `cursor` parameter to iterate through the list of withdrawals (page size equal to the value of `limit`) from newest to oldest. Requires the `Funds permissions - Withdraw` or `Data - Query ledger entries` API key permission.
//
// See https://docs.kraken.com/api-reference/funding/get-status-of-recent-withdrawals.
func (r *Funding) WithdrawStatus(ctx context.Context, request withdrawstatus.Request, opts ...truewire.CallOption) (withdrawstatus.Response, error) {
	return r.withdrawStatus.WithdrawStatus(ctx, request, opts...)
}

// WithdrawStatusRaw is WithdrawStatus without validation: the wire body as it came.
func (r *Funding) WithdrawStatusRaw(ctx context.Context, request withdrawstatus.Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	return r.withdrawStatus.WithdrawStatusRaw(ctx, request, opts...)
}
