// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'

export interface Request {
  /** Asset to transfer (asset ID or `altname`). */
  asset: string
  /** Source wallet. */
  from: 'Spot Wallet'
  /** Destination wallet. */
  to: 'Futures Wallet'
  /** Amount to transfer. */
  amount: string
}

export const Request: Codec<Request> = t.object({
  asset: t.string,
  from: t.literal('Spot Wallet'),
  to: t.literal('Futures Wallet'),
  amount: t.string,
})

/** Reference to the created wallet transfer. */
export interface WalletTransferReceipt {
  /** Reference ID. */
  refid: string
}

export const WalletTransferReceipt: Codec<WalletTransferReceipt> = t.object({
  refid: t.string,
})

/** `walletTransfer`'s request: `Request` with the fixed wire values the method fills in for you. */
export type WalletTransferArgs = Omit<Request, 'from' | 'to'> & { from?: 'Spot Wallet'; to?: 'Futures Wallet' }

/** Transfer from a Kraken Spot wallet to a Kraken Futures wallet. A transfer in the other direction must be requested via the Kraken Futures API withdrawal-to-Spot-wallet endpoint instead. Requires the `Funds permissions - Query` API key permission. */
export class WalletTransfer {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  walletTransfer(request: WalletTransferArgs, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Transfer from a Kraken Spot wallet to a Kraken Futures wallet. A transfer in the other direction must be requested via the Kraken Futures API withdrawal-to-Spot-wallet endpoint instead. Requires the `Funds permissions - Query` API key permission.
   *
   * @see https://docs.kraken.com/api-reference/funding/request-wallet-transfer
   */
  walletTransfer(request: WalletTransferArgs, options?: CallOptions): Promise<WalletTransferReceipt>
  async walletTransfer(request: WalletTransferArgs, options?: CallOptions): Promise<WalletTransferReceipt> {
    const wire: Request = { ...request, from: request.from ?? 'Spot Wallet', to: request.to ?? 'Futures Wallet' }
    return this.core.request({
      method: 'POST',
      path: '/0/private/WalletTransfer',
      request: wire,
      requestCodec: Request,
      responseCodec: WalletTransferReceipt,
      meta: { signed: true },
      ...options,
    })
  }
}
