//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::SpotMeta;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Asset being withdrawn.
    pub asset: String,
    /// Withdrawal reference ID.
    pub refid: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

pub type Response = bool;

/// Cancel a recently requested withdrawal, if it has not already been successfully processed. Requires the `Funds permissions - Withdraw` API key permission, unless the withdrawal is a `WalletTransfer`, in which case no permissions are required.
#[derive(Clone)]
pub struct WithdrawCancel {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl WithdrawCancel {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Cancel a recently requested withdrawal, if it has not already been successfully processed. Requires the `Funds permissions - Withdraw` API key permission, unless the withdrawal is a `WalletTransfer`, in which case no permissions are required.
    ///
    /// See <https://docs.kraken.com/api-reference/funding/request-withdrawal-cancellation>.
    pub async fn withdraw_cancel(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<Response> {
        let raw = self.withdraw_cancel_raw(request, options).await?;
        decode(raw)
    }

    /// `withdraw_cancel` without validation: the wire body as it came.
    pub async fn withdraw_cancel_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/WithdrawCancel",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
