//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampSeconds,
};

use crate::meta::SpotMeta;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestAclass {
    #[serde(rename = "currency")]
    Currency,
    #[serde(rename = "tokenized_asset")]
    TokenizedAsset,
}

#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RequestCursor {
    /// Enable/disable paginated response.
    Boolean(bool),
    /// Cursor for the next page of results.
    String(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestRebaseMultiplier {
    #[serde(rename = "rebased")]
    Rebased,
    #[serde(rename = "base")]
    Base,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Filter for a specific asset being withdrawn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    /// Filter for a specific asset class being withdrawn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aclass: Option<RequestAclass>,
    /// Filter for a specific name of withdrawal method.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// Start timestamp; withdrawals created strictly before this will not be included in the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    /// End timestamp; withdrawals created strictly after this will not be included in the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    /// `true`/`false` to enable/disable the paginated response shape, or a cursor string (returned by a previous call) to fetch the next page. Default `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<RequestCursor>,
    /// Number of results to include per page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity; `base` displays in terms of SPV tokens.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub rebase_multiplier: Option<Option<RequestRebaseMultiplier>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Withdrawal0ItemStatus {
    Initial,
    Pending,
    Settled,
    Success,
    Failure,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Withdrawal0ItemStatusProp {
    #[serde(rename = "cancel-pending")]
    CancelPending,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "cancel-denied")]
    CancelDenied,
    #[serde(rename = "return")]
    Return,
    #[serde(rename = "onhold")]
    Onhold,
}

/// One withdrawal record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Withdrawal0Item {
    /// Name of withdrawal method.
    pub method: String,
    /// Network name based on the funding method used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    /// Asset class.
    pub aclass: String,
    /// Asset.
    pub asset: String,
    /// Reference ID.
    pub refid: String,
    /// Method transaction ID.
    pub txid: String,
    /// Method transaction information.
    pub info: String,
    /// Amount withdrawn.
    pub amount: String,
    /// Fees paid. Type inferred as `string` by analogy with every other `fee` field in this operation family, since upstream declares no `type` for this property.
    pub fee: String,
    /// Unix timestamp when the request was made.
    pub time: TimestampSeconds,
    /// Status of the withdrawal. See the IFEX financial transaction states reference linked from upstream docs for background.
    pub status: Withdrawal0ItemStatus,
    /// Additional status property, if available: `cancel-pending` (cancellation requested), `canceled`, `cancel-denied` (cancellation requested but denied), `return` (a return transaction initiated by Kraken; cannot be canceled), or `onhold` (pending review).
    #[serde(
        rename = "status-prop",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_prop: Option<Withdrawal0ItemStatusProp>,
    /// Withdrawal key name, as set up on the account.
    pub key: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WithdrawalWithdrawalsItemStatus {
    Initial,
    Pending,
    Settled,
    Success,
    Failure,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum WithdrawalWithdrawalsItemStatusProp {
    #[serde(rename = "cancel-pending")]
    CancelPending,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "cancel-denied")]
    CancelDenied,
    #[serde(rename = "return")]
    Return,
    #[serde(rename = "onhold")]
    Onhold,
}

/// One withdrawal record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalWithdrawalsItem {
    /// Name of withdrawal method.
    pub method: String,
    /// Network name based on the funding method used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network: Option<String>,
    /// Asset class.
    pub aclass: String,
    /// Asset.
    pub asset: String,
    /// Reference ID.
    pub refid: String,
    /// Method transaction ID.
    pub txid: String,
    /// Method transaction information.
    pub info: String,
    /// Amount withdrawn.
    pub amount: String,
    /// Fees paid. Type inferred as `string` by analogy with every other `fee` field in this operation family, since upstream declares no `type` for this property.
    pub fee: String,
    /// Unix timestamp when the request was made.
    pub time: TimestampSeconds,
    /// Status of the withdrawal. See the IFEX financial transaction states reference linked from upstream docs for background.
    pub status: WithdrawalWithdrawalsItemStatus,
    /// Additional status property, if available: `cancel-pending` (cancellation requested), `canceled`, `cancel-denied` (cancellation requested but denied), `return` (a return transaction initiated by Kraken; cannot be canceled), or `onhold` (pending review).
    #[serde(
        rename = "status-prop",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_prop: Option<WithdrawalWithdrawalsItemStatusProp>,
    /// Withdrawal key name, as set up on the account.
    pub key: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Paginated withdrawal results, returned when the `cursor` request parameter is set -- confirmed live; upstream's own OpenAPI schema only documents the bare-array shape for this endpoint (unlike deposit_status, which documents both).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct WithdrawStatusPage {
    /// Page of withdrawal records.
    pub withdrawals: Vec<WithdrawalWithdrawalsItem>,
    /// Cursor to pass back as `cursor` to fetch the next page of results. `null` once there is no further page -- confirmed live.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub next_cursor: Option<Option<String>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Response {
    /// Withdrawal records, returned when `cursor` is unset or `false`.
    Withdrawal0ItemList(Vec<Withdrawal0Item>),
    WithdrawStatusPage(WithdrawStatusPage),
}

/// Retrieve information about recent withdrawals. Results are sorted by recency; use the `cursor` parameter to iterate through the list of withdrawals (page size equal to the value of `limit`) from newest to oldest. Requires the `Funds permissions - Withdraw` or `Data - Query ledger entries` API key permission.
#[derive(Clone)]
pub struct WithdrawStatus {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl WithdrawStatus {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Retrieve information about recent withdrawals. Results are sorted by recency; use the `cursor` parameter to iterate through the list of withdrawals (page size equal to the value of `limit`) from newest to oldest. Requires the `Funds permissions - Withdraw` or `Data - Query ledger entries` API key permission.
    ///
    /// See <https://docs.kraken.com/api-reference/funding/get-status-of-recent-withdrawals>.
    pub async fn withdraw_status(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<Response> {
        let raw = self.withdraw_status_raw(request, options).await?;
        decode(raw)
    }

    /// `withdraw_status` without validation: the wire body as it came.
    pub async fn withdraw_status_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/WithdrawStatus",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
