//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso,
};

use crate::meta::SpotMeta;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationAmountValue0 {
    /// Amount in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Amount converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Reward accumulated in the payout period so far.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationAmountValueAccumulatedReward {
    /// Amount in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Amount converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Estimated reward from now until the payout.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationAmountValueEstimatedReward {
    /// Amount in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Amount converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Total amount allocated to this Earn strategy, across every state.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationAmountValueTotal {
    /// Amount in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Amount converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Amount earned using this strategy over the account's whole lifetime.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationAmountValueTotalRewarded {
    /// Amount in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Amount converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One individual allocation contributing to a bonding/exit-queue/unbonding state, and when it transitions to the next state.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationEntryBondingAnyOf0AllocationsItem {
    /// When the request that created this allocation (allocate, or deallocate for exit-queue/unbonding) was received and processed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<TimestampIso>,
    /// When these funds finish unbonding. For `exit_queue`, this is the unbonding completion time, not the time the funds leave the exit queue.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires: Option<TimestampIso>,
    /// Amount in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Amount converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One individual allocation contributing to a bonding/exit-queue/unbonding state, and when it transitions to the next state.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationEntryExitQueueAnyOf0AllocationsItem {
    /// When the request that created this allocation (allocate, or deallocate for exit-queue/unbonding) was received and processed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<TimestampIso>,
    /// When these funds finish unbonding. For `exit_queue`, this is the unbonding completion time, not the time the funds leave the exit queue.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires: Option<TimestampIso>,
    /// Amount in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Amount converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One individual allocation contributing to a bonding/exit-queue/unbonding state, and when it transitions to the next state.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationEntryUnbondingAnyOf0AllocationsItem {
    /// When the request that created this allocation (allocate, or deallocate for exit-queue/unbonding) was received and processed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<TimestampIso>,
    /// When these funds finish unbonding. For `exit_queue`, this is the unbonding completion time, not the time the funds leave the exit queue.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires: Option<TimestampIso>,
    /// Amount in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Amount converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Filters for the allocation listing.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// `true` to sort ascending, `false` (the default) for descending.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub ascending: Option<Option<bool>>,
    /// A secondary currency to express the value of allocations in. Defaults to USD.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub converted_asset: Option<Option<String>>,
    /// Omit entries for strategies used in the past that now hold no allocation. Defaults to `false`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub hide_zero_allocations: Option<Option<bool>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationPayout {
    /// When the current payout period started -- either the last payout date or when it was enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub period_start: Option<TimestampIso>,
    /// Tentative date of the next reward payout.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub period_end: Option<TimestampIso>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accumulated_reward: Option<EarnAllocationAmountValueAccumulatedReward>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub estimated_reward: Option<EarnAllocationAmountValueEstimatedReward>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Amount allocated in one transitional state (bonding, exit-queue, or unbonding), with the individual allocations composing it.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationStateBondingAnyOf0 {
    /// Number of individual allocations in this state for this asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allocation_count: Option<i64>,
    /// Individual allocations composing this state, and when each expires into the next.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allocations: Option<Vec<EarnAllocationEntryBondingAnyOf0AllocationsItem>>,
    /// Total amount in this state, in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Total amount in this state, converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Amount allocated in one transitional state (bonding, exit-queue, or unbonding), with the individual allocations composing it.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationStateExitQueueAnyOf0 {
    /// Number of individual allocations in this state for this asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allocation_count: Option<i64>,
    /// Individual allocations composing this state, and when each expires into the next.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allocations: Option<Vec<EarnAllocationEntryExitQueueAnyOf0AllocationsItem>>,
    /// Total amount in this state, in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Total amount in this state, converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Amount allocated in one transitional state (bonding, exit-queue, or unbonding), with the individual allocations composing it.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationStateUnbondingAnyOf0 {
    /// Number of individual allocations in this state for this asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allocation_count: Option<i64>,
    /// Individual allocations composing this state, and when each expires into the next.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allocations: Option<Vec<EarnAllocationEntryUnbondingAnyOf0AllocationsItem>>,
    /// Total amount in this state, in the native asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native: Option<String>,
    /// Total amount in this state, converted into the requested asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Amounts allocated to this Earn strategy, broken down by state.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationAmount {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<EarnAllocationAmountValueTotal>,
    /// Amount in the bonding state. Present only when there are bonding allocations.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub bonding: Option<Option<EarnAllocationStateBondingAnyOf0>>,
    /// Amount in the exit-queue state (ETH only). Present only when there are exit-queue allocations.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub exit_queue: Option<Option<EarnAllocationStateExitQueueAnyOf0>>,
    /// Amount in the unbonding state. Present only when there are unbonding allocations.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub unbonding: Option<Option<EarnAllocationStateUnbondingAnyOf0>>,
    /// Pending (de)allocation amount -- negative when the pending operation is a deallocation. Present only when there is a pending operation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub pending: Option<Option<EarnAllocationAmountValue0>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The user's allocation to a single Earn strategy.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocation {
    /// Unique ID of the Earn strategy.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub strategy_id: Option<String>,
    /// The native asset of this allocation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub native_asset: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount_allocated: Option<EarnAllocationAmount>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_rewarded: Option<EarnAllocationAmountValueTotalRewarded>,
    /// Information about the current payout period. Absent when there is no current payout period.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub payout: Option<Option<EarnAllocationPayout>>,
    /// Asset class of native_asset, e.g. `currency`. Confirmed present live, not in upstream's own published field list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset_class: Option<String>,
    /// Whether this allocation is actively earning rewards. Confirmed present live, not in upstream's own published field list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_utilized: Option<bool>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The user's Earn allocations across all strategies.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EarnAllocationsResult {
    /// The secondary asset used to show the value of allocations, as chosen in the request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted_asset: Option<String>,
    /// Asset class of `converted_asset`, e.g. `currency`. Confirmed present live, not in upstream's own published field list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted_asset_class: Option<String>,
    /// Cursor for the next page. Present as `null` on a live call even though upstream's own response schema doesn't declare it (only its worked example does, likely copied from `Strategies`); see `notes` -- paging is not documented as implemented for this endpoint either.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub next_cursor: Option<Option<String>>,
    /// Total amount allocated across all strategies, denominated in `converted_asset`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_allocated: Option<String>,
    /// Amount earned across all strategies over the account's lifetime, denominated in `converted_asset`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_rewarded: Option<String>,
    /// One entry per strategy the user has (or has had) an allocation in.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<EarnAllocation>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// List all allocations for the user.
///
/// Requires the `Query Funds` API key permission.
///
/// By default all allocations are returned, even for strategies that have been used in the past and now have zero balance, so the user can see how much was earned with a given strategy historically. `hide_zero_allocations` removes zero-balance entries from the output. Paging hasn't been implemented for this method, as the result for a particular user isn't expected to be overwhelmingly large.
///
/// All amounts in the output can be denominated in a currency of the user's choice (the `converted_asset` parameter). Information about when the next reward will be paid is also provided.
///
/// Allocated funds can be in up to 4 states: `bonding`, `allocated`, `exit_queue` (ETH only), `unbonding`. Any funds in `total` not in `bonding`/`unbonding` are simply allocated and earning rewards; whether the other states also earn rewards depends on the strategy (see `Earn/Strategies`). ETH in `exit_queue` still earns rewards.
///
/// For ETH, when funds are in `exit_queue`, the `expires` time given is when the funds finish unbonding, not when they leave the exit queue for unbonding.
///
/// (Un)bonding time estimates can be inaccurate immediately after (de)allocating; wait 1-2 minutes for an accurate result.
#[derive(Clone)]
pub struct Allocations {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl Allocations {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// List all allocations for the user.
    ///
    /// Requires the `Query Funds` API key permission.
    ///
    /// By default all allocations are returned, even for strategies that have been used in the past and now have zero balance, so the user can see how much was earned with a given strategy historically. `hide_zero_allocations` removes zero-balance entries from the output. Paging hasn't been implemented for this method, as the result for a particular user isn't expected to be overwhelmingly large.
    ///
    /// All amounts in the output can be denominated in a currency of the user's choice (the `converted_asset` parameter). Information about when the next reward will be paid is also provided.
    ///
    /// Allocated funds can be in up to 4 states: `bonding`, `allocated`, `exit_queue` (ETH only), `unbonding`. Any funds in `total` not in `bonding`/`unbonding` are simply allocated and earning rewards; whether the other states also earn rewards depends on the strategy (see `Earn/Strategies`). ETH in `exit_queue` still earns rewards.
    ///
    /// For ETH, when funds are in `exit_queue`, the `expires` time given is when the funds finish unbonding, not when they leave the exit queue for unbonding.
    ///
    /// (Un)bonding time estimates can be inaccurate immediately after (de)allocating; wait 1-2 minutes for an accurate result.
    ///
    /// See <https://docs.kraken.com/api-reference/earn/list-earn-allocations>.
    pub async fn allocations(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<EarnAllocationsResult> {
        let raw = self.allocations_raw(request, options).await?;
        decode(raw)
    }

    /// `allocations` without validation: the wire body as it came.
    pub async fn allocations_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/Earn/Allocations",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
