// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'
import * as allocate from './allocate.js'
import * as allocateStatus from './allocate_status.js'
import * as allocations from './allocations.js'
import * as deallocate from './deallocate.js'
import * as deallocateStatus from './deallocate_status.js'
import * as strategies from './strategies.js'

/**
 * Kraken Earn: list strategies, allocate/deallocate funds to one, and poll the
 * asynchronous (de)allocation status.
 *
 * @see https://docs.kraken.com/api-reference/earn
 */
export class Earn {
  private readonly allocate_: allocate.Allocate
  private readonly allocateStatus_: allocateStatus.AllocateStatus
  private readonly allocations_: allocations.Allocations
  private readonly deallocate_: deallocate.Deallocate
  private readonly deallocateStatus_: deallocateStatus.DeallocateStatus
  private readonly strategies_: strategies.Strategies

  constructor(readonly core: HttpEndpoint<SpotMeta>) {
    this.allocate_ = new allocate.Allocate(core)
    this.allocateStatus_ = new allocateStatus.AllocateStatus(core)
    this.allocations_ = new allocations.Allocations(core)
    this.deallocate_ = new deallocate.Deallocate(core)
    this.deallocateStatus_ = new deallocateStatus.DeallocateStatus(core)
    this.strategies_ = new strategies.Strategies(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  allocate(request: allocate.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Allocate funds to a strategy.
   *
   * Requires the `Earn Funds` API key permission. The amount must always be defined.
   *
   * This method is asynchronous. A couple of preflight checks are performed synchronously before the request is dispatched further; the client is required to poll the result using `spot.earn.allocate_status` (`/0/private/Earn/AllocateStatus`).
   *
   * There can be only one (de)allocation request in progress for a given user and strategy at a time. While the operation is in progress: the `pending` attribute in the `spot.earn.allocations` response for the strategy indicates funds are being allocated, and the `pending` attribute in `spot.earn.allocate_status`'s response is `true`.
   *
   * Specific errors within the `Earnings` error class this method can return:
   * - Minimum allocation: `EEarnings:Below min:(De)allocation operation amount less than minimum`
   * - Allocation in progress: `EEarnings:Busy:Another (de)allocation for the same strategy is in progress`
   * - Service temporarily unavailable: `EEarnings:Busy` -- retry in a few minutes
   * - User tier verification: `EEarnings:Permission denied:The user's tier is not high enough`
   * - Strategy not found: `EGeneral:Invalid arguments:Invalid strategy ID`
   *
   * @see https://docs.kraken.com/api-reference/earn/allocate-earn-funds
   */
  allocate(request: allocate.Request, options?: CallOptions): Promise<allocate.Response>
  allocate(request: allocate.Request, options?: CallOptions): Promise<allocate.Response> {
    return this.allocate_.allocate(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  allocateStatus(request: allocateStatus.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get the status of the last allocation request.
   *
   * Requires either the `Earn Funds` or `Query Funds` API key permission.
   *
   * (De)allocation operations are asynchronous, and this endpoint lets the client retrieve the status of the last dispatched operation. There can be only one (de)allocation request in progress for a given user and strategy.
   *
   * The `pending` attribute in the response indicates whether the previously dispatched operation is still in progress (`true`) or has completed (`false`). If the dispatched request failed with an error, the HTTP error is returned to the client as if it belonged to this request.
   *
   * Specific errors within the `Earnings` error class this method can return:
   * - Insufficient funds: `EEarnings:Insufficient funds:Insufficient funds to complete the (de)allocation request`
   * - User cap exceeded: `EEarnings:Above max:The allocation exceeds user limit for the strategy`
   * - Total cap exceeded: `EEarnings:Above max:The allocation exceeds the total strategy limit`
   * - Minimum allocation: `EEarnings:Below min:(De)allocation operation amount less than minimum`
   *
   * @see https://docs.kraken.com/api-reference/earn/get-allocation-status
   */
  allocateStatus(request: allocateStatus.Request, options?: CallOptions): Promise<allocateStatus.Response>
  allocateStatus(request: allocateStatus.Request, options?: CallOptions): Promise<allocateStatus.Response> {
    return this.allocateStatus_.allocateStatus(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  allocations(request: allocations.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * List all allocations for the user.
   *
   * Requires the `Query Funds` API key permission.
   *
   * By default all allocations are returned, even for strategies that have been used in the past and now have zero balance, so the user can see how much was earned with a given strategy historically. `hide_zero_allocations` removes zero-balance entries from the output. Paging hasn't been implemented for this method, as the result for a particular user isn't expected to be overwhelmingly large.
   *
   * All amounts in the output can be denominated in a currency of the user's choice (the `converted_asset` parameter). Information about when the next reward will be paid is also provided.
   *
   * Allocated funds can be in up to 4 states: `bonding`, `allocated`, `exit_queue` (ETH only), `unbonding`. Any funds in `total` not in `bonding`/`unbonding` are simply allocated and earning rewards; whether the other states also earn rewards depends on the strategy (see `Earn/Strategies`). ETH in `exit_queue` still earns rewards.
   *
   * For ETH, when funds are in `exit_queue`, the `expires` time given is when the funds finish unbonding, not when they leave the exit queue for unbonding.
   *
   * (Un)bonding time estimates can be inaccurate immediately after (de)allocating; wait 1-2 minutes for an accurate result.
   *
   * @see https://docs.kraken.com/api-reference/earn/list-earn-allocations
   */
  allocations(request?: allocations.Request, options?: CallOptions): Promise<allocations.EarnAllocationsResult>
  allocations(request?: allocations.Request, options?: CallOptions): Promise<allocations.EarnAllocationsResult> {
    return this.allocations_.allocations(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  deallocate(request: deallocate.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Deallocate funds from a strategy.
   *
   * Requires the `Earn Funds` API key permission. The amount must always be defined.
   *
   * This method is asynchronous. A couple of preflight checks are performed synchronously before the request is dispatched further; the client is required to poll the result using `spot.earn.deallocate_status` (`/0/private/Earn/DeallocateStatus`).
   *
   * There can be only one (de)allocation request in progress for a given user and strategy at a time. While the operation is in progress: the `pending` attribute in the `spot.earn.allocations` response for the strategy holds the amount being deallocated (a negative amount), and the `pending` attribute in `spot.earn.deallocate_status`'s response is `true`.
   *
   * Specific errors within the `Earnings` error class this method can return:
   * - Minimum allocation: `EEarnings:Below min:(De)allocation operation amount less than minimum allowed`
   * - Allocation in progress: `EEarnings:Busy:Another (de)allocation for the same strategy is in progress`
   * - Strategy not found: `EGeneral:Invalid arguments:Invalid strategy ID`
   *
   * @see https://docs.kraken.com/api-reference/earn/deallocate-earn-funds
   */
  deallocate(request: deallocate.Request, options?: CallOptions): Promise<deallocate.Response>
  deallocate(request: deallocate.Request, options?: CallOptions): Promise<deallocate.Response> {
    return this.deallocate_.deallocate(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  deallocateStatus(request: deallocateStatus.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get the status of the last deallocation request.
   *
   * Requires either the `Earn Funds` or `Query Funds` API key permission.
   *
   * (De)allocation operations are asynchronous, and this endpoint lets the client retrieve the status of the last dispatched operation. There can be only one (de)allocation request in progress for a given user and strategy.
   *
   * The `pending` attribute in the response indicates whether the previously dispatched operation is still in progress (`true`) or has completed (`false`). If the dispatched request failed with an error, the HTTP error is returned to the client as if it belonged to this request.
   *
   * Specific errors within the `Earnings` error class this method can return:
   * - Insufficient funds: `EEarnings:Insufficient funds:Insufficient funds to complete the (de)allocation request`
   * - Minimum allocation: `EEarnings:Below min:(De)allocation operation amount less than minimum`
   *
   * @see https://docs.kraken.com/api-reference/earn/get-deallocation-status
   */
  deallocateStatus(request: deallocateStatus.Request, options?: CallOptions): Promise<deallocateStatus.Response>
  deallocateStatus(request: deallocateStatus.Request, options?: CallOptions): Promise<deallocateStatus.Response> {
    return this.deallocateStatus_.deallocateStatus(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  strategies(request: strategies.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * List earn strategies along with their parameters.
   *
   * Requires a valid API key but no specific permission is required.
   *
   * Returns only strategies that are available to the user based on geographic region.
   *
   * When the user does not meet the tier restriction, `can_allocate` will be false and `allocation_restriction_info` indicates `Tier` as the restriction reason. Earn products generally require Intermediate tier.
   *
   * A note about `lock_type`:
   * - `instant`: can be deallocated without an unbonding period. Called flexible in the UI.
   * - `bonded`: has an unbonding period. Deallocation will not happen until this period has passed.
   * - `flex`: "Kraken rewards" -- earning on spot balances where eligible. It's turned on account-wide from the UI and cannot be manually allocated to.
   *
   * Paging isn't yet implemented, so the endpoint always returns all data in the first page.
   *
   * @see https://docs.kraken.com/api-reference/earn/list-earn-strategies
   */
  strategies(request?: strategies.Request, options?: CallOptions): Promise<strategies.EarnStrategiesResult>
  strategies(request?: strategies.Request, options?: CallOptions): Promise<strategies.EarnStrategiesResult> {
    return this.strategies_.strategies(request, options)
  }
}
