// Code generated by truewire. DO NOT EDIT.

// Package queryledgers is the `spot.account.query_ledgers` endpoint.
package queryledgers

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/kraken/src/kraken/meta"
)

type LedgerEntryType string

const LedgerEntryTypeNone LedgerEntryType = "none"
const LedgerEntryTypeTrade LedgerEntryType = "trade"
const LedgerEntryTypeDeposit LedgerEntryType = "deposit"
const LedgerEntryTypeWithdrawal LedgerEntryType = "withdrawal"
const LedgerEntryTypeTransfer LedgerEntryType = "transfer"
const LedgerEntryTypeMargin LedgerEntryType = "margin"
const LedgerEntryTypeAdjustment LedgerEntryType = "adjustment"
const LedgerEntryTypeRollover LedgerEntryType = "rollover"
const LedgerEntryTypeSpend LedgerEntryType = "spend"
const LedgerEntryTypeReceive LedgerEntryType = "receive"
const LedgerEntryTypeSettled LedgerEntryType = "settled"
const LedgerEntryTypeCredit LedgerEntryType = "credit"
const LedgerEntryTypeStaking LedgerEntryType = "staking"
const LedgerEntryTypeReward LedgerEntryType = "reward"
const LedgerEntryTypeDividend LedgerEntryType = "dividend"
const LedgerEntryTypeSale LedgerEntryType = "sale"
const LedgerEntryTypeConversion LedgerEntryType = "conversion"
const LedgerEntryTypeNfttrade LedgerEntryType = "nfttrade"
const LedgerEntryTypeNftcreatorfee LedgerEntryType = "nftcreatorfee"
const LedgerEntryTypeNftrebate LedgerEntryType = "nftrebate"
const LedgerEntryTypeCustodytransfer LedgerEntryType = "custodytransfer"

// UnmarshalJSON accepts only the literal's values.
func (v *LedgerEntryType) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, LedgerEntryTypeNone, LedgerEntryTypeTrade, LedgerEntryTypeDeposit, LedgerEntryTypeWithdrawal, LedgerEntryTypeTransfer, LedgerEntryTypeMargin, LedgerEntryTypeAdjustment, LedgerEntryTypeRollover, LedgerEntryTypeSpend, LedgerEntryTypeReceive, LedgerEntryTypeSettled, LedgerEntryTypeCredit, LedgerEntryTypeStaking, LedgerEntryTypeReward, LedgerEntryTypeDividend, LedgerEntryTypeSale, LedgerEntryTypeConversion, LedgerEntryTypeNfttrade, LedgerEntryTypeNftcreatorfee, LedgerEntryTypeNftrebate, LedgerEntryTypeCustodytransfer)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v LedgerEntryType) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, LedgerEntryTypeNone, LedgerEntryTypeTrade, LedgerEntryTypeDeposit, LedgerEntryTypeWithdrawal, LedgerEntryTypeTransfer, LedgerEntryTypeMargin, LedgerEntryTypeAdjustment, LedgerEntryTypeRollover, LedgerEntryTypeSpend, LedgerEntryTypeReceive, LedgerEntryTypeSettled, LedgerEntryTypeCredit, LedgerEntryTypeStaking, LedgerEntryTypeReward, LedgerEntryTypeDividend, LedgerEntryTypeSale, LedgerEntryTypeConversion, LedgerEntryTypeNfttrade, LedgerEntryTypeNftcreatorfee, LedgerEntryTypeNftrebate, LedgerEntryTypeCustodytransfer)
}

// One ledger entry.
type LedgerEntry struct {
	// Reference ID of the parent transaction (trade, deposit, withdrawal, etc.) that caused the ledger entry.
	Refid *string
	// Unix timestamp of the ledger entry.
	Time *truewire.TimestampSeconds
	// Type of ledger entry.
	Type *LedgerEntryType
	// Additional info relating to the ledger entry type, where applicable.
	Subtype *string
	// Asset class.
	Aclass *string
	// Asset.
	Asset *string
	// Transaction amount.
	Amount *string
	// Transaction fee.
	Fee *string
	// Resulting balance.
	Balance *string
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *LedgerEntry) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalField("refid", &r.Refid),
		truewire.OptionalField("time", &r.Time),
		truewire.OptionalField("type", &r.Type),
		truewire.OptionalField("subtype", &r.Subtype),
		truewire.OptionalField("aclass", &r.Aclass),
		truewire.OptionalField("asset", &r.Asset),
		truewire.OptionalField("amount", &r.Amount),
		truewire.OptionalField("fee", &r.Fee),
		truewire.OptionalField("balance", &r.Balance),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r LedgerEntry) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalField("refid", &r.Refid),
		truewire.OptionalField("time", &r.Time),
		truewire.OptionalField("type", &r.Type),
		truewire.OptionalField("subtype", &r.Subtype),
		truewire.OptionalField("aclass", &r.Aclass),
		truewire.OptionalField("asset", &r.Asset),
		truewire.OptionalField("amount", &r.Amount),
		truewire.OptionalField("fee", &r.Fee),
		truewire.OptionalField("balance", &r.Balance),
	)
}

type RequestRebaseMultiplier string

const RequestRebaseMultiplierRebased RequestRebaseMultiplier = "rebased"
const RequestRebaseMultiplierBase RequestRebaseMultiplier = "base"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestRebaseMultiplier) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestRebaseMultiplierRebased, RequestRebaseMultiplierBase)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestRebaseMultiplier) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestRebaseMultiplierRebased, RequestRebaseMultiplierBase)
}

type Request struct {
	// Comma-delimited list of ledger IDs to query info about (20 maximum).
	ID string
	// Whether or not to include trades related to position in output.
	Trades *bool
	// Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity, `base` displays in terms of SPV tokens.
	RebaseMultiplier truewire.Optional[*RequestRebaseMultiplier]
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Request) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("id", &r.ID),
		truewire.OptionalField("trades", &r.Trades),
		truewire.OptionalNullable("rebase_multiplier", &r.RebaseMultiplier),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Request) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("id", &r.ID),
		truewire.OptionalField("trades", &r.Trades),
		truewire.OptionalNullable("rebase_multiplier", &r.RebaseMultiplier),
	)
}

type QueriedLedgers = map[string]LedgerEntry

// Endpoint is the `spot.account.query_ledgers` endpoint.
//
// Retrieve information about specific ledger entries, by ledger ID.
//
// **Note on Staking/Earn assets:** assets migrated from the legacy Staking system to the new Earn system may appear with symbol extensions -- `.B` (new yield-bearing products), `.F` (auto-earning Kraken Rewards) -- these are read-only for transacting; use the base asset instead.
//
// **API Key Permissions Required:** `Data - Query ledger entries`
type Endpoint struct {
	core truewire.HttpEndpoint
}

// New returns the endpoint over core.
func New(core truewire.HttpEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// Retrieve information about specific ledger entries, by ledger ID.
//
// **Note on Staking/Earn assets:** assets migrated from the legacy Staking system to the new Earn system may appear with symbol extensions -- `.B` (new yield-bearing products), `.F` (auto-earning Kraken Rewards) -- these are read-only for transacting; use the base asset instead.
//
// **API Key Permissions Required:** `Data - Query ledger entries`
//
// See https://docs.kraken.com/api-reference/account-data/query-ledgers.
func (e *Endpoint) QueryLedgers(ctx context.Context, request Request, opts ...truewire.CallOption) (QueriedLedgers, error) {
	return truewire.DecodeResult[QueriedLedgers](e.QueryLedgersRaw(ctx, request, opts...))
}

// QueryLedgersRaw is QueryLedgers without validation: the wire body as it came.
func (e *Endpoint) QueryLedgersRaw(ctx context.Context, request Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	body, err := truewire.Dump(request)
	if err != nil {
		return nil, err
	}
	return e.core.Request(ctx, truewire.HttpCall{Method: "POST", Path: "/0/private/QueryLedgers", Request: body, Meta: meta.SpotMeta{Signed: truewire.Ptr(true)}, Options: truewire.Options(opts...)})
}
