// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type CommandEndpoint, type TimestampIso, t } from '@truewire/core'
import { OrderTriggers, WsConditionalCloseOrder } from '../types/index.js'

/** Result of one order within a successful `batch_add` call. */
export interface BatchOrderResult {
  /** Unique order identifier generated by Kraken. */
  order_id?: string
  /** The client identifier specified for this order in the request, if any. */
  cl_ord_id?: string
  /** The client identifier specified for this order in the request, if any. */
  order_userref?: number
  /** Non-fatal warnings about the order, if any. */
  warnings?: string[]
}

export const BatchOrderResult: Codec<BatchOrderResult> = t.object({
  order_id: t.optional(t.string),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  warnings: t.optional(t.array(t.string)),
})

export type BatchAddResult = BatchOrderResult[]

export const BatchAddResult: Codec<BatchAddResult> = t.array(BatchOrderResult)

/** An iceberg order within a batch_add request: a limit order that shows only `display_qty` of its quantity in the book while the rest remains hidden. */
export interface WsBatchOrderIceberg {
  /** The execution model of the order. */
  order_type: 'iceberg'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  /** Limit price, for order types that support a limit price restriction. */
  limit_price: number
  /** For iceberg orders only: quantity to show in the book while the rest of `order_qty` remains hidden. Minimum value is 1/15 of `order_qty`. */
  display_qty: number
}

export const WsBatchOrderIceberg: Codec<WsBatchOrderIceberg> = t.object({
  order_type: t.literal('iceberg'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  limit_price: t.number,
  display_qty: t.number,
})

/** A limit order within a batch_add request: rests in the book at `limit_price` or better. */
export interface WsBatchOrderLimit {
  /** The execution model of the order. */
  order_type: 'limit'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  /** Limit price, for order types that support a limit price restriction. */
  limit_price: number
}

export const WsBatchOrderLimit: Codec<WsBatchOrderLimit> = t.object({
  order_type: t.literal('limit'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  limit_price: t.number,
})

/** A market order within a batch_add request: executes immediately at the best available price. */
export interface WsBatchOrderMarket {
  /** The execution model of the order. */
  order_type: 'market'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  /** Order volume expressed in the quote currency. Market orders only. */
  cash_order_qty?: number
}

export const WsBatchOrderMarket: Codec<WsBatchOrderMarket> = t.object({
  order_type: t.literal('market'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  cash_order_qty: t.optional(t.number),
})

/** Settles an open leveraged position at the current market price, within a batch_add request. */
export interface WsBatchOrderSettlePosition {
  /** The execution model of the order. */
  order_type: 'settle-position'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
}

export const WsBatchOrderSettlePosition: Codec<WsBatchOrderSettlePosition> = t.object({
  order_type: t.literal('settle-position'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
})

/** A stop-loss order within a batch_add request: becomes a market order once `triggers.price` is reached in an unfavourable direction. */
export interface WsBatchOrderStopLoss {
  /** The execution model of the order. */
  order_type: 'stop-loss'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  triggers: OrderTriggers
}

export const WsBatchOrderStopLoss: Codec<WsBatchOrderStopLoss> = t.object({
  order_type: t.literal('stop-loss'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  triggers: OrderTriggers,
})

/** A stop-loss-limit order within a batch_add request: becomes a limit order at `limit_price` once `triggers.price` is reached in an unfavourable direction. */
export interface WsBatchOrderStopLossLimit {
  /** The execution model of the order. */
  order_type: 'stop-loss-limit'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  triggers: OrderTriggers
  /** Limit price, for order types that support a limit price restriction. */
  limit_price: number
}

export const WsBatchOrderStopLossLimit: Codec<WsBatchOrderStopLossLimit> = t.object({
  order_type: t.literal('stop-loss-limit'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  triggers: OrderTriggers,
  limit_price: t.number,
})

/** A take-profit order within a batch_add request: becomes a market order once `triggers.price` is reached in a favourable direction. */
export interface WsBatchOrderTakeProfit {
  /** The execution model of the order. */
  order_type: 'take-profit'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  triggers: OrderTriggers
}

export const WsBatchOrderTakeProfit: Codec<WsBatchOrderTakeProfit> = t.object({
  order_type: t.literal('take-profit'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  triggers: OrderTriggers,
})

/** A take-profit-limit order within a batch_add request: becomes a limit order at `limit_price` once `triggers.price` is reached in a favourable direction. */
export interface WsBatchOrderTakeProfitLimit {
  /** The execution model of the order. */
  order_type: 'take-profit-limit'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  triggers: OrderTriggers
  /** Limit price, for order types that support a limit price restriction. */
  limit_price: number
}

export const WsBatchOrderTakeProfitLimit: Codec<WsBatchOrderTakeProfitLimit> = t.object({
  order_type: t.literal('take-profit-limit'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  triggers: OrderTriggers,
  limit_price: t.number,
})

/** A trailing-stop order within a batch_add request: triggers as a market order once the price reverts by `triggers.price` from its peak/trough since order entry. */
export interface WsBatchOrderTrailingStop {
  /** The execution model of the order. */
  order_type: 'trailing-stop'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  triggers: OrderTriggers
}

export const WsBatchOrderTrailingStop: Codec<WsBatchOrderTrailingStop> = t.object({
  order_type: t.literal('trailing-stop'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  triggers: OrderTriggers,
})

/** A trailing-stop-limit order within a batch_add request: triggers a limit order at `limit_price` (an offset from the trigger price, per `limit_price_type`) once the price reverts by `triggers.price` from its peak/trough since order entry. */
export interface WsBatchOrderTrailingStopLimit {
  /** The execution model of the order. */
  order_type: 'trailing-stop-limit'
  /** Side of the order. */
  side: 'buy' | 'sell'
  /** Order quantity in terms of the base asset. */
  order_qty: number
  conditional?: WsConditionalCloseOrder
  /** Scheduled start time, RFC3339, precision to seconds. */
  effective_time?: TimestampIso
  /** Expiration time of the order, RFC3339, precision to seconds. GTD orders only; can expire up to one month in the future. */
  expire_time?: TimestampIso
  /** Fee preference, base or quote currency. `quote` is the default for buy orders, `base` is the default for sell orders. */
  fee_preference?: 'base' | 'quote'
  /** Funds the order on margin using the maximum leverage for the pair (max leverage of 5). */
  margin?: boolean
  /** Deprecated -- if supplied, accepted but ignored. Was: disable Market Price Protection for market orders. */
  no_mpp?: boolean
  /** Alphanumeric client order identifier uniquely identifying this order. Mutually exclusive with `order_userref`. One of: a long UUID (32 hex chars, dashed), a short UUID (32 hex chars, no dashes), or free text up to 18 ASCII characters. */
  cl_ord_id?: string
  /** Optional non-unique numeric identifier associable with any number of orders by the client. Mutually exclusive with `cl_ord_id`. */
  order_userref?: number
  /** Cancels the order if it would take liquidity on arrival. For orders with a limit price only. */
  post_only?: boolean
  /** Reduces an existing margin position without opening an opposite position worth more than the current value of the leveraged assets. */
  reduce_only?: boolean
  /** Self Trade Prevention mode: `cancel_newest` (cancel the arriving order), `cancel_oldest` (cancel the resting order), or `cancel_both`. */
  stp_type?: 'cancel_newest' | 'cancel_oldest' | 'cancel_both'
  /** How long the order remains in effect before expiring: `gtc`, `gtd` (until `expire_time`), `ioc` (cancels any unfilled remainder on arrival), or `fok` (fills fully or cancels entirely; `limit` orders only). */
  time_in_force?: 'gtc' | 'gtd' | 'ioc' | 'fok'
  /** Alphanumeric sub-account/trader identifier enabling Self Trade Prevention at a more granular level, for institutional accounts with enhanced STP. */
  sender_sub_id?: string
  /** Deprecated -- use the `triggers` object. */
  stop_price?: number
  /** Deprecated -- use `triggers.reference`. Triggered order types only. */
  trigger?: 'index' | 'last'
  triggers: OrderTriggers
  /** Limit price, for order types that support a limit price restriction. */
  limit_price: number
  /** Units for `limit_price`: `static` (a static market price), `pct` (a percentage offset from the reference price), or `quote` (a notional offset in the quote currency). Only available on `trailing-stop-limit` orders, where it is an offset from the trigger price (`0` sets the limit price equal to the trigger price). */
  limit_price_type?: 'static' | 'pct' | 'quote'
}

export const WsBatchOrderTrailingStopLimit: Codec<WsBatchOrderTrailingStopLimit> = t.object({
  order_type: t.literal('trailing-stop-limit'),
  side: t.literal('buy', 'sell'),
  order_qty: t.number,
  conditional: t.optional(WsConditionalCloseOrder),
  effective_time: t.optional(t.dateTime),
  expire_time: t.optional(t.dateTime),
  fee_preference: t.optional(t.literal('base', 'quote')),
  margin: t.optional(t.boolean),
  no_mpp: t.optional(t.boolean),
  cl_ord_id: t.optional(t.string),
  order_userref: t.optional(t.integer),
  post_only: t.optional(t.boolean),
  reduce_only: t.optional(t.boolean),
  stp_type: t.optional(t.literal('cancel_newest', 'cancel_oldest', 'cancel_both')),
  time_in_force: t.optional(t.literal('gtc', 'gtd', 'ioc', 'fok')),
  sender_sub_id: t.optional(t.string),
  stop_price: t.optional(t.number),
  trigger: t.optional(t.literal('index', 'last')),
  triggers: OrderTriggers,
  limit_price: t.number,
  limit_price_type: t.optional(t.literal('static', 'pct', 'quote')),
})

/** Parameters for submitting a batch of 2-15 orders in a single request, all on one pair. Validation runs against the whole batch before submission -- one invalid order rejects the entire batch. On submission, an individual order failing a pre-match check (e.g. insufficient funding) is rejected on its own and the rest of the batch is processed. */
export interface Request {
  /** RFC3339 timestamp, millisecond precision. Valid offsets from the current time range from 500ms to 60s (default 5s). The engine will not match orders in this batch after this time. */
  deadline?: TimestampIso
  /** The symbol of the currency pair for every order in the batch, e.g. `BTC/USD`. */
  symbol: string
  /** If `true`, every order in the batch is validated only -- none reaches the matching engine. */
  validate?: boolean
  /** The orders in the batch, 2 to 15 of them, all on `symbol`. */
  orders: (WsBatchOrderMarket | WsBatchOrderLimit | WsBatchOrderIceberg | WsBatchOrderStopLoss | WsBatchOrderStopLossLimit | WsBatchOrderTakeProfit | WsBatchOrderTakeProfitLimit | WsBatchOrderTrailingStop | WsBatchOrderTrailingStopLimit | WsBatchOrderSettlePosition)[]
}

export const Request: Codec<Request> = t.object({
  deadline: t.optional(t.dateTime),
  symbol: t.string,
  validate: t.optional(t.boolean),
  orders: t.array(t.union(WsBatchOrderMarket, WsBatchOrderLimit, WsBatchOrderIceberg, WsBatchOrderStopLoss, WsBatchOrderStopLossLimit, WsBatchOrderTakeProfit, WsBatchOrderTakeProfitLimit, WsBatchOrderTrailingStop, WsBatchOrderTrailingStopLimit, WsBatchOrderSettlePosition)),
})

/** Sends a batch of 2-15 orders in a single request, all sharing one pair. Validation runs against the whole batch before submission to the engine -- if any order fails validation, the whole batch is rejected. Once submitted, an order failing a pre-match check (e.g. insufficient funding) is rejected individually and the rest of the batch is processed. */
export class BatchAdd {
  constructor(readonly core: CommandEndpoint) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  batchAdd(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Sends a batch of 2-15 orders in a single request, all sharing one pair. Validation runs against the whole batch before submission to the engine -- if any order fails validation, the whole batch is rejected. Once submitted, an order failing a pre-match check (e.g. insufficient funding) is rejected individually and the rest of the batch is processed.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/batch_add
   */
  batchAdd(request: Request, options?: CallOptions): Promise<BatchAddResult>
  async batchAdd(request: Request, options?: CallOptions): Promise<BatchAddResult> {
    return this.core.request({
      path: 'batch_add',
      request,
      requestCodec: Request,
      responseCodec: BatchAddResult,
      meta: {},
      ...options,
    })
  }
}
