//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, CommandCall, CommandEndpoint, Result, TimestampIso,
};

/// Result of a successful `cancel_all_orders_after` call.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CancelAllOrdersAfterResult {
    /// RFC3339 engine time at which the request was received.
    #[serde(
        rename = "currentTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub current_time: Option<TimestampIso>,
    /// RFC3339 time after which all orders will be cancelled, unless the timer is extended or disabled first.
    #[serde(
        rename = "triggerTime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_time: Option<TimestampIso>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Parameters for the dead man's switch: resets/extends the countdown timer that cancels all account orders on expiry.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Duration in seconds to set/extend the timer; should be less than 86400 seconds. A timeout of `0` disables the mechanism.
    pub timeout: i64,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// "Dead Man's Switch": protects against network malfunction, extreme latency, or unexpected matching-engine downtime by starting a countdown timer in the trading engine that cancels all account orders on expiry. The client must keep sending requests to push back the trigger time, or send `timeout: 0` to disable the mechanism. Once the timer expires, all orders are cancelled and the feature stays disabled until the next request. Recommended use: a call every 15-30 seconds with `timeout: 60`. It is also recommended to disable the timer ahead of scheduled trading-engine maintenance, since a still-armed timer cancels all orders when the engine returns from downtime.
#[derive(Clone)]
pub struct CancelAllOrdersAfter {
    core: Arc<dyn CommandEndpoint>,
}

impl CancelAllOrdersAfter {
    pub fn new(core: Arc<dyn CommandEndpoint>) -> Self {
        Self { core }
    }

    /// "Dead Man's Switch": protects against network malfunction, extreme latency, or unexpected matching-engine downtime by starting a countdown timer in the trading engine that cancels all account orders on expiry. The client must keep sending requests to push back the trigger time, or send `timeout: 0` to disable the mechanism. Once the timer expires, all orders are cancelled and the feature stays disabled until the next request. Recommended use: a call every 15-30 seconds with `timeout: 60`. It is also recommended to disable the timer ahead of scheduled trading-engine maintenance, since a still-armed timer cancels all orders when the engine returns from downtime.
    ///
    /// See <https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/cancel_after>.
    pub async fn cancel_all_orders_after(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<CancelAllOrdersAfterResult> {
        let raw = self.cancel_all_orders_after_raw(request, options).await?;
        decode(raw)
    }

    /// `cancel_all_orders_after` without validation: the wire body as it came.
    pub async fn cancel_all_orders_after_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let call = CommandCall {
            path: "cancel_all_orders_after",
            request: Some(dump(&request)?),
            meta: &(),
            options,
        };
        self.core.request(call).await
    }
}
