// Generated by truewire — do not edit by hand.
import type { CallOptions, CommandEndpoint } from '@truewire/core'
import * as addOrder from './add_order.js'
import * as amendOrder from './amend_order.js'
import * as batchAdd from './batch_add.js'
import * as batchCancel from './batch_cancel.js'
import * as cancelAll from './cancel_all.js'
import * as cancelAllOrdersAfter from './cancel_all_orders_after.js'
import * as cancelOrder from './cancel_order.js'
import * as editOrder from './edit_order.js'

/**
 * Order entry over the private, token-authenticated Spot WebSocket v2 connection:
 * add/amend/edit orders, batch add/cancel, cancel-all, and the Dead Man's Switch
 * (cancel-all-orders-after).
 *
 * @see https://docs.kraken.com/exchange/api-reference/spot-websocket
 */
export class TradingWs {
  private readonly addOrder_: addOrder.AddOrder
  private readonly amendOrder_: amendOrder.AmendOrder
  private readonly batchAdd_: batchAdd.BatchAdd
  private readonly batchCancel_: batchCancel.BatchCancel
  private readonly cancelAll_: cancelAll.CancelAll
  private readonly cancelAllOrdersAfter_: cancelAllOrdersAfter.CancelAllOrdersAfter
  private readonly cancelOrder_: cancelOrder.CancelOrder
  private readonly editOrder_: editOrder.EditOrder

  constructor(readonly core: CommandEndpoint) {
    this.addOrder_ = new addOrder.AddOrder(core)
    this.amendOrder_ = new amendOrder.AmendOrder(core)
    this.batchAdd_ = new batchAdd.BatchAdd(core)
    this.batchCancel_ = new batchCancel.BatchCancel(core)
    this.cancelAll_ = new cancelAll.CancelAll(core)
    this.cancelAllOrdersAfter_ = new cancelAllOrdersAfter.CancelAllOrdersAfter(core)
    this.cancelOrder_ = new cancelOrder.CancelOrder(core)
    this.editOrder_ = new editOrder.EditOrder(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  addOrder(request: addOrder.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Sends a single, new order into the exchange. A range of order types, Time-In-Force (TIF) settings and order flags can be specified. For triggered order types (`stop-loss`, `take-profit`, `trailing-stop`), `triggers` carries the price-tracking and trigger-threshold parameters. For One-Triggers-Other (OTO) orders, `conditional` carries the parameters for a secondary close order attached to the primary order.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/add_order
   */
  addOrder(request: addOrder.Request, options?: CallOptions): Promise<addOrder.AddOrderResult>
  addOrder(request: addOrder.Request, options?: CallOptions): Promise<addOrder.AddOrderResult> {
    return this.addOrder_.addOrder(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  amendOrder(request: amendOrder.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Modifies the parameters of a live order in-place, without cancelling and re-creating it: order identifiers stay the same, queue priority in the order book is maintained where possible, and if the amendment reduces the order quantity below the already-filled quantity, the remaining quantity is cancelled. Supersedes the legacy `edit_order` (cancel-replace), which loses queue priority and has several unsupported-order-shape caveats.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/amend_order
   */
  amendOrder(request?: amendOrder.Request, options?: CallOptions): Promise<amendOrder.AmendOrderResult>
  amendOrder(request?: amendOrder.Request, options?: CallOptions): Promise<amendOrder.AmendOrderResult> {
    return this.amendOrder_.amendOrder(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  batchAdd(request: batchAdd.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Sends a batch of 2-15 orders in a single request, all sharing one pair. Validation runs against the whole batch before submission to the engine -- if any order fails validation, the whole batch is rejected. Once submitted, an order failing a pre-match check (e.g. insufficient funding) is rejected individually and the rest of the batch is processed.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/batch_add
   */
  batchAdd(request: batchAdd.Request, options?: CallOptions): Promise<batchAdd.BatchAddResult>
  batchAdd(request: batchAdd.Request, options?: CallOptions): Promise<batchAdd.BatchAddResult> {
    return this.batchAdd_.batchAdd(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  batchCancel(request: batchCancel.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Cancels multiple orders (minimum 2, maximum 50) in a single request, identified by a mix of client or Kraken identifiers.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/batch_cancel
   */
  batchCancel(request: batchCancel.Request, options?: CallOptions): Promise<batchCancel.BatchCancelReply>
  batchCancel(request: batchCancel.Request, options?: CallOptions): Promise<batchCancel.BatchCancelReply> {
    return this.batchCancel_.batchCancel(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  cancelAll(request: cancelAll.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Cancels all open orders on the account, including untriggered orders and orders resting in the book. The details of each individual cancelled order are also streamed on the `executions` channel.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/cancel_all
   */
  cancelAll(request?: cancelAll.Request, options?: CallOptions): Promise<cancelAll.CancelAllResult>
  cancelAll(request?: cancelAll.Request, options?: CallOptions): Promise<cancelAll.CancelAllResult> {
    return this.cancelAll_.cancelAll(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  cancelAllOrdersAfter(request: cancelAllOrdersAfter.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * "Dead Man's Switch": protects against network malfunction, extreme latency, or unexpected matching-engine downtime by starting a countdown timer in the trading engine that cancels all account orders on expiry. The client must keep sending requests to push back the trigger time, or send `timeout: 0` to disable the mechanism. Once the timer expires, all orders are cancelled and the feature stays disabled until the next request. Recommended use: a call every 15-30 seconds with `timeout: 60`. It is also recommended to disable the timer ahead of scheduled trading-engine maintenance, since a still-armed timer cancels all orders when the engine returns from downtime.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/cancel_after
   */
  cancelAllOrdersAfter(request: cancelAllOrdersAfter.Request, options?: CallOptions): Promise<cancelAllOrdersAfter.CancelAllOrdersAfterResult>
  cancelAllOrdersAfter(request: cancelAllOrdersAfter.Request, options?: CallOptions): Promise<cancelAllOrdersAfter.CancelAllOrdersAfterResult> {
    return this.cancelAllOrdersAfter_.cancelAllOrdersAfter(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  cancelOrder(request: cancelOrder.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Cancels one or more open orders in a single request, identified by a range of client or Kraken identifiers. The details of each cancelled order are also streamed on the `executions` channel.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/cancel_order
   */
  cancelOrder(request?: cancelOrder.Request, options?: CallOptions): Promise<cancelOrder.CancelOrderResult>
  cancelOrder(request?: cancelOrder.Request, options?: CallOptions): Promise<cancelOrder.CancelOrderResult> {
    return this.cancelOrder_.cancelOrder(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  editOrder(request: editOrder.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Legacy cancel-replace edit of a live order's parameters: the original order is cancelled and a new order is created with the adjusted parameters, returning a new `order_id`. Superseded by `amend_order`, which resolves this endpoint's caveats and performs better: triggered stop-loss/take-profit orders are not supported; orders with attached conditional close terms are not supported; an edit whose executed volume exceeds the newly supplied volume is rejected; `cl_ord_id` is not supported; existing executions stay associated with the original order rather than copying to the edited one; and queue position is not maintained.
   *
   * @see https://docs.kraken.com/exchange/api-reference/spot-websocket-v2/edit_order
   */
  editOrder(request: editOrder.Request, options?: CallOptions): Promise<editOrder.EditOrderResult>
  editOrder(request: editOrder.Request, options?: CallOptions): Promise<editOrder.EditOrderResult> {
    return this.editOrder_.editOrder(request, options)
  }
}
