# Generated by truewire — do not edit by hand.
from decimal import Decimal
from typing_extensions import Literal, NotRequired, TypedDict
from kraken.core.endpoint.rpc import RpcEndpoint


class OrderBook(TypedDict):
  """One pair's L2 order book."""

  asks: NotRequired[list[tuple[Decimal, Decimal, int]]]
  """Ask side, best first."""
  bids: NotRequired[list[tuple[Decimal, Decimal, int]]]
  """Bid side, best first."""


class Request(TypedDict):
  pair: str
  """Asset pair to get data for."""
  assetVersion: NotRequired[Literal[1]]
  """Controls whether response keys use Kraken's internal names or display names. Omitted (default): internal names are used. `assetVersion=1`: display names are used. Only `assetVersion=1` is currently supported."""
  count: NotRequired[int]
  """Maximum number of asks/bids."""
  asset_class: NotRequired[Literal['tokenized_asset']]
  """This parameter is required on requests for non-crypto pairs, i.e. use `tokenized_asset` for xstocks."""


Response = dict[str, OrderBook]


class Depth(RpcEndpoint):
  """Returns level 2 (L2) order book, which describes the individual price levels in the book with aggregated order quantities at each level."""

  async def depth(
    self,
    pair: str,
    *,
    asset_version: Literal[1] | None = None,
    count: int | None = None,
    asset_class: Literal['tokenized_asset'] | None = None,
    validate: bool | None = None,
  ) -> Response:
    """Returns level 2 (L2) order book, which describes the individual price levels in the book with aggregated order quantities at each level.

    Args:
      pair: Asset pair to get data for.
      asset_version: Controls whether response keys use Kraken's internal names or display names. Omitted (default): internal names are used. `assetVersion=1`: display names are used. Only `assetVersion=1` is currently supported.
      count: Maximum number of asks/bids.
      asset_class: This parameter is required on requests for non-crypto pairs, i.e. use `tokenized_asset` for xstocks.
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.kraken.com/api-reference/market-data/get-order-book)
    """
    request: Request = Request(pair=pair)
    if asset_version is not None:
      request['assetVersion'] = asset_version
    if count is not None:
      request['count'] = count
    if asset_class is not None:
      request['asset_class'] = asset_class
    return await self.request(
      request,
      method='GET',
      path='/0/public/Depth',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=Response,
    )
