// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type Decimal, type HttpEndpoint, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'

/** One pair's L2 order book. */
export interface OrderBook {
  /** Ask side, best first. */
  asks?: (readonly [Decimal, Decimal, number])[]
  /** Bid side, best first. */
  bids?: (readonly [Decimal, Decimal, number])[]
}

export const OrderBook: Codec<OrderBook> = t.object({
  asks: t.optional(t.array(t.tuple([t.decimal, t.decimal, t.integer]))),
  bids: t.optional(t.array(t.tuple([t.decimal, t.decimal, t.integer]))),
})

export interface Request {
  /** Asset pair to get data for. */
  pair: string
  /** Controls whether response keys use Kraken's internal names or display names. Omitted (default): internal names are used. `assetVersion=1`: display names are used. Only `assetVersion=1` is currently supported. */
  assetVersion?: 1
  /** Maximum number of asks/bids. */
  count?: number
  /** This parameter is required on requests for non-crypto pairs, i.e. use `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
}

export const Request: Codec<Request> = t.object({
  pair: t.string,
  assetVersion: t.optional(t.literal(1)),
  count: t.optional(t.integer),
  asset_class: t.optional(t.literal('tokenized_asset')),
})

export type Response = Record<string, OrderBook>

export const Response: Codec<Response> = t.record(OrderBook)

/** Returns level 2 (L2) order book, which describes the individual price levels in the book with aggregated order quantities at each level. */
export class Depth {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  depth(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Returns level 2 (L2) order book, which describes the individual price levels in the book with aggregated order quantities at each level.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-order-book
   */
  depth(request: Request, options?: CallOptions): Promise<Response>
  async depth(request: Request, options?: CallOptions): Promise<Response> {
    return this.core.request({
      method: 'GET',
      path: '/0/public/Depth',
      request,
      requestCodec: Request,
      responseCodec: Response,
      meta: {},
      ...options,
    })
  }
}
