// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'
import * as assetPairs from './asset_pairs.js'
import * as assets from './assets.js'
import * as depth from './depth.js'
import * as groupedBook from './grouped_book.js'
import * as ohlc from './ohlc.js'
import * as postTrade from './post_trade.js'
import * as preTrade from './pre_trade.js'
import * as spread from './spread.js'
import * as systemStatus from './system_status.js'
import * as ticker from './ticker.js'
import * as time from './time.js'
import * as trades from './trades.js'

/**
 * Public, unauthenticated market data: server time, system status, tradable asset
 * pairs, asset info, order book depth, recent trades/spreads, OHLC candles, ticker
 * snapshots, and pre-/post-trade transparency reports.
 *
 * @see https://docs.kraken.com/api-reference/market-data
 */
export class MarketData {
  private readonly assetPairs_: assetPairs.AssetPairs
  private readonly assets_: assets.Assets
  private readonly depth_: depth.Depth
  private readonly groupedBook_: groupedBook.GroupedBook
  private readonly ohlc_: ohlc.Ohlc
  private readonly postTrade_: postTrade.PostTrade
  private readonly preTrade_: preTrade.PreTrade
  private readonly spread_: spread.Spread
  private readonly systemStatus_: systemStatus.SystemStatusEndpoint
  private readonly ticker_: ticker.Ticker
  private readonly time_: time.Time
  private readonly trades_: trades.Trades

  constructor(readonly core: HttpEndpoint<SpotMeta>) {
    this.assetPairs_ = new assetPairs.AssetPairs(core)
    this.assets_ = new assets.Assets(core)
    this.depth_ = new depth.Depth(core)
    this.groupedBook_ = new groupedBook.GroupedBook(core)
    this.ohlc_ = new ohlc.Ohlc(core)
    this.postTrade_ = new postTrade.PostTrade(core)
    this.preTrade_ = new preTrade.PreTrade(core)
    this.spread_ = new spread.Spread(core)
    this.systemStatus_ = new systemStatus.SystemStatusEndpoint(core)
    this.ticker_ = new ticker.Ticker(core)
    this.time_ = new time.Time(core)
    this.trades_ = new trades.Trades(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  assetPairs(request: assetPairs.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get tradable asset pairs.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-tradable-asset-pairs
   */
  assetPairs(request?: assetPairs.Request, options?: CallOptions): Promise<assetPairs.Response>
  assetPairs(request?: assetPairs.Request, options?: CallOptions): Promise<assetPairs.Response> {
    return this.assetPairs_.assetPairs(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  assets(request: assets.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get information about the assets that are available for deposit, withdrawal, trading and earn.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-asset-info
   */
  assets(request?: assets.Request, options?: CallOptions): Promise<assets.Response>
  assets(request?: assets.Request, options?: CallOptions): Promise<assets.Response> {
    return this.assets_.assets(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  depth(request: depth.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Returns level 2 (L2) order book, which describes the individual price levels in the book with aggregated order quantities at each level.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-order-book
   */
  depth(request: depth.Request, options?: CallOptions): Promise<depth.Response>
  depth(request: depth.Request, options?: CallOptions): Promise<depth.Response> {
    return this.depth_.depth(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  groupedBook(request: groupedBook.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Aggregates the volume in the order book over a specified tick range, for a summary of liquidity deep into the book (useful for UI display). Bids and asks between grouped price levels are accumulated to the nearest passive level (asks rounded up, bids down).
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-grouped-order-book
   */
  groupedBook(request: groupedBook.Request, options?: CallOptions): Promise<groupedBook.GroupedOrderBook>
  groupedBook(request: groupedBook.Request, options?: CallOptions): Promise<groupedBook.GroupedOrderBook> {
    return this.groupedBook_.groupedBook(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  ohlc(request: ohlc.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Retrieve OHLC market data. The last entry in the OHLC array is for the current, not-yet-committed timeframe, and will always be present, regardless of the value of `since`. Returns up to 720 of the most recent entries (older data cannot be retrieved, regardless of the value of `since`).
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-ohlc-data
   */
  ohlc(request: ohlc.Request, options?: CallOptions): Promise<ohlc.OhlcResult>
  ohlc(request: ohlc.Request, options?: CallOptions): Promise<ohlc.OhlcResult> {
    return this.ohlc_.ohlc(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  postTrade(request: postTrade.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Returns a list of trades on the spot exchange. If no filter parameters are specified, the last 1000 trades for all pairs are received.
   *
   * @see https://docs.kraken.com/api-reference/transparency/post-trade-data
   */
  postTrade(request?: postTrade.Request, options?: CallOptions): Promise<postTrade.PostTradeResult>
  postTrade(request?: postTrade.Request, options?: CallOptions): Promise<postTrade.PostTradeResult> {
    return this.postTrade_.postTrade(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  preTrade(request: preTrade.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Returns the price levels in the order book with aggregated order quantities at each price level. The top 10 levels are returned for each trading pair.
   *
   * @see https://docs.kraken.com/api-reference/transparency/pre-trade-data
   */
  preTrade(request: preTrade.Request, options?: CallOptions): Promise<preTrade.PreTradeBook>
  preTrade(request: preTrade.Request, options?: CallOptions): Promise<preTrade.PreTradeBook> {
    return this.preTrade_.preTrade(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  spread(request: spread.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Returns the last ~200 top-of-book spreads for a given pair.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-recent-spreads
   */
  spread(request: spread.Request, options?: CallOptions): Promise<spread.SpreadResult>
  spread(request: spread.Request, options?: CallOptions): Promise<spread.SpreadResult> {
    return this.spread_.spread(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  systemStatus(options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get the current system status or trading mode.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-system-status
   */
  systemStatus(options?: CallOptions): Promise<systemStatus.SystemStatus>
  systemStatus(options?: CallOptions): Promise<systemStatus.SystemStatus> {
    return this.systemStatus_.systemStatus(options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  ticker(request: ticker.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get ticker information for all or requested markets. Today's prices start at midnight UTC. Leaving the `pair` parameter blank returns tickers for all tradeable assets on Kraken.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-ticker-information
   */
  ticker(request?: ticker.Request, options?: CallOptions): Promise<ticker.Response>
  ticker(request?: ticker.Request, options?: CallOptions): Promise<ticker.Response> {
    return this.ticker_.ticker(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  time(options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Get the server's time.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-server-time
   */
  time(options?: CallOptions): Promise<time.ServerTime>
  time(options?: CallOptions): Promise<time.ServerTime> {
    return this.time_.time(options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  trades(request: trades.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Returns the last 1000 trades by default.
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-recent-trades
   */
  trades(request: trades.Request, options?: CallOptions): Promise<trades.TradesResult>
  trades(request: trades.Request, options?: CallOptions): Promise<trades.TradesResult> {
    return this.trades_.trades(request, options)
  }
}
