// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampSeconds, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'

/** OHLC candles, keyed by pair, plus the polling cursor. */
export interface OhlcResult {
  /** ID to be used as `since` when polling for new, committed OHLC data. */
  last?: number
}

export const OhlcResult: Codec<OhlcResult> = t.object({
  last: t.optional(t.integer),
})

export interface Request {
  /** Asset pair to get data for. */
  pair: string
  /** Controls whether response keys use Kraken's internal names or display names. Omitted (default): internal names are used. `assetVersion=1`: display names are used. Only `assetVersion=1` is currently supported. */
  assetVersion?: 1
  /** Time frame interval in minutes. */
  interval?: 1 | 5 | 15 | 30 | 60 | 240 | 1440 | 10080 | 21600
  /** Return OHLC entries since the given timestamp (intended for incremental updates). */
  since?: TimestampSeconds
  /** This parameter is required on requests for non-crypto pairs, i.e. use `tokenized_asset` for xstocks. */
  asset_class?: 'tokenized_asset'
}

export const Request: Codec<Request> = t.object({
  pair: t.string,
  assetVersion: t.optional(t.literal(1)),
  interval: t.optional(t.literal(1, 5, 15, 30, 60, 240, 1440, 10080, 21600)),
  since: t.optional(t.epochSeconds),
  asset_class: t.optional(t.literal('tokenized_asset')),
})

/** Retrieve OHLC market data. The last entry in the OHLC array is for the current, not-yet-committed timeframe, and will always be present, regardless of the value of `since`. Returns up to 720 of the most recent entries (older data cannot be retrieved, regardless of the value of `since`). */
export class Ohlc {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  ohlc(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Retrieve OHLC market data. The last entry in the OHLC array is for the current, not-yet-committed timeframe, and will always be present, regardless of the value of `since`. Returns up to 720 of the most recent entries (older data cannot be retrieved, regardless of the value of `since`).
   *
   * @see https://docs.kraken.com/api-reference/market-data/get-ohlc-data
   */
  ohlc(request: Request, options?: CallOptions): Promise<OhlcResult>
  async ohlc(request: Request, options?: CallOptions): Promise<OhlcResult> {
    return this.core.request({
      method: 'GET',
      path: '/0/public/OHLC',
      request,
      requestCodec: Request,
      responseCodec: OhlcResult,
      meta: {},
      ...options,
    })
  }
}
