// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'

/** One executed trade. */
export interface PostTradeEntry {
  /** Kraken unique trade identifier. */
  trade_id?: string
  /** Trade price excluding fees and commissions. */
  price?: string
  /** Unconsolidated trade quantity from execution. */
  quantity?: string
  /** The symbol of the currency pair. */
  symbol?: string
  /** The full description of the currency pair. */
  description?: string
  /** ISO 4217 currency code for the base asset. */
  base_asset?: string
  /** Indicates that the quantity is expressed in nominal units. */
  base_notation?: 'UNIT'
  /** ISO 4217 currency in which the trading price is expressed. */
  quote_asset?: string
  /** Indicates that the price is expressed in monetary value. */
  quote_notation?: 'MONE'
  /** ISO 10383 Market Identifier Code (MIC) of the trading platform where the trade was executed. */
  trade_venue?: string
  /** Timestamp the trade was matched in the engine, to microsecond precision. */
  trade_ts?: TimestampIso
  /** ISO 10383 Market Identifier Code (MIC) of the trading platform where the trade was published. */
  publication_venue?: string
  /** Timestamp the trade was published to market data streams. */
  publication_ts?: TimestampIso
}

export const PostTradeEntry: Codec<PostTradeEntry> = t.object({
  trade_id: t.optional(t.string),
  price: t.optional(t.string),
  quantity: t.optional(t.string),
  symbol: t.optional(t.string),
  description: t.optional(t.string),
  base_asset: t.optional(t.string),
  base_notation: t.optional(t.literal('UNIT')),
  quote_asset: t.optional(t.string),
  quote_notation: t.optional(t.literal('MONE')),
  trade_venue: t.optional(t.string),
  trade_ts: t.optional(t.dateTime),
  publication_venue: t.optional(t.string),
  publication_ts: t.optional(t.dateTime),
})

export interface Request {
  /** Filter the results to the currency pair. */
  symbol?: string
  /** Filter the results to include the trades after this timestamp. */
  from_ts?: TimestampIso
  /** Filter the results to include the trades before or at this timestamp. */
  to_ts?: TimestampIso
  /** The maximum number of trades to return. */
  count?: number
}

export const Request: Codec<Request> = t.object({
  symbol: t.optional(t.string),
  from_ts: t.optional(t.dateTime),
  to_ts: t.optional(t.dateTime),
  count: t.optional(t.integer),
})

/** A list of executed trades in ascending timestamp order. */
export interface PostTradeResult {
  /** Timestamp of the latest trade in the list, or an empty string when the result contains no trades. Can be used as the `from_ts` parameter when requesting the next batch of trades. */
  last_ts?: TimestampIso | ''
  /** The number of trades returned. */
  count?: number
  /** The trades, in ascending timestamp order. */
  trades?: PostTradeEntry[]
}

export const PostTradeResult: Codec<PostTradeResult> = t.object({
  last_ts: t.optional(t.union(t.dateTime, t.literal(''))),
  count: t.optional(t.integer),
  trades: t.optional(t.array(PostTradeEntry)),
})

/** Returns a list of trades on the spot exchange. If no filter parameters are specified, the last 1000 trades for all pairs are received. */
export class PostTrade {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  postTrade(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Returns a list of trades on the spot exchange. If no filter parameters are specified, the last 1000 trades for all pairs are received.
   *
   * @see https://docs.kraken.com/api-reference/transparency/post-trade-data
   */
  postTrade(request?: Request, options?: CallOptions): Promise<PostTradeResult>
  async postTrade(request?: Request, options?: CallOptions): Promise<PostTradeResult> {
    return this.core.request({
      method: 'GET',
      path: '/0/public/PostTrade',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: PostTradeResult,
      meta: {},
      ...options,
    })
  }
}
