// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'

/** One aggregated ask price level. */
export interface PreTradeAskLevel {
  /** Indicates this level is an offer. */
  side?: 'SELL'
  /** Price level in the Central Limit Order Book (CLOB). */
  price?: string
  /** The aggregated quantity at the price level. */
  qty?: string
  /** The number of orders in the price level. */
  count?: number
  /** Timestamp the order at this price level was submitted. */
  submission_ts?: TimestampIso
  /** Timestamp the price level was last updated and published. */
  publication_ts?: TimestampIso
}

export const PreTradeAskLevel: Codec<PreTradeAskLevel> = t.object({
  side: t.optional(t.literal('SELL')),
  price: t.optional(t.string),
  qty: t.optional(t.string),
  count: t.optional(t.integer),
  submission_ts: t.optional(t.dateTime),
  publication_ts: t.optional(t.dateTime),
})

/** One aggregated bid price level. */
export interface PreTradeBidLevel {
  /** Indicates this level is a bid. */
  side?: 'BUY'
  /** Price level in the Central Limit Order Book (CLOB). */
  price?: string
  /** The aggregated quantity at the price level. */
  qty?: string
  /** The number of orders in the price level. */
  count?: number
  /** Timestamp the order at this price level was submitted. */
  submission_ts?: TimestampIso
  /** Timestamp the price level was last updated and published. */
  publication_ts?: TimestampIso
}

export const PreTradeBidLevel: Codec<PreTradeBidLevel> = t.object({
  side: t.optional(t.literal('BUY')),
  price: t.optional(t.string),
  qty: t.optional(t.string),
  count: t.optional(t.integer),
  submission_ts: t.optional(t.dateTime),
  publication_ts: t.optional(t.dateTime),
})

export interface Request {
  /** A list of symbols for the currency pairs. */
  symbol: string
}

export const Request: Codec<Request> = t.object({
  symbol: t.string,
})

/** The top-10-level aggregated order book for a pair, plus reference/venue metadata. */
export interface PreTradeBook {
  /** The symbol of the currency pair. */
  symbol?: string
  /** The full description of the currency pair. */
  description?: string
  /** ISO 4217 currency code for the base asset. */
  base_asset?: string
  /** Digital Token Identifier (DTI) code for the base asset. */
  base_dti_code?: string
  /** DTI short name for the base asset. */
  base_dti_short_name?: string
  /** Digital Token Identifier (DTI) code for the quote asset. */
  quote_dti_code?: string
  /** DTI short name for the quote asset. */
  quote_dti_short_name?: string
  /** Indicates how the base quantity is expressed: `UNIT` (nominal units) or `NOML` (notional value). */
  base_notation?: 'UNIT' | 'NOML'
  /** ISO 4217 currency in which the trading price is expressed. */
  quote_asset?: string
  /** Indicates that the price is expressed in monetary value. */
  quote_notation?: 'MONE'
  /** ISO 10383 Market Identifier Code (MIC) of the trading platform where the order was submitted. */
  venue?: 'PGSL'
  /** Indicates the order system is a Central Limit Order Book. */
  system?: 'CLOB'
  /** Top-10 aggregated bid levels. */
  bids?: PreTradeBidLevel[]
  /** Top-10 aggregated ask levels. */
  asks?: PreTradeAskLevel[]
}

export const PreTradeBook: Codec<PreTradeBook> = t.object({
  symbol: t.optional(t.string),
  description: t.optional(t.string),
  base_asset: t.optional(t.string),
  base_dti_code: t.optional(t.string),
  base_dti_short_name: t.optional(t.string),
  quote_dti_code: t.optional(t.string),
  quote_dti_short_name: t.optional(t.string),
  base_notation: t.optional(t.literal('UNIT', 'NOML')),
  quote_asset: t.optional(t.string),
  quote_notation: t.optional(t.literal('MONE')),
  venue: t.optional(t.literal('PGSL')),
  system: t.optional(t.literal('CLOB')),
  bids: t.optional(t.array(PreTradeBidLevel)),
  asks: t.optional(t.array(PreTradeAskLevel)),
})

/** Returns the price levels in the order book with aggregated order quantities at each price level. The top 10 levels are returned for each trading pair. */
export class PreTrade {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  preTrade(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Returns the price levels in the order book with aggregated order quantities at each price level. The top 10 levels are returned for each trading pair.
   *
   * @see https://docs.kraken.com/api-reference/transparency/pre-trade-data
   */
  preTrade(request: Request, options?: CallOptions): Promise<PreTradeBook>
  async preTrade(request: Request, options?: CallOptions): Promise<PreTradeBook> {
    return this.core.request({
      method: 'GET',
      path: '/0/public/PreTrade',
      request,
      requestCodec: Request,
      responseCodec: PreTradeBook,
      meta: {},
      ...options,
    })
  }
}
