# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from typing_extensions import Literal, NotRequired, TypedDict
from kraken.core.endpoint.rpc import RpcEndpoint


class SystemStatus(TypedDict):
  """The exchange's current operational status."""

  status: NotRequired[Literal['online', 'maintenance', 'cancel_only', 'post_only']]
  """Current system status: `online` (operating normally, all order types accepted), `maintenance` (offline, no new orders or cancellations), `cancel_only` (resting orders can be cancelled but none submitted, no trades occur), or `post_only` (only post-only limit orders accepted, existing orders may still be cancelled, no trades occur)."""
  timestamp: NotRequired[TimestampIso]
  """Current timestamp (RFC3339)."""


class SystemStatusEndpoint(RpcEndpoint):
  """Get the current system status or trading mode."""

  async def system_status(self, *, validate: bool | None = None) -> SystemStatus:
    """Get the current system status or trading mode.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted.

    References:
      - [Official docs](https://docs.kraken.com/api-reference/market-data/get-system-status)
    """
    return await self.request(
      None,
      method='GET',
      path='/0/public/SystemStatus',
      meta={},
      validate=validate,
      response_type=SystemStatus,
    )
