// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file demo/base/v1/coin.proto (package demo.base.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file demo/base/v1/coin.proto.
 */
export const file_demo_base_v1_coin: GenFile = /*@__PURE__*/
  fileDesc("ChdkZW1vL2Jhc2UvdjEvY29pbi5wcm90bxIMZGVtby5iYXNlLnYxIiUKBENvaW4SDQoFZGVub20YASABKAkSDgoGYW1vdW50GAIgASgJQh9aHWdpdGh1Yi5jb20vZXhhbXBsZS9kZW1vL3R5cGVzYgZwcm90bzM");

/**
 * Coin is a denomination and an amount.
 *
 * @generated from message demo.base.v1.Coin
 */
export type Coin = Message<"demo.base.v1.Coin"> & {
  /**
   * @generated from field: string denom = 1;
   */
  denom: string;

  /**
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message demo.base.v1.Coin.
 * Use `create(CoinSchema)` to create a new message.
 */
export const CoinSchema: GenMessage<Coin> = /*@__PURE__*/
  messageDesc(file_demo_base_v1_coin, 0);

