//! Generated by truewire — do not edit by hand.
//!
//! Every generated method reachable by its dotted function path: the lookup a replay test, a CLI or anything else driving the client from data uses instead of reflection.

use truewire_core::{decode, dump, serde_json, CallOptions, Error, Result, Stream};

use crate::Kraken;

impl Kraken {
    /// Call the `rpc` endpoint `function` names (`spot.account.account_transfer`) with a wire request: decoded into its `Request`, sent, and the typed response dumped back to a wire value.
    #[doc(hidden)]
    pub async fn call(
        &self,
        function: &str,
        request: serde_json::Value,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        match function {
            "spot.account.account_transfer" => {
                let request = decode(request)?;
                let response = self.spot.account.account_transfer(request, options).await?;
                dump(&response)
            }
            "spot.account.add_export" => {
                let request = decode(request)?;
                let response = self.spot.account.add_export(request, options).await?;
                dump(&response)
            }
            "spot.account.api_key_info" => {
                let request = decode(request)?;
                let response = self.spot.account.api_key_info(request, options).await?;
                dump(&response)
            }
            "spot.account.balance" => {
                let request = decode(request)?;
                let response = self.spot.account.balance(request, options).await?;
                dump(&response)
            }
            "spot.account.balance_ex" => {
                let request = decode(request)?;
                let response = self.spot.account.balance_ex(request, options).await?;
                dump(&response)
            }
            "spot.account.closed_orders" => {
                let request = decode(request)?;
                let response = self.spot.account.closed_orders(request, options).await?;
                dump(&response)
            }
            "spot.account.create_subaccount" => {
                let request = decode(request)?;
                let response = self
                    .spot
                    .account
                    .create_subaccount(request, options)
                    .await?;
                dump(&response)
            }
            "spot.account.credit_lines" => {
                let request = decode(request)?;
                let response = self.spot.account.credit_lines(request, options).await?;
                dump(&response)
            }
            "spot.account.export_status" => {
                let request = decode(request)?;
                let response = self.spot.account.export_status(request, options).await?;
                dump(&response)
            }
            "spot.account.ledgers" => {
                let request = decode(request)?;
                let response = self.spot.account.ledgers(request, options).await?;
                dump(&response)
            }
            "spot.account.open_orders" => {
                let request = decode(request)?;
                let response = self.spot.account.open_orders(request, options).await?;
                dump(&response)
            }
            "spot.account.open_positions" => {
                let request = decode(request)?;
                let response = self.spot.account.open_positions(request, options).await?;
                dump(&response)
            }
            "spot.account.order_amends" => {
                let request = decode(request)?;
                let response = self.spot.account.order_amends(request, options).await?;
                dump(&response)
            }
            "spot.account.query_ledgers" => {
                let request = decode(request)?;
                let response = self.spot.account.query_ledgers(request, options).await?;
                dump(&response)
            }
            "spot.account.query_orders" => {
                let request = decode(request)?;
                let response = self.spot.account.query_orders(request, options).await?;
                dump(&response)
            }
            "spot.account.query_trades" => {
                let request = decode(request)?;
                let response = self.spot.account.query_trades(request, options).await?;
                dump(&response)
            }
            "spot.account.remove_export" => {
                let request = decode(request)?;
                let response = self.spot.account.remove_export(request, options).await?;
                dump(&response)
            }
            "spot.account.trade_balance" => {
                let request = decode(request)?;
                let response = self.spot.account.trade_balance(request, options).await?;
                dump(&response)
            }
            "spot.account.trade_volume" => {
                let request = decode(request)?;
                let response = self.spot.account.trade_volume(request, options).await?;
                dump(&response)
            }
            "spot.account.trades_history" => {
                let request = decode(request)?;
                let response = self.spot.account.trades_history(request, options).await?;
                dump(&response)
            }
            "spot.earn.allocate" => {
                let request = decode(request)?;
                let response = self.spot.earn.allocate(request, options).await?;
                dump(&response)
            }
            "spot.earn.allocate_status" => {
                let request = decode(request)?;
                let response = self.spot.earn.allocate_status(request, options).await?;
                dump(&response)
            }
            "spot.earn.allocations" => {
                let request = decode(request)?;
                let response = self.spot.earn.allocations(request, options).await?;
                dump(&response)
            }
            "spot.earn.deallocate" => {
                let request = decode(request)?;
                let response = self.spot.earn.deallocate(request, options).await?;
                dump(&response)
            }
            "spot.earn.deallocate_status" => {
                let request = decode(request)?;
                let response = self.spot.earn.deallocate_status(request, options).await?;
                dump(&response)
            }
            "spot.earn.strategies" => {
                let request = decode(request)?;
                let response = self.spot.earn.strategies(request, options).await?;
                dump(&response)
            }
            "spot.funding.deposit_addresses" => {
                let request = decode(request)?;
                let response = self
                    .spot
                    .funding
                    .deposit_addresses(request, options)
                    .await?;
                dump(&response)
            }
            "spot.funding.deposit_methods" => {
                let request = decode(request)?;
                let response = self.spot.funding.deposit_methods(request, options).await?;
                dump(&response)
            }
            "spot.funding.deposit_status" => {
                let request = decode(request)?;
                let response = self.spot.funding.deposit_status(request, options).await?;
                dump(&response)
            }
            "spot.funding.wallet_transfer" => {
                let request = decode(request)?;
                let response = self.spot.funding.wallet_transfer(request, options).await?;
                dump(&response)
            }
            "spot.funding.withdraw" => {
                let request = decode(request)?;
                let response = self.spot.funding.withdraw(request, options).await?;
                dump(&response)
            }
            "spot.funding.withdraw_addresses" => {
                let request = decode(request)?;
                let response = self
                    .spot
                    .funding
                    .withdraw_addresses(request, options)
                    .await?;
                dump(&response)
            }
            "spot.funding.withdraw_cancel" => {
                let request = decode(request)?;
                let response = self.spot.funding.withdraw_cancel(request, options).await?;
                dump(&response)
            }
            "spot.funding.withdraw_info" => {
                let request = decode(request)?;
                let response = self.spot.funding.withdraw_info(request, options).await?;
                dump(&response)
            }
            "spot.funding.withdraw_methods" => {
                let request = decode(request)?;
                let response = self.spot.funding.withdraw_methods(request, options).await?;
                dump(&response)
            }
            "spot.funding.withdraw_status" => {
                let request = decode(request)?;
                let response = self.spot.funding.withdraw_status(request, options).await?;
                dump(&response)
            }
            "spot.market_data.asset_pairs" => {
                let request = decode(request)?;
                let response = self.spot.market_data.asset_pairs(request, options).await?;
                dump(&response)
            }
            "spot.market_data.assets" => {
                let request = decode(request)?;
                let response = self.spot.market_data.assets(request, options).await?;
                dump(&response)
            }
            "spot.market_data.depth" => {
                let request = decode(request)?;
                let response = self.spot.market_data.depth(request, options).await?;
                dump(&response)
            }
            "spot.market_data.grouped_book" => {
                let request = decode(request)?;
                let response = self.spot.market_data.grouped_book(request, options).await?;
                dump(&response)
            }
            "spot.market_data.ohlc" => {
                let request = decode(request)?;
                let response = self.spot.market_data.ohlc(request, options).await?;
                dump(&response)
            }
            "spot.market_data.post_trade" => {
                let request = decode(request)?;
                let response = self.spot.market_data.post_trade(request, options).await?;
                dump(&response)
            }
            "spot.market_data.pre_trade" => {
                let request = decode(request)?;
                let response = self.spot.market_data.pre_trade(request, options).await?;
                dump(&response)
            }
            "spot.market_data.spread" => {
                let request = decode(request)?;
                let response = self.spot.market_data.spread(request, options).await?;
                dump(&response)
            }
            "spot.market_data.system_status" => {
                let _ = request;
                let response = self.spot.market_data.system_status(options).await?;
                dump(&response)
            }
            "spot.market_data.ticker" => {
                let request = decode(request)?;
                let response = self.spot.market_data.ticker(request, options).await?;
                dump(&response)
            }
            "spot.market_data.time" => {
                let _ = request;
                let response = self.spot.market_data.time(options).await?;
                dump(&response)
            }
            "spot.market_data.trades" => {
                let request = decode(request)?;
                let response = self.spot.market_data.trades(request, options).await?;
                dump(&response)
            }
            "spot.trading.add_order" => {
                let request = decode(request)?;
                let response = self.spot.trading.add_order(request, options).await?;
                dump(&response)
            }
            "spot.trading.add_order_batch" => {
                let request = decode(request)?;
                let response = self.spot.trading.add_order_batch(request, options).await?;
                dump(&response)
            }
            "spot.trading.amend_order" => {
                let request = decode(request)?;
                let response = self.spot.trading.amend_order(request, options).await?;
                dump(&response)
            }
            "spot.trading.cancel_all" => {
                let _ = request;
                let response = self.spot.trading.cancel_all(options).await?;
                dump(&response)
            }
            "spot.trading.cancel_all_orders_after" => {
                let request = decode(request)?;
                let response = self
                    .spot
                    .trading
                    .cancel_all_orders_after(request, options)
                    .await?;
                dump(&response)
            }
            "spot.trading.cancel_order" => {
                let request = decode(request)?;
                let response = self.spot.trading.cancel_order(request, options).await?;
                dump(&response)
            }
            "spot.trading.cancel_order_batch" => {
                let request = decode(request)?;
                let response = self
                    .spot
                    .trading
                    .cancel_order_batch(request, options)
                    .await?;
                dump(&response)
            }
            "spot.trading.edit_order" => {
                let request = decode(request)?;
                let response = self.spot.trading.edit_order(request, options).await?;
                dump(&response)
            }
            "spot.trading.get_websockets_token" => {
                let _ = request;
                let response = self.spot.trading.get_websockets_token(options).await?;
                dump(&response)
            }
            "streams.market_data.ping" => {
                let _ = request;
                let response = self.streams.market_data.ping(options).await?;
                dump(&response)
            }
            "trading_ws.add_order" => {
                let request = decode(request)?;
                let response = self.trading_ws.add_order(request, options).await?;
                dump(&response)
            }
            "trading_ws.amend_order" => {
                let request = decode(request)?;
                let response = self.trading_ws.amend_order(request, options).await?;
                dump(&response)
            }
            "trading_ws.batch_add" => {
                let request = decode(request)?;
                let response = self.trading_ws.batch_add(request, options).await?;
                dump(&response)
            }
            "trading_ws.batch_cancel" => {
                let request = decode(request)?;
                let response = self.trading_ws.batch_cancel(request, options).await?;
                dump(&response)
            }
            "trading_ws.cancel_all" => {
                let request = decode(request)?;
                let response = self.trading_ws.cancel_all(request, options).await?;
                dump(&response)
            }
            "trading_ws.cancel_all_orders_after" => {
                let request = decode(request)?;
                let response = self
                    .trading_ws
                    .cancel_all_orders_after(request, options)
                    .await?;
                dump(&response)
            }
            "trading_ws.cancel_order" => {
                let request = decode(request)?;
                let response = self.trading_ws.cancel_order(request, options).await?;
                dump(&response)
            }
            "trading_ws.edit_order" => {
                let request = decode(request)?;
                let response = self.trading_ws.edit_order(request, options).await?;
                dump(&response)
            }
            _ => Err(Error::logic(format!("no rpc endpoint {function}"))),
        }
    }

    /// `call` through the `_raw` twin: the wire body as it came.
    #[doc(hidden)]
    pub async fn call_raw(
        &self,
        function: &str,
        request: serde_json::Value,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        match function {
            "spot.account.account_transfer" => {
                let request = decode(request)?;
                self.spot
                    .account
                    .account_transfer_raw(request, options)
                    .await
            }
            "spot.account.add_export" => {
                let request = decode(request)?;
                self.spot.account.add_export_raw(request, options).await
            }
            "spot.account.api_key_info" => {
                let request = decode(request)?;
                self.spot.account.api_key_info_raw(request, options).await
            }
            "spot.account.balance" => {
                let request = decode(request)?;
                self.spot.account.balance_raw(request, options).await
            }
            "spot.account.balance_ex" => {
                let request = decode(request)?;
                self.spot.account.balance_ex_raw(request, options).await
            }
            "spot.account.closed_orders" => {
                let request = decode(request)?;
                self.spot.account.closed_orders_raw(request, options).await
            }
            "spot.account.create_subaccount" => {
                let request = decode(request)?;
                self.spot
                    .account
                    .create_subaccount_raw(request, options)
                    .await
            }
            "spot.account.credit_lines" => {
                let request = decode(request)?;
                self.spot.account.credit_lines_raw(request, options).await
            }
            "spot.account.export_status" => {
                let request = decode(request)?;
                self.spot.account.export_status_raw(request, options).await
            }
            "spot.account.ledgers" => {
                let request = decode(request)?;
                self.spot.account.ledgers_raw(request, options).await
            }
            "spot.account.open_orders" => {
                let request = decode(request)?;
                self.spot.account.open_orders_raw(request, options).await
            }
            "spot.account.open_positions" => {
                let request = decode(request)?;
                self.spot.account.open_positions_raw(request, options).await
            }
            "spot.account.order_amends" => {
                let request = decode(request)?;
                self.spot.account.order_amends_raw(request, options).await
            }
            "spot.account.query_ledgers" => {
                let request = decode(request)?;
                self.spot.account.query_ledgers_raw(request, options).await
            }
            "spot.account.query_orders" => {
                let request = decode(request)?;
                self.spot.account.query_orders_raw(request, options).await
            }
            "spot.account.query_trades" => {
                let request = decode(request)?;
                self.spot.account.query_trades_raw(request, options).await
            }
            "spot.account.remove_export" => {
                let request = decode(request)?;
                self.spot.account.remove_export_raw(request, options).await
            }
            "spot.account.trade_balance" => {
                let request = decode(request)?;
                self.spot.account.trade_balance_raw(request, options).await
            }
            "spot.account.trade_volume" => {
                let request = decode(request)?;
                self.spot.account.trade_volume_raw(request, options).await
            }
            "spot.account.trades_history" => {
                let request = decode(request)?;
                self.spot.account.trades_history_raw(request, options).await
            }
            "spot.earn.allocate" => {
                let request = decode(request)?;
                self.spot.earn.allocate_raw(request, options).await
            }
            "spot.earn.allocate_status" => {
                let request = decode(request)?;
                self.spot.earn.allocate_status_raw(request, options).await
            }
            "spot.earn.allocations" => {
                let request = decode(request)?;
                self.spot.earn.allocations_raw(request, options).await
            }
            "spot.earn.deallocate" => {
                let request = decode(request)?;
                self.spot.earn.deallocate_raw(request, options).await
            }
            "spot.earn.deallocate_status" => {
                let request = decode(request)?;
                self.spot.earn.deallocate_status_raw(request, options).await
            }
            "spot.earn.strategies" => {
                let request = decode(request)?;
                self.spot.earn.strategies_raw(request, options).await
            }
            "spot.funding.deposit_addresses" => {
                let request = decode(request)?;
                self.spot
                    .funding
                    .deposit_addresses_raw(request, options)
                    .await
            }
            "spot.funding.deposit_methods" => {
                let request = decode(request)?;
                self.spot
                    .funding
                    .deposit_methods_raw(request, options)
                    .await
            }
            "spot.funding.deposit_status" => {
                let request = decode(request)?;
                self.spot.funding.deposit_status_raw(request, options).await
            }
            "spot.funding.wallet_transfer" => {
                let request = decode(request)?;
                self.spot
                    .funding
                    .wallet_transfer_raw(request, options)
                    .await
            }
            "spot.funding.withdraw" => {
                let request = decode(request)?;
                self.spot.funding.withdraw_raw(request, options).await
            }
            "spot.funding.withdraw_addresses" => {
                let request = decode(request)?;
                self.spot
                    .funding
                    .withdraw_addresses_raw(request, options)
                    .await
            }
            "spot.funding.withdraw_cancel" => {
                let request = decode(request)?;
                self.spot
                    .funding
                    .withdraw_cancel_raw(request, options)
                    .await
            }
            "spot.funding.withdraw_info" => {
                let request = decode(request)?;
                self.spot.funding.withdraw_info_raw(request, options).await
            }
            "spot.funding.withdraw_methods" => {
                let request = decode(request)?;
                self.spot
                    .funding
                    .withdraw_methods_raw(request, options)
                    .await
            }
            "spot.funding.withdraw_status" => {
                let request = decode(request)?;
                self.spot
                    .funding
                    .withdraw_status_raw(request, options)
                    .await
            }
            "spot.market_data.asset_pairs" => {
                let request = decode(request)?;
                self.spot
                    .market_data
                    .asset_pairs_raw(request, options)
                    .await
            }
            "spot.market_data.assets" => {
                let request = decode(request)?;
                self.spot.market_data.assets_raw(request, options).await
            }
            "spot.market_data.depth" => {
                let request = decode(request)?;
                self.spot.market_data.depth_raw(request, options).await
            }
            "spot.market_data.grouped_book" => {
                let request = decode(request)?;
                self.spot
                    .market_data
                    .grouped_book_raw(request, options)
                    .await
            }
            "spot.market_data.ohlc" => {
                let request = decode(request)?;
                self.spot.market_data.ohlc_raw(request, options).await
            }
            "spot.market_data.post_trade" => {
                let request = decode(request)?;
                self.spot.market_data.post_trade_raw(request, options).await
            }
            "spot.market_data.pre_trade" => {
                let request = decode(request)?;
                self.spot.market_data.pre_trade_raw(request, options).await
            }
            "spot.market_data.spread" => {
                let request = decode(request)?;
                self.spot.market_data.spread_raw(request, options).await
            }
            "spot.market_data.system_status" => {
                let _ = request;
                self.spot.market_data.system_status_raw(options).await
            }
            "spot.market_data.ticker" => {
                let request = decode(request)?;
                self.spot.market_data.ticker_raw(request, options).await
            }
            "spot.market_data.time" => {
                let _ = request;
                self.spot.market_data.time_raw(options).await
            }
            "spot.market_data.trades" => {
                let request = decode(request)?;
                self.spot.market_data.trades_raw(request, options).await
            }
            "spot.trading.add_order" => {
                let request = decode(request)?;
                self.spot.trading.add_order_raw(request, options).await
            }
            "spot.trading.add_order_batch" => {
                let request = decode(request)?;
                self.spot
                    .trading
                    .add_order_batch_raw(request, options)
                    .await
            }
            "spot.trading.amend_order" => {
                let request = decode(request)?;
                self.spot.trading.amend_order_raw(request, options).await
            }
            "spot.trading.cancel_all" => {
                let _ = request;
                self.spot.trading.cancel_all_raw(options).await
            }
            "spot.trading.cancel_all_orders_after" => {
                let request = decode(request)?;
                self.spot
                    .trading
                    .cancel_all_orders_after_raw(request, options)
                    .await
            }
            "spot.trading.cancel_order" => {
                let request = decode(request)?;
                self.spot.trading.cancel_order_raw(request, options).await
            }
            "spot.trading.cancel_order_batch" => {
                let request = decode(request)?;
                self.spot
                    .trading
                    .cancel_order_batch_raw(request, options)
                    .await
            }
            "spot.trading.edit_order" => {
                let request = decode(request)?;
                self.spot.trading.edit_order_raw(request, options).await
            }
            "spot.trading.get_websockets_token" => {
                let _ = request;
                self.spot.trading.get_websockets_token_raw(options).await
            }
            "streams.market_data.ping" => {
                let _ = request;
                self.streams.market_data.ping_raw(options).await
            }
            "trading_ws.add_order" => {
                let request = decode(request)?;
                self.trading_ws.add_order_raw(request, options).await
            }
            "trading_ws.amend_order" => {
                let request = decode(request)?;
                self.trading_ws.amend_order_raw(request, options).await
            }
            "trading_ws.batch_add" => {
                let request = decode(request)?;
                self.trading_ws.batch_add_raw(request, options).await
            }
            "trading_ws.batch_cancel" => {
                let request = decode(request)?;
                self.trading_ws.batch_cancel_raw(request, options).await
            }
            "trading_ws.cancel_all" => {
                let request = decode(request)?;
                self.trading_ws.cancel_all_raw(request, options).await
            }
            "trading_ws.cancel_all_orders_after" => {
                let request = decode(request)?;
                self.trading_ws
                    .cancel_all_orders_after_raw(request, options)
                    .await
            }
            "trading_ws.cancel_order" => {
                let request = decode(request)?;
                self.trading_ws.cancel_order_raw(request, options).await
            }
            "trading_ws.edit_order" => {
                let request = decode(request)?;
                self.trading_ws.edit_order_raw(request, options).await
            }
            _ => Err(Error::logic(format!("no rpc endpoint {function}"))),
        }
    }

    /// Subscribe to the `stream` endpoint `function` names (`streams.market_data.book`) with wire parameters; every pushed message is validated, then dumped back to a wire value.
    #[doc(hidden)]
    pub async fn subscribe(
        &self,
        function: &str,
        parameters: serde_json::Value,
        options: CallOptions,
    ) -> Result<Stream<serde_json::Value>> {
        match function {
            "streams.market_data.book" => {
                let parameters = decode(parameters)?;
                let stream = self.streams.market_data.book(parameters, options).await?;
                Ok(stream.map(|message| dump(&message)))
            }
            "streams.market_data.instrument" => {
                let parameters = decode(parameters)?;
                let stream = self
                    .streams
                    .market_data
                    .instrument(parameters, options)
                    .await?;
                Ok(stream.map(|message| dump(&message)))
            }
            "streams.market_data.ohlc" => {
                let parameters = decode(parameters)?;
                let stream = self.streams.market_data.ohlc(parameters, options).await?;
                Ok(stream.map(|message| dump(&message)))
            }
            "streams.market_data.status" => {
                let _ = parameters;
                let stream = self.streams.market_data.status(options).await?;
                Ok(stream.map(|message| dump(&message)))
            }
            "streams.market_data.ticker" => {
                let parameters = decode(parameters)?;
                let stream = self.streams.market_data.ticker(parameters, options).await?;
                Ok(stream.map(|message| dump(&message)))
            }
            "streams.market_data.trade" => {
                let parameters = decode(parameters)?;
                let stream = self.streams.market_data.trade(parameters, options).await?;
                Ok(stream.map(|message| dump(&message)))
            }
            "streams.private.balances" => {
                let parameters = decode(parameters)?;
                let stream = self.streams.private.balances(parameters, options).await?;
                Ok(stream.map(|message| dump(&message)))
            }
            "streams.private.executions" => {
                let parameters = decode(parameters)?;
                let stream = self.streams.private.executions(parameters, options).await?;
                Ok(stream.map(|message| dump(&message)))
            }
            _ => Err(Error::logic(format!("no stream endpoint {function}"))),
        }
    }

    /// `subscribe` through the `_raw` twin: the frames as they came.
    #[doc(hidden)]
    pub async fn subscribe_raw(
        &self,
        function: &str,
        parameters: serde_json::Value,
        options: CallOptions,
    ) -> Result<Stream<serde_json::Value>> {
        match function {
            "streams.market_data.book" => {
                let parameters = decode(parameters)?;
                self.streams.market_data.book_raw(parameters, options).await
            }
            "streams.market_data.instrument" => {
                let parameters = decode(parameters)?;
                self.streams
                    .market_data
                    .instrument_raw(parameters, options)
                    .await
            }
            "streams.market_data.ohlc" => {
                let parameters = decode(parameters)?;
                self.streams.market_data.ohlc_raw(parameters, options).await
            }
            "streams.market_data.status" => {
                let _ = parameters;
                self.streams.market_data.status_raw(options).await
            }
            "streams.market_data.ticker" => {
                let parameters = decode(parameters)?;
                self.streams
                    .market_data
                    .ticker_raw(parameters, options)
                    .await
            }
            "streams.market_data.trade" => {
                let parameters = decode(parameters)?;
                self.streams
                    .market_data
                    .trade_raw(parameters, options)
                    .await
            }
            "streams.private.balances" => {
                let parameters = decode(parameters)?;
                self.streams.private.balances_raw(parameters, options).await
            }
            "streams.private.executions" => {
                let parameters = decode(parameters)?;
                self.streams
                    .private
                    .executions_raw(parameters, options)
                    .await
            }
            _ => Err(Error::logic(format!("no stream endpoint {function}"))),
        }
    }
}
