# Generated by truewire — do not edit by hand.
"""Shapes shared by two or more endpoints under the client root, generated from `spec/schemas.json`."""

from typing_extensions import Literal, NotRequired, TypedDict


class ConditionalCloseOrder(TypedDict):
  """A conditional close order attached to a primary order."""

  ordertype: NotRequired[
    Literal[
      'limit',
      'iceberg',
      'stop-loss',
      'take-profit',
      'stop-loss-limit',
      'take-profit-limit',
      'trailing-stop',
      'trailing-stop-limit',
    ]
  ]
  """Conditional close order's execution model."""
  price: NotRequired[str]
  """Conditional close order price."""
  price2: NotRequired[str]
  """Conditional close order secondary price."""


class OrderTriggers(TypedDict):
  """Trigger price conditions for triggered order types."""

  reference: NotRequired[Literal['index', 'last']]
  """Reference price to track for triggering orders: `index` (the broader-market index price for this pair -- falls back to `last` during index-feed connectivity issues) or `last` (the last traded price in the Kraken order book for this pair)."""
  price: float
  """Amount for the trigger price -- static or relative, per `price_type`. E.g. 29000.5 with `price_type=static` triggers at that price; 5 with `pct` triggers when price rises 5%; -150 with `quote` triggers when price drops 150 quote-currency units. For `trailing-stop`/`trailing-stop-limit`, represents the reversion from the peak price and is always positive."""
  price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `price`: `static` (a static market price), `pct` (a percentage offset from the reference price), or `quote` (a notional offset in the quote currency)."""


class WsConditionalCloseOrder(TypedDict):
  """Template for the secondary close order generated on each fill of the primary order (One-Triggers-Other). The secondary order matches the executed quantity and takes the opposite side."""

  order_type: NotRequired[
    Literal[
      'limit',
      'stop-loss',
      'stop-loss-limit',
      'take-profit',
      'take-profit-limit',
      'trailing-stop',
      'trailing-stop-limit',
    ]
  ]
  """Order type of the secondary close order created on each fill."""
  limit_price: NotRequired[float]
  """Limit price on the secondary close order. Required for secondary order types that support a limit price: `limit`, `stop-loss-limit`, `take-profit-limit`."""
  limit_price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `limit_price` on the secondary order. Only available on trailing-stop-limit orders; for that order type the value is an offset from the trigger price (`0` sets the limit price equal to the trigger price)."""
  trigger_price: NotRequired[float]
  """Amount for the trigger price on the secondary close order -- static or relative, per `trigger_price_type`. Required on triggered secondary order types: `stop-loss`, `stop-loss-limit`, `take-profit`, `take-profit-limit`."""
  trigger_price_type: NotRequired[Literal['static', 'pct', 'quote']]
  """Units for `trigger_price` on the secondary order."""
  stop_price: NotRequired[float]
  """Deprecated -- use `trigger_price`. Trigger price on the secondary close order, for triggered secondary order types."""
