// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type Decimal, type HttpEndpoint, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'

export type AccountBalance = Record<string, Decimal>

export const AccountBalance: Codec<AccountBalance> = t.record(t.decimal)

export interface Request {
  /** Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity, `base` displays in terms of SPV tokens. */
  rebase_multiplier?: 'rebased' | 'base' | null
}

export const Request: Codec<Request> = t.object({
  rebase_multiplier: t.optional(t.nullable(t.literal('rebased', 'base'))),
})

/**
 * Retrieve all cash balances, net of pending withdrawals.
 *
 * **Note on Staking/Earn assets:** assets migrated from the legacy Staking system to the new Earn system may appear in balances and ledgers with symbol extensions -- `.B` (new yield-bearing products), `.F` (auto-earning Kraken Rewards), `.S`/`.M` (legacy staked/opt-in-reward balances), `.T` (tokenized assets). These are read-only for transacting; use the base asset (e.g. `USDT`) instead.
 *
 * **API Key Permissions Required:** `Funds permissions - Query`
 */
export class Balance {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  balance(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Retrieve all cash balances, net of pending withdrawals.
   *
   * **Note on Staking/Earn assets:** assets migrated from the legacy Staking system to the new Earn system may appear in balances and ledgers with symbol extensions -- `.B` (new yield-bearing products), `.F` (auto-earning Kraken Rewards), `.S`/`.M` (legacy staked/opt-in-reward balances), `.T` (tokenized assets). These are read-only for transacting; use the base asset (e.g. `USDT`) instead.
   *
   * **API Key Permissions Required:** `Funds permissions - Query`
   *
   * @see https://docs.kraken.com/api-reference/account-data/get-account-balance
   */
  balance(request?: Request, options?: CallOptions): Promise<AccountBalance>
  async balance(request?: Request, options?: CallOptions): Promise<AccountBalance> {
    return this.core.request({
      method: 'POST',
      path: '/0/private/Balance',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: AccountBalance,
      meta: { signed: true },
      ...options,
    })
  }
}
