//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::SpotMeta;

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Username for the subaccount.
    pub username: String,
    /// Email address for the subaccount.
    pub email: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

pub type Response = bool;

/// Create a trading subaccount. Must be called using an API key from the master account. Subaccounts are currently only available to institutional clients; contact your Account Manager for details.
///
/// **API Key Permissions Required:** `Funds permissions - Withdraw`
#[derive(Clone)]
pub struct CreateSubaccount {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl CreateSubaccount {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Create a trading subaccount. Must be called using an API key from the master account. Subaccounts are currently only available to institutional clients; contact your Account Manager for details.
    ///
    /// **API Key Permissions Required:** `Funds permissions - Withdraw`
    ///
    /// See <https://docs.kraken.com/api-reference/subaccounts/create-subaccount>.
    pub async fn create_subaccount(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<Response> {
        let raw = self.create_subaccount_raw(request, options).await?;
        decode(raw)
    }

    /// `create_subaccount` without validation: the wire body as it came.
    pub async fn create_subaccount_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/CreateSubaccount",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
