//! Generated by truewire — do not edit by hand.

use std::collections::HashMap;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampSecondsFloat,
};

use crate::meta::SpotMeta;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OpenPositionPosstatus {
    #[serde(rename = "open")]
    Open,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OpenPositionType {
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "sell")]
    Sell,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OpenPositionOrdertype {
    #[serde(rename = "market")]
    Market,
    #[serde(rename = "limit")]
    Limit,
    #[serde(rename = "iceberg")]
    Iceberg,
    #[serde(rename = "stop-loss")]
    StopLoss,
    #[serde(rename = "take-profit")]
    TakeProfit,
    #[serde(rename = "stop-loss-limit")]
    StopLossLimit,
    #[serde(rename = "take-profit-limit")]
    TakeProfitLimit,
    #[serde(rename = "trailing-stop")]
    TrailingStop,
    #[serde(rename = "trailing-stop-limit")]
    TrailingStopLimit,
    #[serde(rename = "settle-position")]
    SettlePosition,
}

/// One open margin position.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenPosition {
    /// Order ID responsible for the position.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ordertxid: Option<String>,
    /// Asset class of the position.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub class: Option<String>,
    /// Position status.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posstatus: Option<OpenPositionPosstatus>,
    /// Asset pair.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pair: Option<String>,
    /// Unix timestamp of the trade.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time: Option<TimestampSecondsFloat>,
    /// Direction of the position.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<OpenPositionType>,
    /// Order type used to open the position.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ordertype: Option<OpenPositionOrdertype>,
    /// Opening cost of the position (quote currency).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<String>,
    /// Opening fee of the position (quote currency).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fee: Option<String>,
    /// Position opening size (base currency).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vol: Option<String>,
    /// Quantity closed (base currency).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub vol_closed: Option<String>,
    /// Initial margin consumed (quote currency).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub margin: Option<String>,
    /// Current value of the remaining position. Only present if `docalcs` requested.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Unrealised P&L of the remaining position. Only present if `docalcs` requested.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub net: Option<String>,
    /// Funding cost and term of the position (e.g. "0.0100% per 4 hours").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terms: Option<String>,
    /// Timestamp of the next margin rollover fee.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rollovertm: Option<String>,
    /// Comma-delimited list of additional info.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub misc: Option<String>,
    /// Comma-delimited list of opening order flags.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub oflags: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestConsolidation {
    #[serde(rename = "market")]
    Market,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestRebaseMultiplier {
    #[serde(rename = "rebased")]
    Rebased,
    #[serde(rename = "base")]
    Base,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Comma-delimited list of txids to limit output to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    /// Whether to include P&L calculations.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub docalcs: Option<bool>,
    /// Consolidate positions by market/pair.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub consolidation: Option<RequestConsolidation>,
    /// Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity, `base` displays in terms of SPV tokens.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub rebase_multiplier: Option<Option<RequestRebaseMultiplier>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

pub type OpenPositionsResponse = HashMap<String, OpenPosition>;

/// Get information about open margin positions.
///
/// **API Key Permissions Required:** `Orders and trades - Query open orders & trades`
#[derive(Clone)]
pub struct OpenPositions {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl OpenPositions {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Get information about open margin positions.
    ///
    /// **API Key Permissions Required:** `Orders and trades - Query open orders & trades`
    ///
    /// See <https://docs.kraken.com/api-reference/account-data/get-open-positions>.
    pub async fn open_positions(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<OpenPositionsResponse> {
        let raw = self.open_positions_raw(request, options).await?;
        decode(raw)
    }

    /// `open_positions` without validation: the wire body as it came.
    pub async fn open_positions_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/OpenPositions",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
