//! Generated by truewire — do not edit by hand.

use std::collections::HashMap;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampSecondsFloat,
};

use crate::meta::SpotMeta;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LedgerEntryType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "trade")]
    Trade,
    #[serde(rename = "deposit")]
    Deposit,
    #[serde(rename = "withdrawal")]
    Withdrawal,
    #[serde(rename = "transfer")]
    Transfer,
    #[serde(rename = "margin")]
    Margin,
    #[serde(rename = "adjustment")]
    Adjustment,
    #[serde(rename = "rollover")]
    Rollover,
    #[serde(rename = "spend")]
    Spend,
    #[serde(rename = "receive")]
    Receive,
    #[serde(rename = "settled")]
    Settled,
    #[serde(rename = "credit")]
    Credit,
    #[serde(rename = "staking")]
    Staking,
    #[serde(rename = "reward")]
    Reward,
    #[serde(rename = "dividend")]
    Dividend,
    #[serde(rename = "sale")]
    Sale,
    #[serde(rename = "conversion")]
    Conversion,
    #[serde(rename = "nfttrade")]
    Nfttrade,
    #[serde(rename = "nftcreatorfee")]
    Nftcreatorfee,
    #[serde(rename = "nftrebate")]
    Nftrebate,
    #[serde(rename = "custodytransfer")]
    Custodytransfer,
}

/// One ledger entry.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct LedgerEntry {
    /// Reference ID of the parent transaction (trade, deposit, withdrawal, etc.) that caused the ledger entry.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refid: Option<String>,
    /// Unix timestamp of the ledger entry.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time: Option<TimestampSecondsFloat>,
    /// Type of ledger entry.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_: Option<LedgerEntryType>,
    /// Additional info relating to the ledger entry type, where applicable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtype: Option<String>,
    /// Asset class.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aclass: Option<String>,
    /// Asset.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    /// Transaction amount.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// Transaction fee.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fee: Option<String>,
    /// Resulting balance.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestRebaseMultiplier {
    #[serde(rename = "rebased")]
    Rebased,
    #[serde(rename = "base")]
    Base,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Comma-delimited list of ledger IDs to query info about (20 maximum).
    pub id: String,
    /// Whether or not to include trades related to position in output.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trades: Option<bool>,
    /// Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity, `base` displays in terms of SPV tokens.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub rebase_multiplier: Option<Option<RequestRebaseMultiplier>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

pub type QueriedLedgers = HashMap<String, LedgerEntry>;

/// Retrieve information about specific ledger entries, by ledger ID.
///
/// **Note on Staking/Earn assets:** assets migrated from the legacy Staking system to the new Earn system may appear with symbol extensions -- `.B` (new yield-bearing products), `.F` (auto-earning Kraken Rewards) -- these are read-only for transacting; use the base asset instead.
///
/// **API Key Permissions Required:** `Data - Query ledger entries`
#[derive(Clone)]
pub struct QueryLedgers {
    core: Arc<dyn HttpEndpoint<SpotMeta>>,
}

impl QueryLedgers {
    pub fn new(core: Arc<dyn HttpEndpoint<SpotMeta>>) -> Self {
        Self { core }
    }

    /// Retrieve information about specific ledger entries, by ledger ID.
    ///
    /// **Note on Staking/Earn assets:** assets migrated from the legacy Staking system to the new Earn system may appear with symbol extensions -- `.B` (new yield-bearing products), `.F` (auto-earning Kraken Rewards) -- these are read-only for transacting; use the base asset instead.
    ///
    /// **API Key Permissions Required:** `Data - Query ledger entries`
    ///
    /// See <https://docs.kraken.com/api-reference/account-data/query-ledgers>.
    pub async fn query_ledgers(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<QueriedLedgers> {
        let raw = self.query_ledgers_raw(request, options).await?;
        decode(raw)
    }

    /// `query_ledgers` without validation: the wire body as it came.
    pub async fn query_ledgers_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = SpotMeta { signed: Some(true) };
        let call = HttpCall {
            method: Some("POST"),
            path: "/0/private/QueryLedgers",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
