# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from kraken.core.endpoint.rpc import RpcEndpoint


class FeeScheduleTier(TypedDict):
  """One tier of a fee schedule."""

  maker_fee: str
  """Maker fee percentage for this tier."""
  taker_fee: str
  """Taker fee percentage for this tier."""
  min_spot_volume: NotRequired[str | None]
  """Minimum spot volume threshold for this tier, if applicable."""
  min_futures_volume: NotRequired[str | None]
  """Minimum 30-day futures volume threshold for this tier, if applicable."""
  min_assets_on_platform: NotRequired[str | None]
  """Minimum assets-on-platform threshold for this tier, if applicable."""
  active: NotRequired[bool | None]
  """Whether this is the currently active tier for the user."""


class FeeTierInfoFeesAnyOf0Additional(TypedDict):
  """Fee and volume tier information. Fees are expressed as percentages, volumes as absolute values."""

  fee: str
  """Current trading fee."""
  minfee: str
  """Minimum trading fee (highest volume tier)."""
  maxfee: str
  """Maximum trading fee (lowest volume tier)."""
  nextfee: NotRequired[str | None]
  """Next fee, applicable once the next volume tier is reached. `null` at the lowest fee tier."""
  tiervolume: str
  """Current spot-volume tier threshold."""
  tierfuturesvolume: NotRequired[str | None]
  """Current futures-volume tier threshold, when visible in the schedule."""
  nextvolume: NotRequired[str | None]
  """Next spot-volume tier threshold. `null` at the highest volume tier."""
  nextfuturesvolume: NotRequired[str | None]
  """Next futures-volume tier threshold, when visible in the schedule."""
  volumeoffset: NotRequired[str | None]
  """Volume adjustment, added to the trade volume when computing fees."""


class FeeTierInfoFeesMakerAnyOf0Additional(TypedDict):
  """Fee and volume tier information. Fees are expressed as percentages, volumes as absolute values."""

  fee: str
  """Current trading fee."""
  minfee: str
  """Minimum trading fee (highest volume tier)."""
  maxfee: str
  """Maximum trading fee (lowest volume tier)."""
  nextfee: NotRequired[str | None]
  """Next fee, applicable once the next volume tier is reached. `null` at the lowest fee tier."""
  tiervolume: str
  """Current spot-volume tier threshold."""
  tierfuturesvolume: NotRequired[str | None]
  """Current futures-volume tier threshold, when visible in the schedule."""
  nextvolume: NotRequired[str | None]
  """Next spot-volume tier threshold. `null` at the highest volume tier."""
  nextfuturesvolume: NotRequired[str | None]
  """Next futures-volume tier threshold, when visible in the schedule."""
  volumeoffset: NotRequired[str | None]
  """Volume adjustment, added to the trade volume when computing fees."""


class SubaccountVolume(TypedDict):
  """Trade volume for one subaccount in a domain."""

  iiban: str
  """The subaccount IIBAN."""
  volume: str
  """The subaccount trade volume."""


class TradeVolumeInputs(TypedDict):
  """Domain-aggregated input values evaluated against fee-schedule tier conditions."""

  domain_spot_volume_30d: str
  """30-day rolling spot trading volume."""
  domain_futures_volume_30d: str
  """30-day rolling futures trading volume."""
  domain_assets_on_platform: str
  """Assets on platform."""


class TradeVolumePairClass(TypedDict):
  """One asset pair, with its asset class."""

  asset: str
  """The pair name. All result amounts are expressed in units of this asset."""
  aclass: Literal[
    'currency',
    'forex',
    'equity',
    'equity_pair',
    'nft',
    'derivatives',
    'tokenized_asset',
    'futures_contract',
  ]
  """The asset class of the pair."""


FeeScheduleKeywords = TypedDict(
  'FeeScheduleKeywords',
  {
    'class': Literal[
      'currency',
      'forex',
      'equity',
      'equity_pair',
      'nft',
      'derivatives',
      'tokenized_asset',
      'futures_contract',
      'volume',
    ]
  },
)
"""
- `class`: Trading pair class.
"""


class FeeSchedule(FeeScheduleKeywords):
  """Full fee schedule for a trading pair."""

  pair: str
  """The trading pair the fee schedule applies to."""
  tiers: list[FeeScheduleTier]
  """The tiers of the fee schedule."""


RequestKeywords = TypedDict(
  'RequestKeywords', {'fee-info': NotRequired[str | bool | float]}
)
"""
- `fee-info`: Whether or not to include fee info in the results. Legacy parameter, accepted for backwards compatibility -- prefer omitting `pair` to exclude fee info.
"""


class Request(RequestKeywords):
  pair: NotRequired[str | list[TradeVolumePairClass]]
  """Asset pair(s) for which to retrieve fee info (optional, but required if any fee info is desired). Accepts either a comma-delimited list of pair names (each looked up as a forex pair), or a list of `{asset, aclass}` objects -- required to request fees for non-forex classes such as `equity_pair`, `derivatives`, or `futures_contract`."""
  fee_schedule: NotRequired[bool | None]
  """Whether to include the full fee schedule per trading pair in the response (returned in `schedules`)."""
  rebase_multiplier: NotRequired[Literal['rebased', 'base'] | None]
  """Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity, `base` displays in terms of SPV tokens."""


class TradeVolume(TypedDict):
  """30-day trading volume and, if requested, the resulting fee schedule."""

  currency: str
  """The asset used to express the trade volume value. `volume` is expressed in units of this asset."""
  asset_class: NotRequired[
    Literal[
      'currency',
      'forex',
      'equity',
      'equity_pair',
      'nft',
      'derivatives',
      'tokenized_asset',
      'futures_contract',
    ]
    | None
  ]
  """The class of the asset used to express the trade volume value."""
  volume: str
  """The total trading volume value."""
  inputs: TradeVolumeInputs
  fees: NotRequired[dict[str, FeeTierInfoFeesAnyOf0Additional] | None]
  """Taker fee per trading pair requested (one entry per pair). `null` if `pair` was not requested."""
  fees_maker: NotRequired[dict[str, FeeTierInfoFeesMakerAnyOf0Additional] | None]
  """Maker fee per trading pair requested (one entry per pair). `null` if `pair` was not requested."""
  volume_subaccounts: NotRequired[list[SubaccountVolume]]
  """Trade volume breakdown by subaccount. Only present when the requester is the domain's master account."""
  schedules: NotRequired[list[FeeSchedule] | None]
  """Full fee schedule per trading pair. Present only when `fee_schedule` was requested."""


class TradeVolumeEndpoint(RpcEndpoint):
  """Returns 30-day USD trading volume and the resulting fee schedule for any asset pair(s) provided. Fees are not included if `pair` is not specified, since Kraken fees differ by asset pair. If an asset pair is on a maker/taker fee schedule, the taker side is given in `fees` and the maker side in `fees_maker`; for pairs not on maker/taker, both sides appear only in `fees`. Set `fee_schedule` to `true` to additionally receive the full fee schedule per trading pair, in `schedules`.

  **API Key Permissions Required:** `Funds permissions - Query`"""

  @overload
  async def trade_volume(
    self,
    pair: str | list[TradeVolumePairClass] | None = None,
    *,
    fee_info: str | bool | float | None = None,
    fee_schedule: bool | None = None,
    rebase_multiplier: Literal['rebased', 'base'] | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def trade_volume(
    self,
    pair: str | list[TradeVolumePairClass] | None = None,
    *,
    fee_info: str | bool | float | None = None,
    fee_schedule: bool | None = None,
    rebase_multiplier: Literal['rebased', 'base'] | None = None,
    validate: bool | None = None,
  ) -> TradeVolume: ...
  async def trade_volume(
    self,
    pair: str | list[TradeVolumePairClass] | None = None,
    *,
    fee_info: str | bool | float | None = None,
    fee_schedule: bool | None = None,
    rebase_multiplier: Literal['rebased', 'base'] | None = None,
    validate: bool | None = None,
  ) -> TradeVolume:
    """Returns 30-day USD trading volume and the resulting fee schedule for any asset pair(s) provided. Fees are not included if `pair` is not specified, since Kraken fees differ by asset pair. If an asset pair is on a maker/taker fee schedule, the taker side is given in `fees` and the maker side in `fees_maker`; for pairs not on maker/taker, both sides appear only in `fees`. Set `fee_schedule` to `true` to additionally receive the full fee schedule per trading pair, in `schedules`.

    **API Key Permissions Required:** `Funds permissions - Query`

    Args:
      pair: Asset pair(s) for which to retrieve fee info (optional, but required if any fee info is desired). Accepts either a comma-delimited list of pair names (each looked up as a forex pair), or a list of `{asset, aclass}` objects -- required to request fees for non-forex classes such as `equity_pair`, `derivatives`, or `futures_contract`.
      fee_info: Whether or not to include fee info in the results. Legacy parameter, accepted for backwards compatibility -- prefer omitting `pair` to exclude fee info.
      fee_schedule: Whether to include the full fee schedule per trading pair in the response (returned in `schedules`).
      rebase_multiplier: Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity, `base` displays in terms of SPV tokens.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://docs.kraken.com/api-reference/account-data/get-trade-volume)
    """
    request: Request = Request()
    if pair is not None:
      request['pair'] = pair
    if fee_info is not None:
      request['fee-info'] = fee_info
    if fee_schedule is not None:
      request['fee_schedule'] = fee_schedule
    if rebase_multiplier is not None:
      request['rebase_multiplier'] = rebase_multiplier
    return await self.request(
      request,
      method='POST',
      path='/0/private/TradeVolume',
      meta={'signed': True},
      validate=validate,
      request_type=Request,
      response_type=TradeVolume,
    )
