// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { SpotMeta } from '../../meta.js'

export interface Request {
  /** Base asset used to determine balance. */
  asset?: string
  /** Optional parameter for viewing xstocks data. `rebased` displays in terms of underlying equity, `base` displays in terms of SPV tokens. */
  rebase_multiplier?: 'rebased' | 'base' | null
}

export const Request: Codec<Request> = t.object({
  asset: t.optional(t.string),
  rebase_multiplier: t.optional(t.nullable(t.literal('rebased', 'base'))),
})

/** Summary of collateral balances, margin position valuations, equity, and margin level. */
export interface TradeBalance {
  /** Equivalent balance (combined balance of all currencies). */
  eb?: string
  /** Trade balance (combined balance of all equity currencies). */
  tb?: string
  /** Margin amount of open positions. */
  m?: string
  /** Unrealized net profit/loss of open positions. */
  n?: string
  /** Cost basis of open positions. */
  c?: string
  /** Current floating valuation of open positions. */
  v?: string
  /** Equity: trade balance plus unrealized net profit/loss. */
  e?: string
  /** Free margin: equity minus initial margin (maximum margin available to open new positions). */
  mf?: string
  /** Margin free for orders: available margin that can be used for new orders. */
  mfo?: string
  /** Margin level: `(equity / initial margin) * 100`. Only present when margin positions are open. */
  ml?: string | null
  /** Unexecuted value: value of unfilled and partially filled orders. */
  uv?: string
}

export const TradeBalance: Codec<TradeBalance> = t.object({
  eb: t.optional(t.string),
  tb: t.optional(t.string),
  m: t.optional(t.string),
  n: t.optional(t.string),
  c: t.optional(t.string),
  v: t.optional(t.string),
  e: t.optional(t.string),
  mf: t.optional(t.string),
  mfo: t.optional(t.string),
  ml: t.optional(t.nullable(t.string)),
  uv: t.optional(t.string),
})

/**
 * Retrieve a summary of collateral balances, margin position valuations, equity and margin level.
 *
 * **API Key Permissions Required:** `Orders and trades - Query open orders & trades`
 */
export class TradeBalanceEndpoint {
  constructor(readonly core: HttpEndpoint<SpotMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  tradeBalance(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Retrieve a summary of collateral balances, margin position valuations, equity and margin level.
   *
   * **API Key Permissions Required:** `Orders and trades - Query open orders & trades`
   *
   * @see https://docs.kraken.com/api-reference/account-data/get-trade-balance
   */
  tradeBalance(request?: Request, options?: CallOptions): Promise<TradeBalance>
  async tradeBalance(request?: Request, options?: CallOptions): Promise<TradeBalance> {
    return this.core.request({
      method: 'POST',
      path: '/0/private/TradeBalance',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: TradeBalance,
      meta: { signed: true },
      ...options,
    })
  }
}
