// Code generated by truewire. DO NOT EDIT.

// Package assetpairs is the `spot.market_data.asset_pairs` endpoint.
package assetpairs

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/kraken/src/kraken/meta"
)

type AssetPairExecutionVenue string

const AssetPairExecutionVenueInternational AssetPairExecutionVenue = "international"
const AssetPairExecutionVenueBitnomialExchange AssetPairExecutionVenue = "bitnomial_exchange"

// UnmarshalJSON accepts only the literal's values.
func (v *AssetPairExecutionVenue) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, AssetPairExecutionVenueInternational, AssetPairExecutionVenueBitnomialExchange)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v AssetPairExecutionVenue) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, AssetPairExecutionVenueInternational, AssetPairExecutionVenueBitnomialExchange)
}

// On the wire, an array of the fields in order.
type AssetPairFeesItem struct {
	V0 float64
	V1 float64
}

// UnmarshalJSON decodes the array, position by position.
func (t *AssetPairFeesItem) UnmarshalJSON(data []byte) error {
	return truewire.DecodeTuple(data, truewire.ItemOf(&t.V0), truewire.ItemOf(&t.V1))
}

// MarshalJSON writes the positions as an array.
func (t AssetPairFeesItem) MarshalJSON() ([]byte, error) {
	return truewire.EncodeTuple(truewire.ItemOf(&t.V0), truewire.ItemOf(&t.V1))
}

// On the wire, an array of the fields in order.
type AssetPairFeesMakerItem struct {
	V0 float64
	V1 float64
}

// UnmarshalJSON decodes the array, position by position.
func (t *AssetPairFeesMakerItem) UnmarshalJSON(data []byte) error {
	return truewire.DecodeTuple(data, truewire.ItemOf(&t.V0), truewire.ItemOf(&t.V1))
}

// MarshalJSON writes the positions as an array.
func (t AssetPairFeesMakerItem) MarshalJSON() ([]byte, error) {
	return truewire.EncodeTuple(truewire.ItemOf(&t.V0), truewire.ItemOf(&t.V1))
}

type AssetPairStatus string

const AssetPairStatusOnline AssetPairStatus = "online"
const AssetPairStatusCancelOnly AssetPairStatus = "cancel_only"
const AssetPairStatusPostOnly AssetPairStatus = "post_only"
const AssetPairStatusLimitOnly AssetPairStatus = "limit_only"
const AssetPairStatusReduceOnly AssetPairStatus = "reduce_only"

// UnmarshalJSON accepts only the literal's values.
func (v *AssetPairStatus) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, AssetPairStatusOnline, AssetPairStatusCancelOnly, AssetPairStatusPostOnly, AssetPairStatusLimitOnly, AssetPairStatusReduceOnly)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v AssetPairStatus) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, AssetPairStatusOnline, AssetPairStatusCancelOnly, AssetPairStatusPostOnly, AssetPairStatusLimitOnly, AssetPairStatusReduceOnly)
}

// One tradable asset pair's info.
type AssetPair struct {
	// Alternate pair name.
	Altname *string
	// WebSocket pair name (if available).
	Wsname *string
	// Asset class of the base component.
	AclassBase *string
	// Asset id of the base component.
	Base *string
	// Asset class of the quote component.
	AclassQuote *string
	// Asset id of the quote component.
	Quote *string
	// Execution venue where the order book for this pair is listed.
	ExecutionVenue *AssetPairExecutionVenue
	// Volume lot size.
	Lot *string
	// Number of decimal places for prices in this pair.
	PairDecimals *int64
	// Number of decimal places for cost of trades in the pair (quote asset terms).
	CostDecimals *int64
	// Number of decimal places for volume (base asset terms).
	LotDecimals *int64
	// Amount to multiply lot volume by to get currency volume.
	LotMultiplier *int64
	// Leverage amounts available when buying.
	LeverageBuy []int64
	// Leverage amounts available when selling.
	LeverageSell []int64
	// Taker fee schedule.
	Fees []AssetPairFeesItem
	// Maker fee schedule, if the pair is on maker/taker fees.
	FeesMaker []AssetPairFeesMakerItem
	// Volume discount currency.
	FeeVolumeCurrency *string
	// Margin call level.
	MarginCall *int64
	// Stop-out/liquidation margin level.
	MarginStop *int64
	// Same value as `margin_stop`, returned under this name instead when `info=margin` is requested. Not in upstream's published field list; confirmed live -- see notes.
	MarginLevel *int64
	// Minimum order size (in terms of base currency).
	Ordermin *truewire.Decimal
	// Minimum order cost (in terms of quote currency).
	Costmin *truewire.Decimal
	// Minimum increment between valid price levels.
	TickSize *truewire.Decimal
	// Status of the pair.
	Status *AssetPairStatus
	// Maximum long margin position size (in terms of base currency).
	LongPositionLimit *int64
	// Maximum short margin position size (in terms of base currency).
	ShortPositionLimit *int64
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *AssetPair) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalField("altname", &r.Altname),
		truewire.OptionalField("wsname", &r.Wsname),
		truewire.OptionalField("aclass_base", &r.AclassBase),
		truewire.OptionalField("base", &r.Base),
		truewire.OptionalField("aclass_quote", &r.AclassQuote),
		truewire.OptionalField("quote", &r.Quote),
		truewire.OptionalField("execution_venue", &r.ExecutionVenue),
		truewire.OptionalField("lot", &r.Lot),
		truewire.OptionalField("pair_decimals", &r.PairDecimals),
		truewire.OptionalField("cost_decimals", &r.CostDecimals),
		truewire.OptionalField("lot_decimals", &r.LotDecimals),
		truewire.OptionalField("lot_multiplier", &r.LotMultiplier),
		truewire.OptionalField("leverage_buy", &r.LeverageBuy),
		truewire.OptionalField("leverage_sell", &r.LeverageSell),
		truewire.OptionalField("fees", &r.Fees),
		truewire.OptionalField("fees_maker", &r.FeesMaker),
		truewire.OptionalField("fee_volume_currency", &r.FeeVolumeCurrency),
		truewire.OptionalField("margin_call", &r.MarginCall),
		truewire.OptionalField("margin_stop", &r.MarginStop),
		truewire.OptionalField("margin_level", &r.MarginLevel),
		truewire.OptionalField("ordermin", &r.Ordermin),
		truewire.OptionalField("costmin", &r.Costmin),
		truewire.OptionalField("tick_size", &r.TickSize),
		truewire.OptionalField("status", &r.Status),
		truewire.OptionalField("long_position_limit", &r.LongPositionLimit),
		truewire.OptionalField("short_position_limit", &r.ShortPositionLimit),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r AssetPair) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalField("altname", &r.Altname),
		truewire.OptionalField("wsname", &r.Wsname),
		truewire.OptionalField("aclass_base", &r.AclassBase),
		truewire.OptionalField("base", &r.Base),
		truewire.OptionalField("aclass_quote", &r.AclassQuote),
		truewire.OptionalField("quote", &r.Quote),
		truewire.OptionalField("execution_venue", &r.ExecutionVenue),
		truewire.OptionalField("lot", &r.Lot),
		truewire.OptionalField("pair_decimals", &r.PairDecimals),
		truewire.OptionalField("cost_decimals", &r.CostDecimals),
		truewire.OptionalField("lot_decimals", &r.LotDecimals),
		truewire.OptionalField("lot_multiplier", &r.LotMultiplier),
		truewire.OptionalField("leverage_buy", &r.LeverageBuy),
		truewire.OptionalField("leverage_sell", &r.LeverageSell),
		truewire.OptionalField("fees", &r.Fees),
		truewire.OptionalField("fees_maker", &r.FeesMaker),
		truewire.OptionalField("fee_volume_currency", &r.FeeVolumeCurrency),
		truewire.OptionalField("margin_call", &r.MarginCall),
		truewire.OptionalField("margin_stop", &r.MarginStop),
		truewire.OptionalField("margin_level", &r.MarginLevel),
		truewire.OptionalField("ordermin", &r.Ordermin),
		truewire.OptionalField("costmin", &r.Costmin),
		truewire.OptionalField("tick_size", &r.TickSize),
		truewire.OptionalField("status", &r.Status),
		truewire.OptionalField("long_position_limit", &r.LongPositionLimit),
		truewire.OptionalField("short_position_limit", &r.ShortPositionLimit),
	)
}

type RequestAclassBase string

const RequestAclassBaseCurrency RequestAclassBase = "currency"
const RequestAclassBaseTokenizedAsset RequestAclassBase = "tokenized_asset"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestAclassBase) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestAclassBaseCurrency, RequestAclassBaseTokenizedAsset)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestAclassBase) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestAclassBaseCurrency, RequestAclassBaseTokenizedAsset)
}

type RequestInfo string

const RequestInfoInfo RequestInfo = "info"
const RequestInfoLeverage RequestInfo = "leverage"
const RequestInfoFees RequestInfo = "fees"
const RequestInfoMargin RequestInfo = "margin"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestInfo) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestInfoInfo, RequestInfoLeverage, RequestInfoFees, RequestInfoMargin)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestInfo) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestInfoInfo, RequestInfoLeverage, RequestInfoFees, RequestInfoMargin)
}

type RequestExecutionVenue string

const RequestExecutionVenueInternational RequestExecutionVenue = "international"
const RequestExecutionVenueBitnomialExchange RequestExecutionVenue = "bitnomial_exchange"

// UnmarshalJSON accepts only the literal's values.
func (v *RequestExecutionVenue) UnmarshalJSON(data []byte) error {
	return truewire.DecodeLiteral(data, v, RequestExecutionVenueInternational, RequestExecutionVenueBitnomialExchange)
}

// MarshalJSON writes the value, checking it is one of the literal's.
func (v RequestExecutionVenue) MarshalJSON() ([]byte, error) {
	return truewire.EncodeLiteral(v, RequestExecutionVenueInternational, RequestExecutionVenueBitnomialExchange)
}

type Request struct {
	// Controls whether response keys and asset identifier fields use Kraken's internal names or display names. Omitted (default): internal names are used, pair keys use the internal format (`XXBTZUSD`), and `base`/`quote`/`fee_volume_currency` use internal names. `assetVersion=1`: display names are used, pair keys become the slash-separated display format (`BTC/USD`), and `base`/`quote`/`fee_volume_currency` also switch to display names. Only `assetVersion=1` is currently supported. The `altname`/`wsname` fields are not affected by this parameter.
	AssetVersion *int64
	// Asset pairs to get data for (optional, default all tradeable pairs).
	Pair *string
	// Filters the asset class to retrieve: `currency` (spot currency pairs) or `tokenized_asset` (tokenized asset pairs, i.e. xstocks).
	AclassBase *RequestAclassBase
	// Info to retrieve: `info` (all info), `leverage` (leverage info), `fees` (fee schedule), or `margin` (margin info).
	Info *RequestInfo
	// Filter for response to only include pairs available in the provided country/region (ISO 3166-1 alpha-2 code).
	CountryCode *string
	// Filter by execution venue: `international` (International exchange) or `bitnomial_exchange` (Bitnomial exchange).
	ExecutionVenue *RequestExecutionVenue
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Request) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.OptionalField("assetVersion", &r.AssetVersion),
		truewire.OptionalField("pair", &r.Pair),
		truewire.OptionalField("aclass_base", &r.AclassBase),
		truewire.OptionalField("info", &r.Info),
		truewire.OptionalField("country_code", &r.CountryCode),
		truewire.OptionalField("execution_venue", &r.ExecutionVenue),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Request) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.OptionalField("assetVersion", &r.AssetVersion),
		truewire.OptionalField("pair", &r.Pair),
		truewire.OptionalField("aclass_base", &r.AclassBase),
		truewire.OptionalField("info", &r.Info),
		truewire.OptionalField("country_code", &r.CountryCode),
		truewire.OptionalField("execution_venue", &r.ExecutionVenue),
	)
}

type Response = map[string]AssetPair

// Endpoint is the `spot.market_data.asset_pairs` endpoint.
//
// Get tradable asset pairs.
type Endpoint struct {
	core truewire.HttpEndpoint
}

// New returns the endpoint over core.
func New(core truewire.HttpEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// Get tradable asset pairs.
//
// See https://docs.kraken.com/api-reference/market-data/get-tradable-asset-pairs.
func (e *Endpoint) AssetPairs(ctx context.Context, request Request, opts ...truewire.CallOption) (Response, error) {
	return truewire.DecodeResult[Response](e.AssetPairsRaw(ctx, request, opts...))
}

// AssetPairsRaw is AssetPairs without validation: the wire body as it came.
func (e *Endpoint) AssetPairsRaw(ctx context.Context, request Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	body, err := truewire.Dump(request)
	if err != nil {
		return nil, err
	}
	return e.core.Request(ctx, truewire.HttpCall{Method: "GET", Path: "/0/public/AssetPairs", Request: body, Meta: meta.SpotMeta{}, Options: truewire.Options(opts...)})
}
