"""The TypeScript backend's gRPC endpoints (ADR 0017).

The `grpc_client` fixture's generated package is committed as
`packages/testing-ts/test/grpc_demo/`, where `@truewire/testing`'s own suite type-checks it
and replays every recording through it against the in-process gRPC mock. This file pins
that committed output to what the backend renders today, and checks the rendering rules
on their own. After a deliberate change, regenerate with `truewire protos typescript` and
`truewire generate typescript` in a copy of the fixture and copy `src/grpc_demo/` over.
"""
from pathlib import Path

import pytest

from truewire.codegen.typescript import render_package
from truewire.codegen.typescript.grpc import proto_camel_case, rpc_local_name
from truewire.plan.build import build_plan
from truewire.project import load_project

FIXTURE = Path(__file__).parent / 'fixtures' / 'grpc_client'
COMMITTED = Path(__file__).parents[3] / 'packages' / 'testing-ts' / 'test' / 'grpc_demo'
BANNER = '// Generated by truewire — do not edit by hand.\n'


@pytest.fixture(scope='module')
def rendered():
  project = load_project(FIXTURE)
  return render_package(build_plan(project), project)


def test_names_follow_protobuf_es():
  assert proto_camel_case('next_key') == 'nextKey'
  assert proto_camel_case('tx_responses') == 'txResponses'
  assert proto_camel_case('height_2x') == 'height2x'
  assert proto_camel_case('constructor') == 'constructor$'
  assert rpc_local_name('AllBalances') == 'allBalances'


def test_endpoint_calls_the_grpc_core(rendered):
  source = rendered.files['bank/balance.ts']
  assert "import type { GrpcCallOptions, GrpcEndpoint } from '@truewire/core/grpc'" in source
  assert "import { Query, type QueryBalanceRequestSchema, type QueryBalanceResponse } from '../protos/demo/bank/v1/query_pb.js'" in source
  assert 'export type Request = MessageInitShape<typeof QueryBalanceRequestSchema>' in source
  assert 'export const method = Query.method.balance' in source
  assert 'constructor(readonly core: GrpcEndpoint<GrpcMeta>) {}' in source
  assert 'return this.core.unary({ method, request, meta: { public: true }, ...options })' in source
  assert 'validate: false' not in source
  assert rendered.skipped == []


def test_walkers_clone_the_request_and_read_the_stub_fields(rendered):
  token = rendered.files['bank/all_balances.ts']
  assert 'allBalancesPaged(request: Request = {}, options?: GrpcCallOptions): PaginatedResponse<Row, Cursor> {' in token
  assert 'const at = clone(QueryAllBalancesRequestSchema, create(QueryAllBalancesRequestSchema, request))' in token
  assert 'at.pagination ??= create(PageRequestSchema)' in token
  assert 'const following = response.pagination?.nextKey' in token
  assert 'export type Cursor = Uint8Array' in token
  page = rendered.files['bank/search.ts']
  assert 'export type Row = SearchResponse_Hit' in page
  assert 'export type Cursor = bigint' in page
  assert 'return new PaginatedResponse<Row, Cursor>(1n, next)' in page


def test_router_delegates_with_qualified_types(rendered):
  router = rendered.files['bank/index.ts']
  assert 'constructor(readonly core: GrpcEndpoint<GrpcMeta>) {' in router
  assert 'allBalancesPaged(request?: allBalances.Request, options?: GrpcCallOptions): PaginatedResponse<allBalances.Row, allBalances.Cursor> {' in router
  assert 'validate: false' not in router


def test_committed_package_is_what_the_backend_renders(rendered):
  if not COMMITTED.is_dir():
    pytest.skip('packages/testing-ts is not checked out beside the package')
  committed = {
    path.relative_to(COMMITTED).as_posix(): path.read_text()
    for path in COMMITTED.rglob('*.ts') if not path.relative_to(COMMITTED).as_posix().startswith('protos/')
  }
  expected = {path: BANNER + content if not content.startswith(BANNER) else content for path, content in rendered.files.items()}
  assert sorted(committed) == sorted(expected)
  for path, content in expected.items():
    assert committed[path] == content, path
  assert (COMMITTED / 'protos' / 'demo' / 'bank' / 'v1' / 'query_pb.ts').is_file()
