"""A deterministic printer for generated Go that `gofmt` leaves alone.

No formatter runs over the output, but `gofmt -l` runs over the generated packages in CI,
so the printer reproduces the `gofmt` decisions the emitted shapes can trigger: tab
indentation, the columns of consecutive struct fields (a run is broken by a comment line or
a blank line, exactly as `gofmt`'s tabwriter breaks it), and import blocks sorted by path
within each blank-line-separated group. Every other construct is emitted in the one form
`gofmt` produces for it, and nothing that `gofmt` would align (a multi-line keyed literal,
a `const` block) is emitted at all.
"""
from collections.abc import Iterator
from contextlib import contextmanager

BANNER = '// Code generated by truewire. DO NOT EDIT.'
"""First line of every generated `.go` file: the marker `go generate` tooling and linters
recognise as generated code."""

INDENT = '\t'


class Writer:
  """Accumulates lines at the current indent; `render` joins them with one trailing newline."""

  def __init__(self, level: int = 0):
    self._lines: list[str] = []
    self._level = level

  def line(self, text: str = ''):
    self._lines.append(INDENT * self._level + text if text else '')

  def lines(self, text: str):
    for item in text.split('\n'):
      self.line(item)

  def raw(self, text: str):
    """Append already-indented lines verbatim."""
    self._lines.extend(text.split('\n'))

  def blank(self):
    if self._lines and self._lines[-1] != '':
      self._lines.append('')

  @contextmanager
  def indented(self) -> Iterator[None]:
    self._level += 1
    try:
      yield
    finally:
      self._level -= 1

  @contextmanager
  def block(self, opener: str, closer: str = '}') -> Iterator[None]:
    self.line(opener)
    with self.indented():
      yield
    self.line(closer)

  def doc(self, *paragraphs: str | None):
    """`//` lines from the non-empty paragraphs, blank-comment-separated.

    Each paragraph's lines are stripped and joined into one line, so no line of a doc
    comment is indented: `gofmt` rewrites an indented doc line into a code block or a list,
    and a generated comment that `gofmt` rewrites fails `gofmt -l`.
    """
    body: list[str] = []
    for paragraph in paragraphs:
      if paragraph is None or not paragraph.strip():
        continue
      for part in _paragraphs(paragraph):
        if body:
          body.append('')
        body.append(part)
    for item in body:
      self.line(f'// {item}'.rstrip())

  def struct(self, opener: str, entries: list['Entry']):
    """A struct type whose fields `gofmt` aligns: `entries` in order, each a field (name and
    type) with its doc lines, or `None` for a blank line."""
    self.line(opener)
    with self.indented():
      run: list[tuple[str, str]] = []

      def flush():
        if not run:
          return
        width = max(len(name) for name, _ in run)
        for name, type_ in run:
          self.line(f'{name.ljust(width)} {type_}')
        run.clear()

      for entry in entries:
        if entry is None:
          flush()
          self.blank()
          continue
        name, type_, doc = entry
        if doc:
          flush()
          self.doc(doc)
        run.append((name, type_))
      flush()
    self.line('}')

  def render(self) -> str:
    return '\n'.join(self._lines).rstrip('\n') + '\n'


Entry = tuple[str, str, str | None] | None
"""A struct field: `(name, type, doc)`, or `None` for a blank line between groups."""


def _paragraphs(text: str) -> list[str]:
  out: list[str] = []
  current: list[str] = []
  for raw in text.strip().split('\n'):
    line = ' '.join(raw.replace('\t', ' ').split())
    if not line:
      if current:
        out.append(' '.join(current))
        current = []
      continue
    current.append(line)
  if current:
    out.append(' '.join(current))
  return out


class Imports:
  """One file's imports: the standard library group, then everything else, each sorted by
  path the way `gofmt` sorts an import group."""

  def __init__(self):
    self._std: set[str] = set()
    self._other: dict[str, str | None] = {}
    """Import path -> alias (or `None` for the package's own name)."""

  def std(self, path: str):
    self._std.add(path)

  def add(self, path: str, alias: str | None = None):
    self._other[path] = alias

  def __contains__(self, path: str) -> bool:
    return path in self._std or path in self._other

  def render(self) -> list[str]:
    if not self._std and not self._other:
      return []
    out = ['import (']
    for path in sorted(self._std):
      out.append(f'\t"{path}"')
    if self._std and self._other:
      out.append('')
    for path in sorted(self._other):
      alias = self._other[path]
      out.append(f'\t{alias} "{path}"' if alias else f'\t"{path}"')
    out.append(')')
    return out


__all__ = ['BANNER', 'INDENT', 'Entry', 'Imports', 'Writer']
