// Code generated by truewire. DO NOT EDIT.

// Package listtags is the `repos.list_tags` endpoint.
package listtags

import (
	"context"
	"encoding/json"

	truewire "truewire.dev/core"
	"truewire.dev/examples/github/src/github/meta"
	"truewire.dev/examples/github/src/github/types"
)

// Which repository, and which page.
type Request struct {
	// Account owner of the repository, case-insensitive.
	Owner string
	// Repository name without the `.git` extension, case-insensitive.
	Repo string
	// Results per page, at most 100.
	PerPage *int64
	// Page number of the results to fetch, starting at 1.
	Page *int64
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Request) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("owner", &r.Owner),
		truewire.Required("repo", &r.Repo),
		truewire.OptionalField("per_page", &r.PerPage),
		truewire.OptionalField("page", &r.Page),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Request) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("owner", &r.Owner),
		truewire.Required("repo", &r.Repo),
		truewire.OptionalField("per_page", &r.PerPage),
		truewire.OptionalField("page", &r.Page),
	)
}

// A git tag and the commit it points at.
type Tag struct {
	// Tag name.
	Name string
	// Zip archive of the tagged tree.
	ZipballURL *string
	// Tar archive of the tagged tree.
	TarballURL *string
	// Tagged commit.
	Commit types.CommitRef
	// GraphQL node id.
	NodeID *string
	// Extra holds the keys the spec does not document, kept as they came.
	Extra map[string]json.RawMessage
}

// UnmarshalJSON decodes the wire object, checking every documented key.
func (r *Tag) UnmarshalJSON(data []byte) error {
	return truewire.DecodeObject(data, &r.Extra,
		truewire.Required("name", &r.Name),
		truewire.OptionalField("zipball_url", &r.ZipballURL),
		truewire.OptionalField("tarball_url", &r.TarballURL),
		truewire.Required("commit", &r.Commit),
		truewire.OptionalField("node_id", &r.NodeID),
	)
}

// MarshalJSON writes the wire object: the documented keys, then Extra.
func (r Tag) MarshalJSON() ([]byte, error) {
	return truewire.EncodeObject(r.Extra,
		truewire.Required("name", &r.Name),
		truewire.OptionalField("zipball_url", &r.ZipballURL),
		truewire.OptionalField("tarball_url", &r.TarballURL),
		truewire.Required("commit", &r.Commit),
		truewire.OptionalField("node_id", &r.NodeID),
	)
}

type Tags = []Tag

// PagedRequest is Request without `page`, which ListTagsPaged advances.
type PagedRequest struct {
	// Account owner of the repository, case-insensitive.
	Owner string
	// Repository name without the `.git` extension, case-insensitive.
	Repo string
	// Results per page, at most 100.
	PerPage *int64
	// Extra holds keys the spec does not document, sent as they are.
	Extra map[string]json.RawMessage
}

// at is the Request for one page of the walk.
func (p PagedRequest) at(pageValue *int64) Request {
	return Request{Owner: p.Owner, Repo: p.Repo, PerPage: p.PerPage, Page: pageValue, Extra: p.Extra}
}

// Endpoint is the `repos.list_tags` endpoint.
//
// List repository tags, newest first.
type Endpoint struct {
	core truewire.HttpEndpoint
}

// New returns the endpoint over core.
func New(core truewire.HttpEndpoint) *Endpoint {
	return &Endpoint{core: core}
}

// List repository tags, newest first.
//
// ListTagsPaged is the paged variant of ListTags: All for every row, or range over Rows/Pages one page at a time.
//
// See https://docs.github.com/en/rest/repos/repos#list-repository-tags.
func (e *Endpoint) ListTagsPaged(request PagedRequest, opts ...truewire.CallOption) *truewire.PaginatedResponse[Tag, int64] {
	size := 30
	if request.PerPage != nil {
		size = min(int(*request.PerPage), 100)
	}
	next := func(ctx context.Context, state int64) ([]Tag, *int64, error) {
		response, err := e.ListTags(ctx, request.at(&state), opts...)
		if err != nil {
			return nil, nil, err
		}
		rows := response
		if truewire.Exhausted(len(rows), size) {
			return rows, nil, nil
		}
		following := state + 1
		return rows, &following, nil
	}
	return truewire.NewPaginatedResponse(int64(1), next)
}

// List repository tags, newest first.
//
// See https://docs.github.com/en/rest/repos/repos#list-repository-tags.
func (e *Endpoint) ListTags(ctx context.Context, request Request, opts ...truewire.CallOption) (Tags, error) {
	return truewire.DecodeResult[Tags](e.ListTagsRaw(ctx, request, opts...))
}

// ListTagsRaw is ListTags without validation: the wire body as it came.
func (e *Endpoint) ListTagsRaw(ctx context.Context, request Request, opts ...truewire.CallOption) (json.RawMessage, error) {
	body, err := truewire.Dump(request)
	if err != nil {
		return nil, err
	}
	return e.core.Request(ctx, truewire.HttpCall{Method: "GET", Path: "/repos/{owner}/{repo}/tags", Request: body, Meta: meta.DefaultMeta{Public: truewire.Ptr(true)}, Options: truewire.Options(opts...)})
}
